- README.md
- docker-compose.yml
Docker has done some confusing things with the Compose file format. They've introduced a [Compose specification](https://docs.docker.com/compose/compose-file/#name-top-level-element) which has some incompatibilities with the existing tooling, and then labeled the [existing](https://docs.docker.com/compose/compose-file/compose-file-v3/) [versions](https://docs.docker.com/compose/compose-file/compose-file-v2/) that are well-supported by all reasonably-current versions of the Compose tool as "legacy". The top-level `name:` key is new in the "specification" version, but not present in the "legacy" versions.
> Remove 'name' key from docker compose

- nexus/peer-bigquery/src/lib.rs
- nexus/peer-cursor/src/lib.rs
- nexus/peer-postgres/src/lib.rs
- nexus/peer-snowflake/src/lib.rs
- nexus/server/src/main.rs
CREATE PEER flow now checks if the user-provided configuration can successfully connect to the peer.
Note that these sql files are CREATE PEER commands of the three peers.
```shell
amogh=> \i bq.sql
psql:bq.sql:37: ERROR:  [peer]: invalid configuration: unable to create GcpClient.
amogh=> \i sf.sql
psql:sf.sql:62: ERROR:  [peer]: invalid configuration: Internal error: error decoding response body: expected value at line 1 column 1
amogh=> \i pg.sql
psql:pg.sql:8: ERROR:  [peer]: invalid configuration: error encountered while connecting to postgres Error { kind: Connect, cause: Some(Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" }) }
```
> Connectivity Checks in CREATE PEER Flow

- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/snowflake/snowflake.go
1) [CDC] rejects source tables which have composite primary keys, since they aren't supported yet.
2) [QRep] supporting tables with int32 and int16 primary keys properly now, along with handling edge case of source table not having any rows so MIN() and MAX() return nil instead of a a number/timestamp.
3) minor variable name nits
> minor bug fixes

- nexus/peer-postgres/src/lib.rs
Sets timeout for PG peer connection to 15 seconds. 
Fixes #209
> Fixes long wait for PG peer creation with invalid host 

- flow/connectors/postgres/client.go
Fixing a edge case in the normalization step for Postgres CDC where a delete record in the same batch as a insert record does not get handled properly.
> [URGENT] fixing MERGE statement for Postgres CDC

- flow/activities/flowable.go
- flow/cmd/worker.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/core.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/s3/s3.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/sqlserver/sqlserver.go
- flow/e2e/peer_flow_test.go
- flow/workflows/peer_flow.go
- flow/workflows/setup_flow.go
- flow/workflows/snapshot_flow.go
- This now happens after setup flow, this is a precursor to snapshot cloning.
- Only postgres connector will support it for the foreseeable future so remove the method from the core interface.
> Refactor SnapshotFlow out of setup flow

- flow/activities/flowable.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/postgres_cdc_test.go
- flow/connectors/postgres/postgres_repl_test.go
- flow/connectors/postgres/slot_signal.go
1. This will ensure that we have a valid snapshot while the initial clone happens.
2. Add tests to check simple slot creation
> Add signals to postgres replication for keep-alive

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/qvalue_convert.go
- nexus/peer-bigquery/src/stream.rs
- Now supports array columns for BigQuery mirror
- Fixes an issue where tables with null timestamp values in BigQuery tables could not be queried
> Array and Null Timestamp Fixes

- flow/connectors/postgres/client.go
Now quotes column names in the CreateNormalizedStep of Postgres as sink for cdc
> Quote column names pg

- flow/connectors/bigquery/qrep_sync_method.go
This fix is to allow having reserve keywords as column names in BigQuery
> Backticks for BQ Column Names in Multi-Insert Merge

- flow/connectors/bigquery/bigquery.go
- flow/e2e/peer_flow_test.go
- Adds a case for Arrays in NormalizeRecords step which handles array values
- Adds array columns in tests
> Array support for BigQuery CDC

- docker-compose.yml
This addition helps cancel workflows from the temporal UI, avoiding the "Missing csrf token in request header" error. Reference: [1]
[1] https://community.temporal.io/t/missing-csrf-token-in-request-header/7410
> Fix Linux docker-compose error and add TEMPORAL_CSRF_COOKIE_INSECURE=true

- flow/activities/flowable.go
CDC to Eventhub errors in SyncFlow with 'GetLastSyncBatchID not supported for Eventhub', because in `flowable.go`'s `StartFlow` this method is being called for catalog metrics.
Eventhub does not have this method implemented so we can just ignore the error in this section and have sync ID in the metrics start from 0:
```Go
if a.CatalogMirrorMonitor.IsActive() && len(records.Records) > 0 {
syncBatchID, err := dest.GetLastSyncBatchID(input.FlowConnectionConfigs.FlowJobName)
if err != nil && conn.Destination.Type != protos.DBType_EVENTHUB {
return nil, err
}
....
}
```
> Ignore error for catalog monitor for EH

- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/cdc.go
`res` (result of normalize flow) in the below call is nil in case of Eventhub so we make it a non-nil:
```Go
err = a.CatalogMirrorMonitor.UpdateEndTimeForCDCBatch(ctx, input.FlowConnectionConfigs.FlowJobName,
res.EndBatchID)
```
> Eventhub Normalize Fix

- flow/activities/flowable.go
> add timing info for pull and push

- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
When we check for primary keys during pull, we should also check for no-pkey but replica identity case for the table.
> Replica Identity Check

- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/utils/partition/partition.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
- flow/generated/protos/flow.pb.go
- nexus/pt/src/peerdb_flow.rs
- nexus/pt/src/peerdb_flow.serde.rs
- protos/flow.proto
- ui/grpc_generated/flow.ts
- Support for XMIN as watermark column in QRep
You must type-cast the `xmin` column in the query of your QRep create-mirror command :
```sql
$$ SELECT * FROM mytable WHERE xmin::text::bigint BETWEEN {{.start}} AND {{.end}} $$
```
Fixes #397
> XMIN for Query Replication

- nexus/analyzer/src/lib.rs
- nexus/flow-rs/src/grpc.rs
- nexus/pt/src/flow_model.rs
- Adds `max_batch_size` parameter to the create mirror parsing flow
> max_batch_size parameter fix

- flow/cmd/handler.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/eventhub/metadata.go
- flow/go.mod
- flow/go.sum
fix - https://github.com/PeerDB-io/peerdb/issues/415
> Wait for the workflow to actually close before proceeding

- flow/connectors/postgres/cdc.go
This PR is debugging an issue where schema change propagation (#368) don't apply properly when there are parallel transactions happening during an ALTER TABLE statement. 
Borrowing from https://github.com/jackc/pglogrepl/pull/59
This PR changes the handling of clientXLogPos to match the one from Postgres' own `pg_recvlogical`:
- keepalive messages should bump the position too, as they're only sent (from what I can tell) after any xlogdata message;
- both the WALStart and the ServerWALEnd in logical xlogdata messages represent the position that should be reported back, and adding the length of the post-decoding data to it is meaningless;
- relation messages have a position of zero, and in general we should match the pg_recvlogical behavior of only increasing the local position.
> changed WAL update logic

- flow/activities/flowable.go
- flow/connectors/core.go
- flow/connectors/postgres/postgres.go
- flow/workflows/cdc_flow.go
Implemented `SendWALHeartbeat()` method to maintain PostgreSQL WAL activity.
To ensure consistent WAL activity in idle PostgreSQL databases and prevent indefinite growth of replication slots, a heartbeat mechanism is introduced. This method generates WAL activity by creating and immediately dropping an aggregate function, ensuring a guaranteed and lightweight WAL entry without leaving persistent changes in the database schema. Using an aggregate was chosen for its guaranteed WAL generation and minimal impact.
fixes: https://github.com/PeerDB-io/peerdb/issues/429
> Add SendWALHeartbeat Method

- flow/cmd/worker.go
- flow/connectors/utils/monitoring/monitoring.go
For full table partitions skip logging metrics.
> Fix an issue where we were trying to log metrics for full table

- flow/cmd/handler.go
- flow/connectors/core.go
- nexus/flow-rs/src/grpc.rs
- nexus/server/src/main.rs
For now, uses the `ValidatePeer` gRPC endpoint for SQL Server on the Rust side. Tested for all relevant peers - SQL Server, PG, SF and BQ.
Partially completes #484
> API Peer Validation for SQL Server

- flow/cmd/handler.go
- flow/connectors/snowflake/snowflake.go
- flow/workflows/qrep_flow.go
fixes: https://github.com/PeerDB-io/peerdb/issues/476
> Support `DROP MIRROR` for Query Replication

- .github/workflows/flow.yml
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/qvalue_convert.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/snowflake/qvalue_convert.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/utils/postgres.go
- flow/e2e/bigquery/qrep_flow_bq_test.go
- flow/e2e/s3/s3_helper.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
- flow/e2e/test_utils.go
- flow/model/column.go
- flow/model/conversion_avro.go
- flow/model/qvalue/avro_converter.go
- flow/model/qvalue/kind.go
- flow/workflows/cdc_flow.go
- Supports GEOGRAPHY and GEOMETRY of PostGIS from PostgreSQL to Snowflake - both CDC and QRep
- Supports Postgres' POINT data type to Snowflake
- Adds unique timestamp in prefix for S3 test
> Geospatial support for Snowflake

- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/utils/avro/avro_writer.go
- flow/go.mod
- flow/go.sum
- Introduced Zstandard (`zstd`) compression while streaming source rows, reducing post-processing time.
- Generated unique `partitionID` with a random 16-character string.
This enhancement not only bypasses Snowflake's automatic gzip compression but also ensures a more efficient data transfer by compressing data on-the-fly. `zstd` is also faster that Snowflake's default `gzip`.
See `AUTO_COMPRESS` and `SOURCE_COMPRESSION` here https://docs.snowflake.com/en/sql-reference/sql/put for more details
> Optimize Avro Streaming with `zstd` Compression for Snowflake

- flow/connectors/postgres/postgres.go
> reintroduce not erroring out when no primary keys && isFullReplica

- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_partition_test.go
- flow/e2e/congen.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
- flow/workflows/qrep_flow.go
- nexus/analyzer/src/qrep.rs
- nexus/flow-rs/src/grpc.rs
- protos/flow.proto
Only mechanism for partitioning will be `num_rows_per_partition` which is now a mandatory option. Unrecognized options in QRep mirror commands will now cause an error from the SQL interface layer.
> remove code for int,timestamp partitioning using min,max values

- nexus/analyzer/src/lib.rs
- nexus/catalog/src/lib.rs
- nexus/peer-bigquery/src/ast.rs
- nexus/peer-bigquery/src/stream.rs
- nexus/peer-postgres/src/ast.rs
- nexus/peer-snowflake/src/auth.rs
- nexus/peer-snowflake/src/lib.rs
- nexus/server/src/main.rs
Prefer `as_ref` over `clone` when possible
Prefer `eq_ignore_ascii_case` over calling `to_lowercase` before comparison
Executor: convert `Arc<Box<T>>` to `Arc<T>`
Prefer passing `&[u8]` instead of `Vec<u8>` to get_config. The postgres library is able to lend out slices from rows, avoiding a copy. Use that to avoid intermediate string before `to_lowercase` too
Found one bug: `t_lower == "Seconds"` would never be true
> Basic optimizations

- scripts/install-protobuf.sh
- stacks/peerdb-server.Dockerfile
This makes it consistent with the other docker images
Also remove wget
> peerdb-server: use Debian slim over Ubuntu

- nexus/Cargo.lock
- nexus/parser/Cargo.toml
- nexus/peer-bigquery/Cargo.toml
- nexus/peer-bigquery/src/ast.rs
- nexus/peer-cursor/Cargo.toml
- nexus/peer-postgres/Cargo.toml
- nexus/peer-snowflake/Cargo.toml
- nexus/peer-snowflake/src/ast.rs
- nexus/server/Cargo.toml
- nexus/server/src/main.rs
- nexus/value/Cargo.toml
BINARY(_, op, ANY) was changed to { left, op, right } binary op in sqlparser-rs
Cast had a format field added, ignore for now
portal.parameter had param_type added as a parameter: https://github.com/sunng87/pgwire/commit/38f361d9201a19d487dbe37a83add60d55d62ca4
Follow up to #611
> nexus: update sqlparser-rs & pgwire

- ui/app/mirrors/create/helpers/cdc.ts
- ui/app/mirrors/page.tsx
- ui/app/peers/page.tsx
- ui/lib/Dialog/Dialog.tsx
- Sets whitespace to nowrap  for create peer/mirror buttons
- Prevents drop modals from disappearing when clicking outside
- For multi-mirror shows a single flow now
- Sets snapshot parallel tables default to 4
> Minor UI Fixes

- .github/workflows/customer-docker.yml
- .github/workflows/dev-docker.yml
- .github/workflows/flow.yml
- .github/workflows/stable-docker.yml
Also update Actions setup-go & login-action
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands
> Remove use of deprecated github ci command set-output

- nexus/flow-rs/src/grpc.rs
- nexus/server/src/main.rs
While running `dev-peerdb.sh` I saw peer-server failing due to grpc connection taking too long. Replace connect_with_retries with tonic's connect_lazy
Also remove health check, if commandline includes grpc endpoint that endpoint should be used, regardless of health
The underlying principle of this PR is that grpc server should be able to come up & down as it pleases & peer-server will use it when it's up (& ideally fail loudly but non-terminally while it's down). I'm not sure this PR achieves that principle tho
> peer-server: connect lazily

- flow/connectors/snowflake/snowflake.go
> [snowflake] Run merges in parallel during normalize flow

- .github/workflows/rust-lint.yml
sqlparser-rs linting belongs at the source: https://github.com/PeerDB-io/sqlparser-rs
That way new clippy rules flagging old code in sqlparser-rs don't cause lint fails for this repo
> Disable CI linting sqlparser-rs

- ui/app/mirrors/create/schema.ts
- ui/app/mirrors/edit/[mirrorId]/aggregatedCountsByInterval.ts
- ui/app/mirrors/edit/[mirrorId]/cdc.tsx
- ui/app/mirrors/edit/[mirrorId]/cdcDetails.tsx
- ui/app/mirrors/edit/[mirrorId]/cdcGraph.tsx
- ui/app/mirrors/edit/[mirrorId]/configValues.ts
- ui/app/mirrors/edit/[mirrorId]/page.tsx
- ui/app/mirrors/edit/[mirrorId]/syncStatus.tsx
- ui/app/mirrors/edit/[mirrorId]/syncStatusTable.tsx
- ui/app/mirrors/edit/[mirrorId]/tablePairs.tsx
- ui/app/peers/[peerName]/datatables.tsx
- ui/app/peers/create/[peerType]/handlers.ts
- ui/app/peers/create/[peerType]/schema.ts
- ui/components/DropDialog.tsx
- ui/components/MirrorInfo.tsx
- ui/lib/Dialog/Dialog.tsx
- ui/lib/Dialog/DialogContent.styles.ts
Fixes #654 
Fixes #660 
Fixes #656 
- Restores tab UI for specific mirror page (`/edit/[mirrorId]`)
- Adds mirror configuration details and list of source tables to destination tables in overview tab (with search bar)
- Adds sort functionality for CDC tab and Initial load tab. In CDC you can sort by `Start Time`, `End Time` and `Rows Synced`. In Initial Load you can sort by `Start Time` and `Time per partition`.
- Timeframe options in CDC Graph now in a dropdown.
- Moves Sync History graph to Sync tab.
- Displays further mirror config via a `View More` button click which pops up a modal with the info.
- Centers the drop modal (same component as configuration modal in specific mirror page).
> Mirror Overview UI

- flow/connectors/eventhub/eventhub.go
- flow/connectors/eventhub/hub_batches.go
- Moves `SendEventBatch` to the Hub class and refactors accordingly.
- Removes `TableNameRowsMapping` with the vision of completing #677 in a future PR
> Refactors Sendeventbatch

- flow/cmd/handler.go
- flow/connectors/core.go
- flow/connectors/external_metadata/store.go
- flow/connectors/s3/s3.go
- ui/app/api/peers/route.ts
- ui/app/dto/PeersDTO.ts
- ui/app/mirrors/create/helpers/common.ts
- ui/app/mirrors/create/page.tsx
- ui/app/peers/create/[peerType]/handlers.ts
- ui/app/peers/create/[peerType]/helpers/common.ts
- ui/app/peers/create/[peerType]/helpers/s3.ts
- ui/app/peers/create/[peerType]/page.tsx
- ui/app/peers/create/[peerType]/schema.ts
- ui/components/PeerComponent.tsx
- ui/components/S3Form.tsx
- ui/components/SelectSource.tsx
- Upon choosing the GCS option, the `Region` and `Role ARN` fields will not be shown as they have fixed values for GCS
> S3 Peer UI

- flow/activities/flowable.go
- flow/workflows/cdc_flow.go
SendWalHeartbeat now runs every 10 seconds in parallel during the PeerFlow phase of CDC (after setup and snapshot)
cancelActivity is called where previously the .Get() on the activity was called in `cdc_flow.go`
> Runs SendWalHeartbeat in parallel

- flow/connectors/external_metadata/store.go
- flow/connectors/s3/s3.go
- ui/app/peers/create/[peerType]/helpers/s3.ts
- ui/app/peers/create/[peerType]/schema.ts
- ui/components/S3Form.tsx
If metadataDB is set to empty string/undefined, we now use catalog as the metadata postgres instance for S3/GCS and Eventhub CDC
> Use catalog as external store

- flow/connectors/eventhub/eventhub.go
- flow/connectors/eventhub/hub_batches.go
This is for performance, we want to keep `START_REPLICATION` connection alive for as long as we can. This was observed to reduce the latency overall significantly.
> Send the events as soon as we have hit the batch size limit

- flow/connectors/postgres/cdc.go
This was missed before, when `wal_sender_timeout` is set to a large value waiting for PKMs is a bad idea
> [cdc] Flush at the beginning of CDC until consumedXLogPos

- docker-compose-dev.yml
- docker-compose.yml
- flow/cmd/api.go
- flow/cmd/main.go
- flow/cmd/snapshot_worker.go
- flow/cmd/worker.go
Adds environment variables in docker compose for client certificate and client key to connect to Temporal Cloud server.
If a user wants to wire PeerDB with Temporal Cloud instead of local Temporal which we spin up, they need to:
1. Set `TEMPORAL_HOST_PORT` to the Temporal Cloud endpoint
2. Set the certificate and key variables
Flow worker, Flow API and Flow Snapshot Worker use these values. Mirrors run will now appear in Temporal Cloud UI
> Support Temporal Cloud

- nexus/analyzer/src/lib.rs
- nexus/catalog/src/lib.rs
- nexus/parser/src/lib.rs
- nexus/peer-bigquery/src/stream.rs
- nexus/peer-snowflake/src/lib.rs
- nexus/server/src/cursor.rs
- nexus/server/src/main.rs
- nexus/value/src/lib.rs
1. fix typo: QueryAssocation to QueryAssociation
2. remove unnecessary allocations for two-item keys_to_ignore
3. make NexusQueryParser get_peers_bridge/parse_simple_sql async; all callers are async
4. use with_capacity whenever straightforward to do so
5. change peer-snowflake SQLStatement parameters to struct since it serializes to a constant object
> nexus cleanup

- ui/app/mirrors/edit/[mirrorId]/aggregatedCountsByInterval.ts
- ui/app/mirrors/edit/[mirrorId]/cdcGraph.tsx
A proposal from my end for a more polished UI for our Sync History.
- Hovering on the bars reveals a proper tooltip box with rows synced and at what time
> New Graph UI

- docker-compose-dev.yml
- docker-compose.yml
- nexus/server/src/main.rs
Does not gracefully shutdown all sockets. To do that we'd need to store the sockets from listen to a map & shutdown. But all the programs we're interfacing with should be handling connection being dropped suddenly
Fixes #682
> peerdb-server: receive sigint & exit

- flow/connectors/eventhub/eventhub.go
If the sync flow fails this would make it so that the metadata is more up-to data. Prior to the change the metadata would only be updated once per sync flow, now this is done every 10s, so its more updated.
> [eventhubs] Update last commited LSN on metadata after we flush

- nexus/peer-bigquery/src/lib.rs
- nexus/peer-snowflake/src/auth.rs
- nexus/peer-snowflake/src/lib.rs
- nexus/server/src/main.rs
BigQueryQueryExecutor clones most of config into client, only needing 2 strings out of it afterwards
SnowflakeAuth says private_key must not be copied while the caller was calling clone to pass String
While going over String parameters to functions, noticed get_peer_of_mirror/handle_mirror_existence not needing ownership
> nexus: more cloning reduction

- ui/app/mirrors/create/cdc/cdc.tsx
- ui/app/mirrors/create/handlers.ts
- ui/app/mirrors/create/helpers/cdc.ts
- ui/app/mirrors/create/helpers/qrep.ts
- ui/app/mirrors/create/qrep/qrep.tsx
- ui/components/InfoPopover.tsx
- Since Sync Mode fields are now defaulted (see: https://github.com/PeerDB-io/peerdb/pull/707), those fields in the UI are now removed.
- Staging path fields appear depending on if the destination is AVRO type.
> Remove sync mode fields from UI

- scripts/mirror-name-search.sh
Noticed that temporal was not ready yet and so temporal-admin-tools could not list attributes
Now sleeping for 5 seconds. Tested it and now the above issue wasn't reproducible by me
Also adding `-s` to tini command as suggested by warnings
> More reliable mirror name search attribute script

- flow/cmd/handler.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/cdc.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/s3/cdc_s3_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/workflows/cdc_flow.go
- flow/workflows/sync_flow.go
Completes flow CDC tests based on rows synced instead of number of sync flows completed
> Use number of records synced as decider for CDC tests

- flow/activities/flowable.go
- flow/connectors/utils/monitoring/monitoring.go
- ui/app/mirrors/status/qrep/[mirrorId]/page.tsx
Restores metrics for XMIN mirror.
Since the first partition (first sync) of an XMIN mirror is going to have a nil range, here we make a name-sake range with end as number of records pulled and storing that in stats table.
Fixes #761
> Metrics For XMIN

- flow/activities/flowable.go
- flow/cmd/handler.go
- flow/cmd/peer_data.go
- flow/connectors/external_metadata/store.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/postgres_repl_test.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/snowflake/client.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/sql/query_executor.go
- flow/connectors/sqlserver/qrep.go
- flow/connectors/utils/postgres.go
- flow/e2e/congen.go
- flow/e2e/sqlserver/qrep_flow_sqlserver_test.go
Also set connection pool limit to 3 for our postgres client
> Default types replaced with pgtype wherever possible

- ui/app/mirrors/create/cdc/schemabox.tsx
- ui/app/mirrors/create/cdc/tablemapping.tsx
For list of components whose ordering or cardinality can change, using the array index as the key attribute isn't ideal. This PR uses a unique component-based key instead such as row.id or row.name in those cases
> UI: No index as key

- .github/workflows/flow.yml
- flow/activities/flowable.go
- flow/cmd/api.go
- flow/cmd/handler.go
- flow/cmd/worker.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/external_metadata/store.go
- flow/connectors/postgres/postgres.go
- flow/connectors/utils/catalog/env.go
- flow/connectors/utils/monitoring/monitoring.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/bigquery/qrep_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/s3/cdc_s3_test.go
- flow/e2e/s3/qrep_flow_s3_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
- flow/e2e/sqlserver/qrep_flow_sqlserver_test.go
- flow/e2e/test_utils.go
Connection pools are meant to be shared, so remove pool from monitoring
Also go one step further: cache connection pool from env.go into global This requires never closing pool returned by GetCatalogConnectionPoolFromEnv
Run migrations for CI because `monitoring` logic is now non optional
Opens up reusing pool for #778
> Avoid having multiple catalog connection pools

- flow/activities/flowable.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/postgres.go
- flow/connectors/s3/s3.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/utils/monitoring/monitoring.go
- flow/model/model.go
This value is not currently being computed consistently, to be correct it should be taking the minimum checkpoint id, not the first
Ultimately it only serves for being written to monitoring, so remove it
> Remove FirstCheckpointID

- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/qvalue_convert.go
- flow/connectors/utils/cdc_records/cdc_records_storage_test.go
- flow/model/conversion_avro.go
- flow/model/model.go
- flow/model/qrecord.go
- flow/model/qvalue/avro_converter.go
- flow/model/qvalue/kind.go
- flow/model/qvalue/qvalue.go
QValue is a string/interface{} pair
string is a pointer/int pair
interface{} is a pointer/pointer pair
Copying four words is cheap, especially when for the most part qvalues are stored in a QRecord which will itself be passed around by pointer
Include a `QValueKindEmpty` which is used in places where previously pointer would be nil
> qvalue: pass by value

- flow/connectors/bigquery/merge_statement_generator.go
- flow/connectors/postgres/qrep_partition_test.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/qrep_sync_method.go
- flow/connectors/snowflake/client.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/utils/cdc_records/cdc_records_storage.go
- flow/e2e/bigquery/bigquery_helper.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/snowflake_helper.go
- flow/e2e/sqlserver/sqlserver_helper.go
- flow/shared/crypto.go
- flow/shared/random.go
Resolves util/utils ambiguity with flow/connectors/utils
> Merge flow/utils into flow/shared

- flow/activities/flowable.go
- flow/connectors/core.go
- flow/connectors/postgres/postgres.go
- flow/shared/constants.go
Pass catalog connection as parameter instead
> Remove shared.CDCMirrorMonitorKey

- flow/connectors/postgres/client.go
- flow/connectors/snowflake/snowflake.go
Use QueryRow instead of Query,
& introduce a Tx variant which can reuse existing connection
> Refactor jobMetadataExists in postgres/snowflake connectors

- flow/cmd/worker.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/merge_statement_generator.go
- flow/connectors/postgres/cdc.go
1) Replaces the legacy `JSON_EXTRACT_*` functions with `JSON_VALUE_*` equivalents which fixes quoting issues in certain types.
2) Changes some logging and Pyroscope to be less noisy.
> fixes merge statement casting for JSONB and array types

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/qrecord_value_saver.go
- flow/connectors/postgres/client.go
- flow/generated/protos/flow.pb.go
- flow/model/qvalue/kind.go
- nexus/pt/src/peerdb_flow.rs
- protos/flow.proto
- ui/grpc_generated/flow.ts
Change qvalue.QValueKindIsArray to IsArray method using HasPrefix,
update code calling `Contains(type, "array")` to use method
> Prefer `HasPrefix(type, "array_")` to `Contains(type, "array")`

- nexus/catalog/src/lib.rs
- nexus/postgres-connection/src/lib.rs
- nexus/server/src/main.rs
Previously this was blocking accepting next connection
Benchmark:
```
pids=()
for i in {1..100}
do psql "host=localhost port=9900 password=asdf" 2> /dev/null&
pids+=($!)
done
for pid in ${pids[@]}
do wait $pid
```
Before:
```
real	0m0.739s
user	0m0.325s
sys	0m0.268s
```
After:
```
real    0m0.130s
user    0m0.300s
sys     0m0.295s
```
> nexus: move most connection setup into connection handling task

- flow/go.mod
- flow/go.sum
- flow/workflows/cdc_flow.go
multierror struct has a formatting closure, making it unserializable Thus, multierror cannot be stored in temporal state
Replace with `[]string`
> Remove multierror to fix error in error handling

- ui/app/peers/page.tsx
Convert /peers page to client components, so that we dont have to do a round trip on every page visit. Converting it to client side rendering, caches the page once it is loaded and we can load data via api. When data is loading we show the loader. We also cache the data(via swr) and refresh the data in background.
> Improve loading: peers page

- flow/connectors/bigquery/bigquery.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/snowflake/avro_file_writer_test.go
- flow/connectors/sql/query_executor.go
- flow/connectors/utils/avro/avro_writer.go
- flow/connectors/utils/stream.go
- flow/e2e/bigquery/bigquery_helper.go
- flow/model/conversion_avro.go
- flow/model/qrecord.go
- flow/model/qrecord_batch.go
- flow/model/qrecord_stream.go
- flow/model/qrecord_test.go
A QRecord is 3 integers & a pointer,
mostly held in slices for QRecordBatch
> Pass QRecord around by value

- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- nexus/catalog/migrations/V15__schema_deltas_audit_log.sql
Currently stores the following info:
```
CREATE TABLE IF NOT EXISTS peerdb_stats.schema_deltas_audit_log (
id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
flow_job_name TEXT NOT NULL,
read_timestamp TIMESTAMP DEFAULT now(),
workflow_id TEXT NOT NULL,
run_id TEXT NOT NULL,
delta_info JSONB NOT NULL
);
```
delta_info is the marshaled version of the `RelationRecord`. Store happens in the same function where `RelationMessages` are processed.
> logs schema deltas to catalog as soon as they are read

- ui/app/api/mirrors/route.ts
- ui/app/mirrors/page.tsx
The mirror fetch API was sending data in the wrong format, causing the mirrors page to crash when qrep mirrors exist. This PR restores functionality of the mirrors page
> UI: Better mirror fetching

- nexus/Cargo.lock
- nexus/peer-snowflake/Cargo.toml
- nexus/peer-snowflake/src/auth.rs
Made while attempting to remove pkcs1 to get around https://people.redhat.com/~hkario/marvin
Unfortunately this'll require changing keys. So I'll look to implement support for pkcs8 encoded keys too so pkcs1 can be avoided
> Remove direct dependency on pkcs1/pkcs8

- flow/cmd/handler.go
- flow/connectors/bigquery/qrep.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_sync_method.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/bigquery/qrep_flow_bq_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/s3/qrep_flow_s3_test.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
- flow/e2e/snowflake/snowflake_helper.go
- flow/e2e/test_utils.go
- flow/workflows/qrep_flow.go
- flow/workflows/snapshot_flow.go
Implements `_PEERDB_SYNCED_AT` for Query Replication mirrors for PG -> [PG, BQ, SF]
> SyncedAt Column for QRep

- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/e2e/snowflake/peer_flow_sf_test.go
This is to support `USING INDEX` replica identity types in Postgres. Treating the index columns as primary key columns for now as it is the fastest way for us to support replica identity index.
> Refactor replica identity type and primary key column retrieval in Postgres

- flow/connectors/postgres/client.go
I tried PeerDB on Read Replicas in PG 16:
1. Initial Load worked as expected
2. SyncFlows were erroring out:
```
ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
```
The reason was `pg_current_wal_lsn()` cannot be run on a standby. I changed that function to `pg_last_wal_replay_lsn()` if Replica.
> Replication should now work from PG 16 Standbys

- flow/connectors/bigquery/merge_statement_generator.go
- flow/connectors/bigquery/merge_stmt_generator_test.go
- flow/connectors/postgres/client.go
- flow/connectors/snowflake/snowflake.go
Fixes the update statements we generate during normalize merge for bigquery and postgres. Also adds comments for SF,PG and BQ for generating update statements
> Soft Delete: Patch update statements

- flow/connectors/core.go
- flow/connectors/postgres/postgres.go
Since this is done on the activity level now for all Postgres peers
> remove SendWALHeartbeat from the CDCPullConnector interface

- flow/activities/flowable.go
- flow/cmd/version.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/utils/catalog/env.go
- flow/connectors/utils/cdc_records/cdc_records_storage.go
- flow/model/model.go
- flow/peerdbenv/config.go
- flow/shared/alerting/alerting.go
- flow/shared/constants.go
the Go convention is not to have `Get` in the function name, `GetPeer` vs `Peer`.
Can be changed in other places on a case by case basis.
> changing naming convention for getters in peerdbenv

- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/snowflake/snowflake.go
> making all Snowflake DB access use a context

- flow/cmd/worker.go
- flow/e2e/test_utils.go
- flow/shared/alerting/alerting.go
This makes the alerter log to catalog whether slack based alerting is setup or not. Also fixes usage of Context in the alerting class.
> Make alerter independent of slack

- .github/workflows/flow.yml
- flow/activities/flowable.go
- flow/connectors/bigquery/bigquery.go
- flow/e2e/congen.go
- flow/workflows/normalize_flow.go
- flow/workflows/sync_flow.go
> Split normalize flow logic out of sync_flow.go

- dev-peerdb.sh
- docker-compose-dev.yml
- docker-compose.yml
podman complains if multiple arguments are passed to `CMD-SHELL`. Turns out we don't need it. podman doesn't support `--no-attach`. Otherwise everything works. Adjust `dev-peerdb.sh` to support podman-compose fallback or being invoked with `USE_PODMAN=1 ./dev-peerdb.sh`
> be compatible with podman-compose

- flow/connectors/postgres/cdc.go
This could potentially cause the WAL to build up but based on reports in the field this seems like the safer alternative for now.
> Never update consumed xlogpos even when num records is zero

- ui/app/api/mirrors/alerts/route.ts
- ui/app/mirrors/edit/[mirrorId]/cdcDetails.tsx
- ui/app/mirrors/errors/[mirrorName]/ackbutton.tsx
- ui/app/mirrors/errors/[mirrorName]/page.tsx
- ui/app/mirrors/mirror-status.tsx
- ui/app/mirrors/tables.tsx
Users can now mark errors as 'Acknowledged'. If there are no unacknowledged errors for a mirror, it's status is said to be 'Active'
Users can click on the status and be taken to the page above.
- Loading indicator for acknowledge button
- Error toast incase acknowledge operation fails
> Errors UI: Acknowledge functionality

- flow/activities/flowable.go
A few places we were logging peer names instead of flow name for the `peerdb_stats.flow_errors` table. Also some long lines have been split in this PR
> Fix flow err log and cleanup flowable.go

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/merge_statement_generator.go
- flow/connectors/bigquery/qrep.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/cdc.go
- flow/e2e/bigquery/bigquery_helper.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/model/model.go
1) Just like Snowflake and Postgres, now BigQuery takes tables in the form of `<dataset>.<table>`. If dataset is omitted then it defaults to using the dataset specified at the time of peer creation.
2) If the dataset doesn't exist at the time of mirror creation, it is created during `SetupNormalizedTables` before the tables in the dataset.
3) A check has also been added so that two source tables cannot point to the same destination table specified in 2 different formats.
> added capability for BQ CDC across datasets

- flow/connectors/external_metadata/store.go
- flow/go.mod
- flow/go.sum
- flow/workflows/setup_flow.go
https://stackoverflow.com/questions/29900845/create-schema-if-not-exists-raises-duplicate-key-error
Ran into this while looking to make all tests run in parallel
> Ignore unique constraint violation during CREATE IF NOT EXISTS

- flow/connectors/snowflake/client.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/utils/identifiers.go
- flow/connectors/utils/postgres.go
> replacing SF tableNameComponents with PG's version

- flow/connectors/bigquery/bigquery.go
Ran into an issue where in syncRecordsViaAvro we are creating a stream with size 1 >> 20. 
For pulled records of a number higher than this, the loop just blocks with no logs
> Increase bq avro stream size to 10 mil

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/merge_statement_generator.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/utils/stream.go
Fixes a bug in BigQuery CDC where a batch with number of records greater than `2 ** 20` causes the Avro file generation part to hang. This is because all records were being written to a bounded channel first and then consumed by the Avro writer instead of the 2 operations happening in parallel. With a large number of records, the channel would fill up and block before the records finished writing, leading to the loop deadlocking itself.
Fixed by switching BigQuery record generation to the mechanism used by Snowflake, where the record generation happens in another goroutine and therefore the channel consumption happens in parallel. As part of this change, some code was cleaned up and the BigQuery raw table schema was changed in a breaking manner to be similar to the SF/PG equivalent. …
> [breaking] BQ SyncRecords now streams properly, code cleanup

- docker-compose-dev.yml
- docker-compose.yml
- ui/app/api/version/route.ts
- ui/app/dto/VersionDTO.ts
- ui/components/SidebarComponent.tsx
Docker compose changes:
Figured it would be good to have ui start after the flow-api container
> Show version, make ui dependent on api in docker

- flow/connectors/bigquery/bigquery.go
Setup clustering for pkey for normalized table, we noticed at one of our customers that the costs associated with MERGE statements are high. This is an attempt to reduce them per: https://cloud.google.com/blog/products/data-analytics/cost-optimization-best-practices-for-bigquery
> Setup partitioning and clustering for raw table

- ui/app/mirrors/create/cdc/fields.tsx
- ui/app/mirrors/create/helpers/cdc.ts
- ui/app/mirrors/create/helpers/common.ts
- ui/app/mirrors/create/qrep/qrep.tsx
- ui/app/mirrors/edit/[mirrorId]/cdc.tsx
- ui/app/mirrors/tables.tsx
- ui/components/MirrorLink.tsx
- Clicking on the mirror name links in the mirror tables in the mirror page sometimes has a small delay so this PR displays a loader there.
- Sets default snapshot setting to true
- Restores tab persistence on refresh functionality in specific mirror page
> Restore tabs, set default to true for snapshot, link loader

- flow/activities/flowable.go
- flow/activities/snapshot_activity.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/slot_signal.go
- flow/model/model.go
- flow/workflows/cdc_flow.go
Channels & maps are internally pointers,
so behave as if passed by reference already
This concludes reviewing `chan *`, as it turns out there are no large objects which get sent over channels in our codebase
> Use more values by value

- .github/workflows/ci.yml
- .github/workflows/dev-docker.yml
- .github/workflows/flow.yml
This shaves almost a minute off flow ci, & I expect that'll improve as rest of test suite parallelizes
> Experiment: run flow ci with 16 cores

- flow/activities/flowable.go
- flow/connectors/postgres/cdc.go
[Debezium](https://github.com/debezium/debezium/blob/db0cfea550308e7386413db25115d531a4c0a61c/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java#L584) also does something similar. Awaiting confirmation from Postgres experts on this but so far what we have seen from the field indicates that this error is OK.
This PR also does some minor refactors and cleaning up of error messages that looked very similar.
> Retry when WAL segment has not been found

- flow/e2e/sqlserver/qrep_flow_sqlserver_test.go
> sqlserver: port away from testify/suite

- flow/connectors/external_metadata/store.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/connectors/utils/postgres.go
Followup from #905 now that I've seen parallel testing of pg connector (#941) running into this
> postgres connector: ignore unique constraint violations from IF NOT EXISTS

- flow/connectors/external_metadata/store.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep.go
When a command errors during a transaction the transaction can no longer progress, it must be rolled back. This is the case when IF NOT EXISTS errors over unique violation
We do not need schema/table creation to be transactional, so remove transaction
Corrects #942 & #905 to be effective
> Don't create metadata schema in a transaction

- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/sql/query_executor.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
Similar to how #830 fixes JSON structure for BigQuery, this one does it for Snowflake by performing a [PARSE_JSON transformation](https://docs.snowflake.com/en/sql-reference/functions/parse_json) in Copy (for initial load) and Merge (CDC) steps
You can now query synced Postgres JSONs by PeerDB to Snowflake Variants using:
```sql
SELECT j:tags FROM mysftable
``` 
Adds a test for this. Also tested manually
Fixes #828
> SF JSON (Variant): Remove escaped quotes

- flow/activities/flowable.go
- flow/peerdbenv/config.go
- flow/shared/constants.go
- flow/workflows/cdc_flow.go
- protos/flow.proto
- ui/app/mirrors/create/helpers/cdc.ts
- ui/app/mirrors/create/helpers/common.ts
- Refactors our signal receptor in CDC to take in a struct of two values - `BatchSize` and `IdleTimeout`.
You can send a signal by going to peerflow in Temporal UI, clicking on the down-arrow in the Request Cancellation button on the right, click on `Send Signal`, and then enter like this:
You can set one of the two at a time as well.
Note that the name of the signal must be  `cdc-dynamic-properties`
- Adds Idle Timeout to UI and an info tip with explanation and link to https://docs.peerdb.io/metrics/important_cdc_configs
> Adds idletimeout to flow config, ui and temporal signal

- flow/workflows/qrep_flow.go
In `waitForNewRows` in our QRep logic, we blindly set activity timeout to 5 minutes, when actually it is very much dependent on what the user set as `waitBetweenBatches`.
This PR sets the activity timeout based on the waitBetweenBatches value
> Set proper waitForBatches activity timeout 

- flow/cmd/peer_data.go
- flow/connectors/core.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/postgres_repl_test.go
- flow/connectors/postgres/postgres_schema_delta_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
Alternative to #872
Allows #945 to test replPool code path without losing testing of codepaths without replPool
> PostgresConnector replPool: initialize lazily

- flow/connectors/eventhub/scoped_eventhub.go
If you want to have an eventhub name with a hyphen when creating a PG -> EH mirror via SQL Layer:
```sql
CREATE MIRROR pgeh_mirror
FROM pg_peer TO eventhub_group_peer_1
WITH TABLE MAPPING (
public.oss1:ehpeer1."oss1-eventhub".oss1
)
```
> EventHub:: Handle quoted eventhub name

- ui/app/mirrors/create/helpers/cdc.ts
- ui/app/mirrors/create/helpers/common.ts
- ui/app/mirrors/create/helpers/qrep.ts
Some defaults in the UI were not displayed correctly. This PR fixes that
> UI: Fixes default for some params

- flow/connectors/postgres/postgres_schema_delta_test.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/bigquery/qrep_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/s3/cdc_s3_test.go
- flow/e2e/s3/qrep_flow_s3_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
- flow/e2e/snowflake/snowflake_schema_delta_test.go
- flow/e2e/sqlserver/qrep_flow_sqlserver_test.go
- flow/e2eshared/e2eshared.go
got.G only introduces methods which align to testify/assert rather than testify/require
> Remove use of got.G

- flow/connectors/bigquery/merge_statement_generator.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/bigquery/qvalue_convert.go
- flow/connectors/postgres/qvalue_convert.go
- flow/e2e/bigquery/bigquery_helper.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/bigquery/qrep_flow_bq_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/test_utils.go
Similar to #516 
Leverages https://cloud.google.com/bigquery/docs/geospatial-data to implement syncing of Postgres' POSTGIS types to BigQuery's GEOGRAPHY data type - for both QRep, Initial Load and CDC.
In `qrep_avro_sync`, we now have a function where we can perform transformations of the data on staging table before copying to destination - a feature which was needed here, and makes it easier to support datatypes in QRep for BQ
Tests added for QRep and CDC
> Geospatial Support for BigQuery

- flow/connectors/bigquery/merge_statement_generator.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/bigquery/qvalue_convert.go
- flow/e2e/bigquery/peer_flow_bq_test.go
Before we were creating the destination table (SetupNormalize) with the JSON column as STRING. Now it is truly JSON at the BigQuery destination
> Better JSON datatype handling in BQ

- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/shared/alerting/alerting.go
1. Retrieve syncBatchID and normalizeBatchID in one statement, like SF and BQ
2. Iterate over distinctTableNames instead of unchangedToastCols for generating merge statements, since sometimes tables that needed merge statements were getting skipped.
3. Fixed couple of bugs for soft delete handling in PG merge statements
4. added PG tests for soft delete
> misc fixes and improvements for PG, along with softdel tests

- flow/workflows/snapshot_flow.go
This lays the ground work for cases where we want a consistent view without creating a slot by exposing a transaction snapshot
> Refactor snapshot flow for slot based snapshotting

- flow/cmd/handler.go
- flow/cmd/mirror_status.go
- flow/connectors/postgres/postgres.go
- flow/e2e/test_utils.go
- flow/shared/constants.go
- flow/workflows/cdc_flow.go
- flow/workflows/qrep_flow.go
- nexus/flow-rs/src/grpc.rs
- nexus/server/src/main.rs
- protos/flow.proto
- protos/route.proto
- temporal-dynamicconfig/development-sql.yaml
breaks some protos and routes for clearer naming conventions, UI needs to be updated accordingly
removes SetupComplete and SnapshotComplete booleans in CDCFlowState in favour of a CurrentFlowState that expresses all states of a CDC workflow in a single variable.
rebase of PR: https://github.com/PeerDB-io/peerdb/pull/657
> adding visibility into current mirror state

- .github/workflows/golang-lint.yml
- flow/e2e/test_utils.go
- flow/geo/geo.go
We were never actually checking the geo column values in snowflake qrep. This PR aims to fix that and also a lint
Fixes #973
> Fix snowflake qrep tests: geography validation

- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/qvalue_convert.go
- flow/e2e/bigquery/qrep_flow_bq_test.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
- flow/e2e/test_utils.go
- flow/e2eshared/e2eshared.go
- flow/geo/geo.go
- flow/model/qvalue/qvalue.go
I introduced regression in #923
Function was returning bool while callers expect testify/require semantics
> Fix e2e.RequireEqualRecordBatches

- flow/activities/flowable.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/s3/cdc_s3_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/test_utils.go
https://pkg.go.dev/testing#T.FailNow
> FailNow must be called from the goroutine running the test or benchmark function,
> not from other goroutines created during the test
This would cause workflow to hang if it was waiting on goroutine, so introduce helper functions which:
1. Check assertion
2. Log failure & mark test failed
3. Cancel workflow
4. Abort goroutine
A followup PR will fix calls to compareTableContents
> tests: avoid require in non-initial go routines

- flow/connectors/postgres/postgres_schema_delta_test.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/s3/qrep_flow_s3_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/snowflake_schema_delta_test.go
- flow/e2e/sqlserver/qrep_flow_sqlserver_test.go
- flow/e2eshared/e2eshared.go
- flow/go.mod
- flow/go.sum
got.Each calls all public methods, which was complicating making a Teardown method
I'm also looking to implement other interfaces to share code between packages,
which is complicated by got
> Remove got

- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/bigquery/qrep_flow_bq_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
- flow/e2e/test_utils.go
- flow/e2eshared/e2eshared.go
Split the two use cases into two functions,
e2e.RequireEqualTables & e2e.EnvEqualTables
Which uses interfaces to share code between
Followup for #977
> Fix compareTableContents use for goroutines

- flow/connectors/bigquery/qrep_avro_sync.go
- flow/e2e/test_utils.go
> Add test for Date in QRep

- nexus/analyzer/src/lib.rs
- nexus/flow-rs/src/grpc.rs
We already use catalog in cases where this isn't passed, but validation failed for eventhub group peer.
> Remove the need for metadata db in eventhub group peer

- nexus/analyzer/src/lib.rs
- nexus/analyzer/src/qrep.rs
Small refactoring noticed while reviewing #983
> parse_db_options: avoid string copy for integer options

- nexus/analyzer/src/lib.rs
- nexus/catalog/src/lib.rs
- protos/peers.proto
- ui/components/PeerTypeComponent.tsx
add protos as a first step for clickhouse connectors
> Clickhouse add protos

- ui/app/mirrors/create/mirrorcards.tsx
Create Mirror cards had Learn More link all pointing to the same page
> Remove hardcoded link

- flow/connectors/utils/heartbeat.go
- flow/model/model.go
- flow/model/qrecord_stream.go
Makes it clearer how a channel is intended to be used,
& is an extra layer of static type checking
Also have `HeartbeatRoutine` stop when `ctx.Done()`
> flow: specify when channel is read-only or write-only

- flow/connectors/bigquery/merge_statement_generator.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/test_utils.go
In BigQuery: currently our JSON handling fails for JSONs with long double values:
```
Input number cannot round-trip through string representation
```
The fix is presented [here](https://issuetracker.google.com/issues/231030459#comment17)
> BQ: Add wide_number_mode to PARSE_JSON

- flow/cmd/mirror_status.go
We would iterate through each partition in the qrep flow and make a query and then render the mirror status page. This reduces all of them to just one query.
> Make mirror status query not proportional to number of partitions

- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/bigquery/qrep_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/s3/cdc_s3_test.go
- flow/e2e/s3/qrep_flow_s3_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
No tests currently use workflow assertions,
their purpose is for mocking, which is not what e2e is doing,
& is something I'm moving us further away from with #980
> e2e: Remove AssertExpectations

- flow/activities/flowable.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/utils/avro/avro_writer.go
- flow/connectors/utils/heartbeat.go
`context.WithCancel` is a bit hairy in its implementation since internally they use a lazily allocated `chan struct{}` themselves, but seems idiomatic to use it
HeartbeatRoutine could keep creating its own `chan struct{}` & instead `return func() { shutdown <- struct{}{} }` to keep the same API
> HeartbeatRoutine: return context.CancelFunc instead of chan struct{}

- flow/connectors/utils/map.go
This could and has led to issues where the same set of unchanged toast columns could lead to different values being set for `_peerdb_unchanged_toast_columns` in the raw table, causing extra update statements to be generated.
> make KeysToString sort array since maps.Keys is non-deterministic

- flow/connectors/bigquery/merge_statement_generator.go
- flow/connectors/bigquery/merge_stmt_generator_test.go
This is part of a series of PRs to address the size of our BigQuery merge statements. The maximum supported size for a single BQ query is 1MB and really wide tables with a lot of TOAST columns can cause our merge statement generator to generate queries that BigQuery cannot execute.
For this PR:
1) Remove unnecessary whitespace in merge statements.
2) Change our CTEs to use shorter aliases, _peerdb_deduped -> _d etc.
3) Alias some of our frequently used raw table columns: _peerdb_unchanged_toast_columns -> _ut.
> made CTEs and some columns use alias, eliminate whitespace

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/merge_statement_generator.go
- flow/connectors/bigquery/merge_stmt_generator_test.go
Introduces a map - `shortColumn` in the mergeGenerator struct to map column names to shorter _c1, _c2 etc.
> Alias deduped cols to be shorter

- flow/model/model.go
> Handle NaNs for Floats and Float Arrays

- flow/connectors/bigquery/merge_statement_generator.go
- flow/e2e/bigquery/bigquery_helper.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/model/model.go
json.Marshall does not support NaN , so we have to nullfy them, but:
NULLs are aren't allowed when inserting arrays in bigquery. 
So in the Merge statement we skip nulls
Fixes #1029
> BQ: Handle NaN in Merge

- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/test_utils.go
Tests were flaking because enum tests were trying to create the mood enum in parallel.
Unfortunately, `CREATE TYPE IF NOT EXISTS` is not a thing, and doing `DROP TYPE IF EXISTS` before every enum creation can be flaky. 
Solution is to just ignore the specific unique typename constraint violation
> enum tests: ignore type unique violation

- flow/cmd/mirror_status.go
- ui/app/api/alert-config/route.ts
- ui/app/api/mirrors/alerts/route.ts
- ui/app/mirrors/edit/[mirrorId]/page.tsx
- ui/app/mirrors/page.tsx
- ui/app/mirrors/status/qrep/[mirrorId]/page.tsx
- ui/app/mirrors/status/qrep/[mirrorId]/qrepConfigViewer.tsx
- ui/app/peers/[peerName]/page.tsx
Remove force-dynamic in the UI mirrors status file
> UI: Remove force-dynamic

- nexus/peer-bigquery/src/cursor.rs
- nexus/peer-cursor/src/lib.rs
- nexus/peer-snowflake/src/cursor.rs
Cursor is mutable so type system already knows it has exclusive access
> SendableStream: remove mutex, require sync

- nexus/parser/src/lib.rs
- nexus/server/src/main.rs
Catalog's methods already handle synchronization,
besides when running migrations, which already uses exclusive connections
Also query source/destination peer in parallel
> nexus: don't wrap Catalog in Mutex

- flow/workflows/qrep_flow.go
- flow/workflows/xmin_flow.go
Realised we can just create a qrep execution object for many of the activities we're calling in xmin_flow.go
Fixes a typo in qrep_flow
Adds temporal query handlers in xmin_flow.go (same ones as in qrep_flow - these have been refactored to a common function). Without these, XMIN mirror statuses cannot be viewed in UI
> Clean xmin flow, add query handlers, fix typo

- flow/cmd/mirror_status.go
- ui/app/mirrors/edit/[mirrorId]/page.tsx
Refactors our initial load status fetch to now perform a join instead of iterating through flow names and running `len(clones)` number of queries. 
Uses `{cache : 'no-store'}` as an alternative to forcing dynamic rendering. This is the more idiomatic way of using NextJS and force-dynamic is just for cases where easier migration from the earlier getServerSideProps of page router is the need
> UI: Refactor api and control cache frontend

- flow/cmd/mirror_status.go
- ui/app/mirrors/edit/[mirrorId]/page.tsx
Refactors our initial load status fetch to now perform a join instead of iterating through flow names and running `len(clones)` number of queries.
Uses `{cache : 'no-store'}` as an alternative to forcing dynamic rendering. This is the more idiomatic way of using NextJS and force-dynamic is just for cases where easier migration from the earlier getServerSideProps of page router is the need
> UI: Refactor api and control cache frontend (#1042)

- flow/connectors/utils/avro/avro_writer.go
- flow/go.mod
go 1.19 introduced atomic types similar to uber
> Replace go.uber.org/atomic with sync/atomic

- flow/cmd/peer_data.go
- protos/route.proto
- ui/app/api/alert-config/route.ts
- ui/app/api/peers/tables/all/route.ts
- ui/app/dto/MirrorsDTO.ts
- ui/app/dto/PeersDTO.ts
- ui/app/mirrors/create/cdc/schemabox.tsx
- ui/app/mirrors/create/cdc/styles.ts
- ui/app/mirrors/create/handlers.ts
If a table does not have primary key nor is it a replica identity, it is now not selectable in Create CDC UI.
> UI: Blur table if not mirror-able

- flow/connectors/eventhub/eventhub.go
We weren't returning the current sync batch ID as part of eventhub's SyncRecords. As a result, we weren't able to get CDC logs for Eventhub. This PR fixes that
> Eventhub: Fix rows synced log

- flow/connectors/eventhub/eventhub.go
- nexus/analyzer/src/lib.rs
Removes metadatadb requirement for Eventhub Group peer as it can use catalog on its own
Fixes a few logs
> Eventhub: fix logs and metadatadb requirement

- ui/app/mirrors/create/handlers.ts
- ui/app/mirrors/create/page.tsx
- ui/app/mirrors/errors/[mirrorName]/page.tsx
- ui/app/peers/[peerName]/page.tsx
- ui/app/peers/create/[peerType]/handlers.ts
Refreshing in the slot page was not updating the slot table data since we aren't disabling caching there like we are in the mirrors edit page. Same goes for mirror errors page. Also just adds `cache:no-store` in a few other fetches for safety
> UI: Fix caching

- flow/connectors/eventhub/eventhub.go
- flow/connectors/eventhub/hub_batches.go
- Remove push parallelism
- Move heartbeat routine inside processBatch
- use atomic int for num records
> Eventhub: remove parallelism, move recordheartbeat, use atomic

- flow/e2e/postgres/qrep_flow_pg_test.go
https://pkg.go.dev/github.com/jackc/pgx/v5#QueryExecMode
> compareTables test: drop loop by not using prepared statements for query

- flow/activities/snapshot_activity.go
- flow/connectors/postgres/slot_signal.go
- flow/connectors/utils/heartbeat.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
Closing allows for multiple receivers & never blocks sender
It's the correct choice when one wants to signal an irreversible state change
> Prefer to close completion channels instead of <-struct{}{}

- flow/activities/flowable.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/core.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/postgres.go
- flow/connectors/s3/s3.go
- flow/connectors/snowflake/snowflake.go
- flow/model/model.go
- flow/workflows/sync_flow.go
- protos/flow.proto
A sync batch should not be considered complete until its schema changes are processed,
this avoids failures after commit causing schema changes to be dropped,
& when decoupling normalize/sync in #893 was causing normalization to be missing values
> Move ReplayTableSchemaDeltas into SyncRecords

- flow/e2e/bigquery/peer_flow_bq_test.go
Seems like `peer_flow_bq_test.go` was missing the sync import
> Import sync in bq test file

- flow/connectors/eventhub/eventhub.go
- flow/connectors/utils/partition_hash.go
- ui/app/mirrors/edit/[mirrorId]/aggregatedCountsByInterval.ts
- ui/app/mirrors/edit/[mirrorId]/cdc.tsx
- ui/app/mirrors/edit/[mirrorId]/cdcGraph.tsx
We now hash the partition key column value obtained from the destination table name in create mirror for PG->EH.
This is to reduce the number of Eventhub batches we create. Noticed that not doing so makes the mirror extremely slow
Also fixes some code of the UI Graph component
> Fix Eventhub Partition Key and UI Graph

- flow/connectors/bigquery/avro_transform_test.go
- flow/connectors/bigquery/merge_stmt_generator.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/bigquery/qvalue_convert.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/qvalue_convert.go
- flow/connectors/sql/query_executor.go
- flow/e2e/bigquery/bigquery_helper.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/test_utils.go
- flow/model/model.go
- flow/model/qrecord_batch.go
- flow/model/qvalue/avro_converter.go
- flow/model/qvalue/kind.go
- flow/model/qvalue/qvalue.go
This PR adds support for the following types across PG, SF and BQ:
- Array of Boolean
- Array of Date
- Array of Timestamp(/TZ)
- Array of Int16 (smallint)
- CIDR
- MacAddr
- INET
The latter 3 is more relevant for Postgres.
This PR achieves the correct AVRO type mapping for Date in BigQuery - eliminating the hack which was being done in merge transforms. 
This PR also writes date and time values as human readable text for BQ QRep
Tests added as well
Fixes #666 
Fixes #20
> Support more data types

- flow/connectors/utils/postgres.go
Currently fails in initial load with something like `failed to begin transaction: no rows in result set`
> RegisterHStore shouldn't fail when hstore isn't present

- ui/app/mirrors/create/mirrorcards.tsx
Quick fix to fix the overflowing text problem. On smaller screens now the cards would be of different size but will not overflow
Before
After
> fix mirror ui

- flow/connectors/snowflake/avro_transform_test.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/qrep_avro_consolidate.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/snowflake/snowflake.go
Quite a bit of reorganization, moved functions from connector level to `ConsolidateHandler` level, reading from struct instead of unnecessary var passing
> split and tidy up code for SF Avro consolidate

- flow/activities/flowable.go
- flow/cmd/handler.go
- flow/cmd/validate_mirror.go
- flow/cmd/validate_peer.go
- flow/connectors/postgres/client.go
- protos/route.proto
- ui/app/api/mirrors/cdc/route.ts
- ui/app/api/mirrors/cdc/validate/route.ts
- ui/app/dto/MirrorsDTO.ts
- ui/app/mirrors/create/cdc/cdc.tsx
- ui/app/mirrors/create/cdc/fields.tsx
- ui/app/mirrors/create/cdc/guide.tsx
- ui/app/mirrors/create/cdc/tablemapping.tsx
- ui/app/mirrors/create/handlers.ts
- ui/app/mirrors/create/helpers/cdc.ts
- ui/app/mirrors/create/page.tsx
- ui/app/mirrors/create/schema.ts
- ui/app/mirrors/create/styles.tsx
- ui/app/peers/create/[peerType]/page.tsx
This PR adds a Validate mirror button and corresponding logic to check if the postgres source peer and selected tables are ready to be mirrored. Moves validate peer logic to separate file
This PR covers:
- Check if replication permissions are there for user
- Check if we can do SELECT * FROM TABLE LIMIT 0. for all selected tables.
- If initial copy is selected, they can’t enter the replication slot.
- Check if publication they provide, is attached to all selected tables.
- If no tables show up, remind them check GRANT permissions.
- Validate peer: Don’t let you create < 12 version
- Link to docs in CREATE PEER page.
> Validate Mirror: PostgreSQL Checks

- flow/connectors/postgres/client.go
- ui/app/mirrors/edit/[mirrorId]/cdcDetails.tsx
In RDS, you cannot add `rolreplication` to a user. Instead, RDS accepts `rds.logical_replication` :
```sql
grant rds_replication to postgres
```
This PR modifies validate mirror to allow for this
> Add check for rds replication

- nexus/peer-bigquery/src/lib.rs
We close the tracker after getting the result set but if we error while obtaining the result set, the token wouldn't get closed. This PR fixes that.
> Nexus bq: refactor run tracked

- flow/cmd/validate_peer.go
Return error on invalid PG version instead of a valid one
> Validate Peer: Fix check condition

- flow/connectors/postgres/client.go
Forgot to quote the source table identifiers we use in validate mirror's source table check
> Validate mirror: account for mixed case

- .editorconfig
- flow/connectors/postgres/ssh_wrapped_pool.go
- flow/connectors/utils/ssh.go
- protos/peers.proto
- ui/app/peers/create/[peerType]/helpers/pg.ts
- ui/components/PeerForms/ClickhouseConfig.tsx
- ui/components/PeerForms/PostgresForm.tsx
Empty host key interpreted as accept-all
Fixes #804
UX would be greatly improved by implementing a "load host key" button which has server request host key from remote server & fill in ui field
Host keys can be acquired with
```sh
ssh-keyscan $HOST
```
> Support specifying host key for ssh config

- flow/activities/flowable.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/connectors/s3/s3.go
- flow/connectors/snowflake/snowflake.go
- flow/model/model.go
RelationMessageMapping of input is mutated,
thus it can be added to sync response from input at end
> CDCRecordStream: remove RelationMessageMapping

- flow/model/model.go
- flow/model/numeric/scale.go
- flow/model/qvalue/avro_converter.go
`200` was being synced as `199.99999999` in initial load for PostgreSQL -> Snowflake. It resided in a numeric column.
Noticed that in ToJSON where we transform numerics and other types for raw table insertion, we set the scale to 9 to conform with the scale value we've chosen for Snowflake for Numeric values (Number(38,9)). And this issue isn't present in CDC.
This PR does the same at `processNumeric` in the Avro transform step where we write to Avro files
> Numeric: adjust precision handling

- flow/activities/flowable.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/postgres.go
- flow/connectors/s3/s3.go
- flow/connectors/snowflake/snowflake.go
- flow/model/model.go
No need to query it twice
CatalogPool is always present, so remove nil check
> Pass sync batch id to SyncRecords

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/qrep.go
- flow/connectors/bigquery/qrep_avro_sync.go
- ui/app/peers/create/[peerType]/schema.ts
Service account JSONs can have permissions granted on them to access datasets in other projects. This PR supports datasetID being entered as `project.dataset` in the BQ peer, where the project is not the one specified in the SA
The main changes are:
1
```Go
client.Dataset(dataset)
// now becomes
client.DatasetInProject(project,dataset)
```
2
```Go
query := client.Query(..)
query.DefaultDatasetID := datasetID
query.DefaultProjectID := projectID
_, err := query.Read()
```
> BQ Peer: Support project dot dataset

- flow/connectors/eventhub/eventhub.go
- nexus/analyzer/src/lib.rs
Ident::to_string preserves quoting, so
```
exclude:["c2"]
exclude:[c2]
```
send different things to grpc endpoint,
which expects unquoted strings
Same goes for PartitionKeyColumn
> nexus: don't send quoting to grpc

- flow/activities/flowable.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/connectors/s3/s3.go
- flow/connectors/snowflake/snowflake.go
- flow/model/model.go
Simpler alternative to #1134
Particularly convenient having exclusion info already transformed into maps/sets in pull connector
Idea is that `CDCRecordStream` is a synchronization object. While `Records` is open everything is written to only by pull connector, we only receive records out Records channel. Pull connector relieves write access once `Records` closed, allowing everything else to read out the rest. In this regard `lastCheckpointSet` is unnecessary & I eventually intend to get rid of it
> Change CDCRecordStream TableSchemaChanges from channel to slice

- flow/connectors/eventhub/hubmanager.go
Eventhub's PartitionKey based routing for some reason was routing to only the first and the last partitions.
So route to PartitionID instead.
> Eventhub: Fix Partitioning

- flow/workflows/cdc_flow.go
- protos/flow.proto
Syntax has changed as a result due to switching to a proto:
```
{
"batch_size":100000,
"idle_timeout":10,
"additional_tables": [{
"source_table_identifier": "public.oss2",
"destination_table_identifier": "public.oss2dst"
}]
}
```
> added dynamic table addition to existing props signal

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/merge_stmt_generator.go
- flow/connectors/bigquery/qrep.go
- flow/connectors/bigquery/qrep_avro_sync.go
`DefaultDatasetID` and `DefaultProjectID` work only for unqualified tables. This PR unqualifies our tables in bigquery queries for qrep and cdc. 
Will update our docs to explicitly say that we support cross-project mode only for CDC  and QRep (BQ). This is yet to be integrated for resync mirror
This PR has been functionally tested with two projects.
Follow up to #1073
> BigQuery cross project support: unqualify tables for cdc/qrep

- flow/model/model.go
- protos/flow.proto
- ui/app/mirrors/create/cdc/cdc.tsx
- ui/app/mirrors/create/handlers.ts
- ui/app/mirrors/create/helpers/common.ts
- ui/app/mirrors/create/qrep/qrep.tsx
- ui/app/mirrors/edit/[mirrorId]/configValues.ts
Removes `QRepSyncMode`, `batch_size_int` and `batch_duration_seconds`
> removing deprecated params from QRep

- flow/connectors/utils/heartbeat.go
`time.After(x)` is same as `time.NewTicker(x).C`
> HeartbeatRoutine: use explicit ticker

- flow/activities/flowable.go
- flow/activities/slot.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/eventhub/hubmanager.go
Based on #1151,
the ticker.Reset doesn't need to be changed since ticker isn't shared between goroutines
> EventHub processBatch: handle `ctx.Done()`

- flow/connectors/postgres/cdc.go
- flow/connectors/utils/avro/avro_writer.go
- flow/e2e/test_utils.go
- flow/workflows/qrep_flow.go
We don't want temporal activities calling `os.Exit`
Also prefer `fmt.Sprint(x)` to `fmt.Sprintf("%v", x)`
> Avoid log.Fatalf in connector code, return error instead

- flow/workflows/xmin_flow.go
It's redundant & that redundancy caused a mixup:
code called `q.receiveAndHandleSignalAsync`,
but checked `x.activeSignal` instead of `q.activeSignal`
> xmin_flow: remove XminFlowExecution

- flow/activities/flowable.go
- flow/activities/slot.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/utils/heartbeat.go
Tickers are periodic: https://pkg.go.dev/time#NewTicker
> The ticker will adjust the time interval or drop ticks to make up for slow receivers
> Don't call ticker.Reset

- flow/.golangci.yml
- flow/connectors/clickhouse/qrep.go
- flow/connectors/postgres/postgres.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/snowflake.go
It turns out `rows.Next()` can return false on error, avoiding error detection with `rows.Scan`
See https://github.com/golangci/golangci-lint/issues/945
Fix that. In particular, `QueryRowContext` with checking for `sql.ErrNowRows` is much simpler when expecting 0 or 1 results
Mark two false positives when only wanting schema of `LIMIT 0` query
> lint: rowserrcheck

- flow/cmd/validate_peer.go
- flow/connectors/bigquery/bigquery.go
- ui/components/PeerForms/BigqueryConfig.tsx
- ui/tsconfig.json
Checks for bigquery.table.create and bigquery.jobs.create in validate peer logic
> Validate peer: check bigquery permissions

- flow/cmd/peer_data.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_partition_test.go
- flow/connectors/postgres/qrep_sql_sync.go
- flow/connectors/postgres/ssh_wrapped_pool.go
Instead, they should coexist
This way multiple pools/connections can use one tunnel
Also replace replPool, with its `MaxConns = 1`, with a connection
> Don't wrap pg connections with ssh tunnel

- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
This was being experimented with to help reduce slot size, however it's conflicting with reducing pool use
To have the two work together some kind of clone-for-new-connection mechanism needs to be made. But this code isn't used anymore, so defer implementing that mechanism for now by removing this code
> cdc: remove SetLastOffset

- ui/app/alert-config/page.tsx
- ui/app/peers/[peerName]/omitKeys.ts
- ui/app/peers/[peerName]/page.tsx
- ui/app/peers/[peerName]/peerDetails.tsx
- ui/app/peers/[peerName]/slottable.tsx
- ui/app/peers/[peerName]/stattable.tsx
Shows the peer's config object when clicking on the peer buttons. Sensitive keys not exposed.
> UI: Show peer configuration on clicking peer

- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/ssh_wrapped_pool.go
- nexus/postgres-connection/src/lib.rs
Nexus application_name is peerdb_nexus since those queries can be user generated
Remove unused code for creating pool over ssh tunnel
> Always set application_name when connecting to postgres

- flow/connectors/clickhouse/cdc.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/external_metadata/store.go
- flow/connectors/s3/s3.go
This stops relying on SyncBatchID being tightly sequential,
& combines SetLastOffset/IncrementID
Also remove unnecessary transaction in UpdateLastOffset
> external metadata: replace IncrementID with FinishBatch

- flow/connectors/postgres/qvalue_convert.go
- flow/e2e/test_utils.go
- flow/model/numeric/scale.go
- flow/model/qvalue/qvalue.go
**Pull side:** The way we were converting pgtype numeric to big.Rat was incorrect. Resulted in integers being written as 200 -> 199.99999 for PG->PG Qrep. This was caught by setting better values for numerics in our qrep tests. This PR adapts the logic from [jackc's numeric.go](https://github.com/jackc/pgtype/blob/31dd0e442de8bbd1fbf0865b3c76d40708d3e429/numeric.go#L422)
**compareNumeric:** For numbers like 1.123 or 1.12345678 (less than 9 digits to the right), we now assert that they should be exactly equal. If one of the values has more than 9 digits to the right, we fall back to the difference less than 1e9 check. 
This change was tested with the old `processNumeric` code, and it caught the suboptimal conversion of 200 -> 199.9999...
> Fix numeric datatype

- flow/workflows/cdc_flow.go
- flow/workflows/qrep_flow.go
- flow/workflows/xmin_flow.go
An issue with drop mirror was seen where the peer flow would continue as new and sync, normalize flows would be spawned
This PR catches erred contexts before returning ContinueAsNew in CDC, qrep and xmin flows
This has been manually tested
> Drop Mirror Fix: Prevent continueasnew

- flow/cmd/validate_mirror.go
- ui/app/mirrors/edit/[mirrorId]/page.tsx
- ui/components/DropDialog.tsx
- ui/components/ResyncDialog.tsx
Introduces a resync button in the specific mirror page which when clicked opens a confirmation dialog box.
The resync when done via UI:
- first calls drop mirror and drops the mirror
- kicks off a cdc mirror with the same config as the current mirror, with `resync:true` added
> UI: Resync button

- ui/components/ResyncDialog.tsx
Always set `do_initial_snapshot` to true for resync
This has been manually tested for a mirror with that setting set to false and then resynced
> UI: set do_initial_snapshot to true for resync

- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/bigquery/qrep_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/s3/cdc_s3_test.go
- flow/e2e/s3/qrep_flow_s3_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
- flow/e2e/sqlserver/qrep_flow_sqlserver_test.go
- flow/e2e/test_utils.go
Logging to os.Stdout mixes up logging in test output, wrap t.Log in an io.Writer interface to avoid that
This is not ideal, there are proposals to address this in go:
1. https://github.com/golang/go/issues/22513
2. https://github.com/golang/go/issues/59928
> Temporal test workflow: don't log to os.Stdout

- ui/app/api/peers/slots/[name]/route.ts
- ui/app/dto/PeersDTO.ts
- ui/app/mirrors/edit/[mirrorId]/aggregatedCountsByInterval.ts
- ui/app/peers/[peerName]/lagGraph.tsx
- ui/app/peers/[peerName]/page.tsx
Note: the line chart above was generated by a random series of slot sizes for representation purposes
The selected slot name is persisted in local storage
> UI: Line chart for slot growth

- flow/connectors/bigquery/bigquery.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/utils/heartbeat.go
Ideally e2e tests would pass context with mock activity,
but in meantime this'll reduce noise in test logs
& is a bit more efficient
> utils.RecordHeartbeat: use activity.IsActivity

- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/congen.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/s3/qrep_flow_s3_test.go
- flow/e2e/s3/s3_helper.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/snowflake_schema_delta_test.go
- flow/e2e/sqlserver/qrep_flow_sqlserver_test.go
- flow/e2e/test_utils.go
Global logger should not be used with parallel testing
> Replace slog with t.Log in e2e tests

- flow/cmd/handler.go
- flow/cmd/mirror_status.go
- flow/shared/constants.go
- flow/workflows/cdc_flow.go
- protos/route.proto
- ui/app/api/mirrors/state/route.ts
- ui/app/mirrors/[mirrorId]/edit/page.tsx
- ui/app/mirrors/[mirrorId]/page.tsx
- ui/app/mirrors/create/cdc/cdc.tsx
- ui/app/mirrors/create/cdc/schemabox.tsx
- ui/app/mirrors/create/cdc/tablemapping.tsx
- ui/app/mirrors/create/handlers.ts
`IdleTimeoutSeconds` and `SyncBatchSize` can be changed anytime, tables can only be added IF mirror is paused, otherwise the button will be disabled.
Additional changes for this:
1) moved CDC dynamic properties to the main signal selector and blocking on the main signal selector while paused, so we can receive mirror edits even while paused.
2) pass `TableNameSchemaMapping` from state always to `NormalizeFlow` in case new tables were added.
3) added a new property to the tables component to disable selecting of tables already in the mirror.
There is a bug where tables added to the mirror dynamically will not reflect in the status screen, will be fixed in a follow up PR. `TableMappings` Needs to be stored in state as well.
> UI for editing mirror parameters

- flow/cmd/api.go
- flow/cmd/snapshot_worker.go
- flow/cmd/worker.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/qrep.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/normalize_stmt_generator.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep_partition_test.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/qrep_sql_sync.go
- flow/connectors/s3/s3.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/sqlserver/sqlserver.go
- flow/connectors/utils/avro/avro_writer.go
- flow/logger/from_ctx.go
Noticed that in e2e tests, logs of a different test appear in the current test's logs. This PR is an attempt to fix that by obtaining a temporal logger from the current context and using that in our connectors instead of the slog instance.
> Try using temporal's activity.GetLogger

- nexus/catalog/src/lib.rs
Recently combined catalog connections for nexus connections,
now `SET search_path` queries change search_path for our backend connection, breaking things
> nexus/catalog: fully qualify tables in queries

- .github/workflows/flow.yml
- flow/activities/flowable.go
- flow/cmd/handler.go
- flow/cmd/mirror_status.go
- flow/connectors/postgres/cdc.go
- flow/connectors/utils/cdc_records/cdc_records_storage.go
- flow/connectors/utils/cdc_records/cdc_records_storage_test.go
- flow/peerdbenv/config.go
- flow/workflows/cdc_flow.go
- flow/workflows/normalize_flow.go
- flow/workflows/qrep_flow.go
- flow/workflows/setup_flow.go
- flow/workflows/sync_flow.go
- flow/workflows/xmin_flow.go
- nexus/flow-rs/src/grpc.rs
- protos/flow.proto
- protos/route.proto
- ui/app/api/mirrors/cdc/route.ts
- ui/app/api/mirrors/qrep/route.ts
- ui/app/mirrors/[mirrorId]/cdc.tsx
- ui/app/mirrors/[mirrorId]/edit/page.tsx
1. `TableMappings` is now cloned and stored in state, and modifications affect only state version. Pass it through to `SyncFlow`.
2. Fixed some logs
3. removed env var for idle timeout seconds, but retaining function for tests.
4. Renamed mispelt proto field.
5. bug in UI, wasn't looking at the correct version of `additionalTables`
6. optimization - don't store records from CDC in some cases
7. don't heartbeat after every record.
> fixes for UI and general

- flow/connectors/eventhub/eventhub.go
- flow/connectors/eventhub/hubmanager.go
- flow/connectors/eventhub/scoped_eventhub.go
The destination table name in table mapping of Create CDC Mirror now expected to look like: 
```
<eventhub_name>.<eventhub_namespace>.<unique_identifier>.<partition_key>
```
This is to allow multiple source tables to be mapped to same eventhub partition.
`unique identifier` can be the source table name or anything else. It's purely to distinguish destination table names
> Eventhubs: Refactor Destination Table Semantics

- flow/connectors/clickhouse/cdc.go
- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/connectors/s3/s3.go
- nexus/analyzer/src/lib.rs
- nexus/catalog/src/lib.rs
- nexus/peer-postgres/src/lib.rs
- nexus/postgres-connection/src/lib.rs
- protos/peers.proto
- ui/app/peers/create/[peerType]/helpers/ch.ts
- ui/app/peers/create/[peerType]/schema.ts
- ui/components/PeerForms/ClickhouseConfig.tsx
This PR refactors the Clickhouse peer to now have the S3 fields - object path, access key id, secret key and region:
```
message ClickhouseConfig{
string host = 1;
uint32 port = 2;
string user = 3;
string password = 4;
string database = 5;
string s3_path = 6; // path to S3 bucket which will store avro files
string access_key_id = 7;
string secret_access_key = 8;
string region = 9;
}
```
The UI for Clickhouse peer creation has been updated accordingly:
Validation for the S3 stage is also added as part of validate peer for clickhouse.
Nexus code updated accordingly.
This PR has been functionally tested by validating and creating a clickhouse peer followed by performing a basic CDC PG -> CH mirror
> Clickhouse peer: specify S3 fields

- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/shared/additional_tables.go
1. fixes an issue where duplicate additional tables were not being rejected properly
2. made adding tables to publication more lenient, if default pub name we add tables but don't error out if table is already in publication, if custom name we just check.
> fixing bugs with rejecting dups + lenient addpub

- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
In the Postgres connector, the sync side doesn't take advantage of record streaming over Go channels, loading all records into an array and then processing when the channel is closed from the pull side. This PR addresses that and now Postgres copies from a function invocation instead of an array, therefore copying records while they're being read from the channel. 
This leads to lower memory utilization (no massive buffer) and improved parallelism.
also changing some `Info` logs back to `Debug` to prevent spam
> Postgres streaming using CopyFromFunc

- flow/connectors/eventhub/eventhub.go
- flow/connectors/eventhub/hubmanager.go
- flow/connectors/eventhub/scoped_eventhub.go
Destination for eventhub cdc mirror is now of the form `peername.eventhub_name.unique_key.column_name`
> Eventhub: Revert to earlier order with unique key

- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/s3/cdc_s3_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/test_utils.go
Thinking in #1211 the workflow is exiting with an error which we're then ignoring & letting test pass but cleanup fail
> e2e: require workflows exit with canceled error when expected to be canceled

- flow/workflows/drop_flow.go
Somehow between testing & merging I screwed up adding initial activities to selector,
causing drop flow to indefinitely hang
Also need explicit listen on ctx.Done in selector since `selector.Select(ctx)` doesn't return if ctx is canceled, so if the activities hung in selector that'd cause our workflow to ignore cancelation
> drop_flow: fix hanging bug

- flow/cmd/mirror_status.go
Checks if syncflowoptions is not nil before getting the mirror edits
> flow api: fix nil pointer handling

- flow/connectors/bigquery/bigquery.go
Was seeing activity heartbeat timeouts during destination table setup for a large number of tables. This PR attempts to fix that
> Fix normalize heartbeats

- flow/model/model.go
Checks for nil value of rat in `toMap` which is responsible for converting records to json for writing to avro files
> Numeric nil case: cdc fix

- ui/app/mirrors/create/helpers/cdc.ts
Changes UI's setting name of the initialSnapshotOnly parameter
> Initial copy only : change param name

- flow/connectors/postgres/postgres.go
- flow/connectors/utils/postgres.go
A couple of our queries [`getTableSchemaForTable` and `getChildToParentRelIDMap`] use the simple query protocol (why is this needed? not sure). pgx requires `client_encoding` to be set to `UTF8` for using the simple query protocol, but it won't be set if the database we are connecting to doesn't use the `UTF8` encoding, which isn't very likely but still possible.
Fixed by explicitly mentioning `client_encoding` in the connection string. Also moving `application_name` there.
> explicitly set client_encoding to UTF8

- flow/connectors/utils/cdc_records/cdc_records_storage.go
- flow/peerdbenv/config.go
- flow/peerdbenv/env.go
the existing number of records based threshold is still present, both can be active at the same time.
Best used with `GOMEMLIMIT` to keep heap more aligned with set memory limit.
> spill to disk based on flow-worker memory usage

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/qrep.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/clickhouse/cdc.go
- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/clickhouse/normalize.go
- flow/connectors/clickhouse/qrep.go
- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/external_metadata/store.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_sql_sync.go
- flow/connectors/s3/qrep.go
- flow/connectors/s3/s3.go
- flow/connectors/snowflake/avro_file_writer_test.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/qrep_avro_consolidate.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/utils/avro/avro_writer.go
Along with `connector.ctx` references in internal helpers
Also replace more slog.Logger with temporal log.Logger
This is the initial start to enabling containedctx lint, which moves away from coupling connectors with their constructor's context
Removing ctx from connectors will require updating interfaces, which will be done as a followup
> Remove ctx from PostgresMetadataStore & peerDBOCFWriter

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/merge_stmt_generator.go
- flow/connectors/utils/array.go
BQ `it.Next(&row)` seems to mutate the target,
https://github.com/googleapis/google-cloud-go/blob/f049c9751415f9fc4c81c1839a8371782cfc016c/bigquery/value.go#L490
so reallocate a fresh row each iteration
ArrayChunks: replace with ArrayIterChunks. Document behavior when input is empty slice
Also reduces allocations, since we've seen people having 1000+ columns
go 1.22 has a rangefunc experiment, so eventually we can replace this with that https://go.dev/wiki/RangefuncExperiment
> BQ merge fixes

- flow/cmd/peer_data.go
Probably a good practice to not use information_schema views. Relying on pg tables instead.
This PR has been functionally tested
> UI API: Remove usage of information schema

- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/core.go
- flow/connectors/eventhub/hub_batches.go
- flow/connectors/eventhub/hubmanager.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_query_build_test.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/qrep_sql_sync.go
- flow/connectors/postgres/ssh_wrapped_pool.go
- flow/connectors/sqlserver/qrep.go
- flow/connectors/utils/avro/avro_writer.go
- flow/connectors/utils/cdc_records/cdc_records_storage.go
- flow/connectors/utils/cdc_records/cdc_records_storage_test.go
- flow/connectors/utils/monitoring/monitoring.go
- flow/dynamicconf/dynamicconf.go
- flow/model/qrecord_batch.go
- flow/shared/alerting/alerting.go
Things are getting a bit messy since while https://github.com/temporalio/sdk-go/issues/1158 claims the interfaces are compatible in reality there's a mess about what the two different implementations expect from `args ...interface{}`
For now use context specific logger more to mangle output less in CI. A more correct/complete solution will have to be worked out in future
> Replace more use of default slog handler with logger from context

- flow/connectors/clickhouse/normalize.go
We were running into a syntax error with the insert-into-select statement in normalize flow due to quoting. This PR removes that
> Clickhouse: Remove quote from Normalize statement

- flow/model/qvalue/avro_converter.go
Use the schema for data as documented in [Avro specification](https://avro.apache.org/docs/1.8.0/spec.html#Date) (basically what we already use for bigquery date)
This PR fixes date syncing for clickhouse initial load aka qrep and has been functionally tested
> Set correct avro schema for clickhouse date

- flow/connectors/clickhouse/cdc.go
- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/connectors/utils/aws.go
- flow/shared/constants.go
- ui/app/mirrors/create/handlers.ts
- ui/app/peers/create/[peerType]/schema.ts
- ui/components/PeerForms/ClickhouseConfig.tsx
Now requires one of the two:
1. Env variables for S3 credentials
2. S3 credentials from clickhouse peer which are now optional in UI
For the former, the bucket path is constructed by bucket-name/deployment-uid/flowname
> Refactor s3 wiring for clickhouse

- flow/connectors/core.go
Split out from moving normalized table creation to a separate connector interface
> connectors: build on a single GetConnector using generic GetConnectorAs function

- flow/activities/flowable.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/merge_stmt_generator.go
- flow/connectors/clickhouse/normalize.go
- flow/connectors/core.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/postgres.go
- flow/connectors/s3/s3.go
- flow/connectors/snowflake/snowflake.go
- flow/workflows/qrep_flow.go
- flow/workflows/setup_flow.go
Snowflake was sending a heartbeat for each table, BQ was using HeartbeatRoutine, clickhouse wasn't sending heartbeats. Unify on HeartbeatRoutine
Move to a separate connector interface so s3/eventhubs etc don't need to implement the start/abort/finish methods as stubs too
Also introduce a generalized GetConnectorAs, use internally for existing functions
> CreateNormalizedTable: lift loop, make it based on separate connector

- flow/connectors/postgres/postgres.go
- flow/shared/alerting/alerting.go
- flow/shared/alerting/slack_alert_sender.go
- ui/app/alert-config/new.tsx
- ui/app/alert-config/validation.ts
- ui/tsconfig.json
> custom threshold support for slack alerts

- flow/connectors/bigquery/bigquery.go
- flow/connectors/clickhouse/cdc.go
- flow/connectors/postgres/client.go
- flow/connectors/snowflake/snowflake.go
avoids mirror `a__b` from having a name conflict with `a_b`
> raw table names: preserve underscores in names

- flow/connectors/postgres/qvalue_convert.go
- flow/connectors/snowflake/merge_stmt_generator.go
- flow/model/conversion_avro.go
- flow/model/qrecord_batch.go
- flow/model/qvalue/avro_converter.go
> Misc cleanup of qvalue code

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/merge_stmt_generator.go
Merge statements currently are syntactically incorrect for tables without a primary key. This case is ideally not seen as tables without pkey/replica identity full are filtered out the UI level but in branches where we rely on signals for adding tables, this case can go unchecked and normalize flow fails.
This PR skips a table during merge if there are no primary keys for it.
> BigQuery: Skip merge if no primary keys present

- flow/connectors/bigquery/bigquery.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_bench_test.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/qrep_query_executor_test.go
- flow/connectors/postgres/qvalue_convert.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/bigquery/qrep_flow_bq_test.go
- flow/e2e/congen.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/s3/cdc_s3_test.go
- flow/e2e/s3/qrep_flow_s3_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
- flow/e2e/sqlserver/qrep_flow_sqlserver_test.go
- flow/e2e/test_utils.go
- flow/e2eshared/e2eshared.go
- flow/geo/geo.go
- flow/model/qvalue/qvalue.go
Logs of this nature should only be generated once per connector
PostgresCDCSource & QRepQueryExecutor now extend PostgresConnector,
stops QRepQueryExecutor querying for customTypesMapping for snapshots
> Don't spam logs about unknown types being sent as text

- flow/activities/flowable.go
Main thread waits on errGroup.Wait sooner,
so that if an error happens it'll be the original error,
instead of reporting context canceled from SyncRecords after PullRecords error
Also causes context cancelation to be two way:
if SyncRecords fails, PullRecords will now be canceled
> cdc: also run SyncRecords in error group

- flow/connectors/utils/cdc_records/cdc_records_storage.go
Since we use it in HeartbeatRoutine
> Make cdcRecordsStorage Len threadsafe

- flow/cmd/validate_mirror.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/validate.go
Validate mirror now also checks: if no publication provided, we can create (and drop) a publication for the selected tables.
> Validate mirror: publication creation

- flow/connectors/postgres/validate.go
Bypass no rows error due to some managed offerings being different
> Validate mirror: Bypass no rows error

- flow/activities/flowable.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/clickhouse/cdc.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/connectors/s3/s3.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/utils/monitoring/monitoring.go
- flow/model/cdc_record_stream.go
1. monitoring should remain connector agnostic, not using pglogrepl in activities/flowable.go
2. GetLastCheckpoint returning error would only happen due to programmer error; panic instead
3. NewPostgresCDCSource becomes infalliable when caller responsible for childToParentRelIDMap
Also have CDCRecordStream ignore redundant calls to Close
> Cleanup code for reduced error handling

- flow/activities/flowable.go
- flow/activities/snapshot_activity.go
- flow/cmd/peer_data.go
- flow/cmd/validate_mirror.go
- flow/cmd/validate_peer.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/clickhouse/normalize.go
- flow/connectors/core.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/postgres_schema_delta_test.go
- flow/connectors/postgres/qrep_bench_test.go
- flow/connectors/postgres/qrep_query_executor_test.go
- flow/connectors/s3/s3.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/sql/query_executor.go
- flow/connectors/sqlserver/sqlserver.go
- flow/e2e/congen.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/snowflake_schema_delta_test.go
Also remove unnecessary nil checks,
& make self nil check in Connector Close methods consistent
This helps gracefully close connections when workflow canceled
> Improve Close: use 1 minute timeout instead of potentially canceled context

- flow/cmd/handler.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
Cancelling drop flow after a minute isn't a good idea. Slot remains active after sync flow dies (i.e it is fully cancelled, not waiting) for more than a minute (for some reason) causing drop flow to cancel and the slot surviving. Bumped it up to 5 minutes.
> Fixes to potentially aid drop mirror

- flow/connectors/clickhouse/qrep_avro_sync.go
The check for skipping peerdb columns in insert-into-select in clickhouse qrep was failing due to case mismatch. this PR fixes this
> Clickhouse QRep Insert: use strings.EqualFold

- flow/activities/flowable.go
`SetupNormalize` returning true implies the table was pre-existing, not that it was now created. The logging was reversed
> Fix switched up logging for table creation

- flow/activities/flowable.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/eventhub/hubmanager.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/utils/avro/avro_writer.go
- flow/connectors/utils/heartbeat.go
- flow/workflows/sync_flow.go
- Moves getting of last offset to start flow and removes from peer flow
> refactor fetching and pushing of last offset

- flow/connectors/clickhouse/clickhouse.go
- nexus/analyzer/src/lib.rs
- protos/peers.proto
- ui/app/peers/create/[peerType]/helpers/ch.ts
- ui/app/peers/create/[peerType]/helpers/common.ts
- ui/app/peers/create/[peerType]/helpers/pg.ts
- ui/app/peers/create/[peerType]/helpers/s3.ts
- ui/app/peers/create/[peerType]/helpers/sf.ts
- ui/components/PeerForms/ClickhouseConfig.tsx
For a clickhouse server running without tls (for example clickhouse docker), mirror fails and we would need to comment out the tls setting. This PR adds a flag - disableTls - to the clickhouse peer so that this is not needed. This can be configured in UI and query layer for create peer
> Add disableTls option for clickhouse

- flow/connectors/clickhouse/clickhouse.go
- nexus/analyzer/src/lib.rs
- protos/peers.proto
Default false, no need for tri-value state
protobuf values default to zero value already
> clickhouse disable tls: non-nullable

- flow/activities/flowable.go
- flow/connectors/postgres/cdc.go
- flow/workflows/cdc_flow.go
Introduced hastily in #1335, `state.SyncFlowOptions.RelationMessageMapping = state.RelationMessageMapping` needs to happen before constructing arguments for activity
> Fix nil relationMessageMapping not updating original input field

- flow/connectors/clickhouse/normalize.go
It appears timeseries performance is a common use-case for Clickhouse, wherein users often index based on a `DateTime` column. Clickhouse does not allow indexing based on `Nullable` columns.  Also having nullable columns decreases performance.
Thus, this PR chooses to stay with the original mapping of DateTime and Date (without the Nullable)
A decision is to be made in the future regarding whether we get user's preference on setting a column as Nullable or not for Clickhouse mirrors
> Clickhouse: remove nullable mapping

- flow/activities/flowable.go
- flow/cmd/mirror_status.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/workflows/cdc_flow.go
- protos/flow.proto
Only pass config & options to StartFlow, removing StartFlowInput
In fact, while we're at it, rename StartFlow to SyncFlow,
the name doesn't really make sense anymore,
& it'll make less sense after #1211
> Remove redundancy between cdc state & sync flow options

- flow/activities/flowable.go
- flow/cmd/worker.go
- flow/connectors/core.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/e2e/test_utils.go
- flow/workflows/cdc_flow.go
Currently we reconnect with each sync flow, requiring repeatedly starting replication. This can take an exceedingly long time for some workloads on some databases
Fix: use temporal session to share state between activities, use a single source connector throughout cdc flow, & move replication connection back into source connection
> Maintain replication connection between sync flows

- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/ssh_wrapped_pool.go
Sometimes with replication connections `-- ping` isn't playing well, replace with `SELECT 1`
> replace ping with `SELECT 1`

- flow/connectors/postgres/client.go
- ui/app/api/peers/slots/[name]/route.ts
- ui/app/peers/[peerName]/lagGraph.tsx
- Fix lag point computation
- Use `pg_current_wal_lsn() - restart_lsn` instead of confirmed_flush_lsn
- Fix placeholder not showing in slot dropdown
> UI: Fix slot graph

- flow/workflows/cdc_flow.go
- flow/workflows/normalize_flow.go
- flow/workflows/qrep_flow.go
- flow/workflows/scheduled_flows.go
https://pkg.go.dev/go.temporal.io/sdk/workflow#hdr-SideEffect_API
> The only way to fail SideEffect is to panic, which causes workflow task failure
The only way it would return error was if returned value cannot be decoded;
it would be a programmer error to use such a type, we're not going to hit that with strings/bools
> GetSideEffect: be infallible, also avoid unnecessary SendWalHeartbeat workflows

- flow/e2e/postgres/peer_flow_pg_test.go
- flow/model/model.go
- flow/model/signals.go
- flow/workflows/cdc_flow.go
- flow/workflows/normalize_flow.go
Results/Errors are sent via signal instead of buffering & sending at end
> Split normalize changes from split-cdc-sync

- flow/connectors/bigquery/bigquery.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/qrep_bench_test.go
- flow/connectors/postgres/qrep_partition_test.go
- flow/connectors/snowflake/snowflake.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/sqlserver/qrep_flow_sqlserver_test.go
- flow/e2e/test_utils.go
- flow/e2eshared/e2eshared.go
1. reflect.TypeOf
2. no need to copy loop variable for closure
3. `range N` replaces basic count-to-N loop
Need to update golangci, see #1386
> go 1.22 features

- flow/workflows/qrep_flow.go
Currently for a table with no rows in it, initial load fails with:
```
WorkflowTaskFailed
--
"message": "runtime error: integer divide by zero",
```
This was occurring in processPartitions in qrep_flow.go:
```golang
chunkSize := shared.DivCeil(len(partitions), maxParallelWorkers)
batches := make([][]*protos.QRepPartition, 0, len(partitions)/chunkSize+1) -- div by zero if no partitions
```
This PR fixes this by skipping processPartitions if there are no partitions
> FIx case where table has no rows

- ui/app/mirrors/create/cdc/schemabox.tsx
- ui/app/mirrors/create/handlers.ts
Fixes a bug with select all where not mirrorable tables are included
> UI: filter out no canMirror

- flow/e2e/postgres/qrep_flow_pg_test.go
Adds a test for syncing an empty table via QRep. 
This PR is to address [this comment](https://github.com/PeerDB-io/peerdb/pull/1393#issuecomment-1968746921)
The test successfully caught the error which was seen [pre-patch](#1393):
```
qrep_flow_pg_test.go:340: 
Error Trace: peerdb/flow/e2e/postgres/qrep_flow_pg_test.go:340
Error:          Received unexpected error:
workflow execution error (type: QRepFlowWorkflow, workflowID: default-test-workflow-id, runID: default-test-run-id): 
runtime error: integer divide by zero
```
> QRep: Add test for no rows mirror

- flow/e2e/bigquery/qrep_flow_bq_test.go
- flow/model/qvalue/avro_converter.go
- flow/model/qvalue/timestamp.go
The lower bound check of 1 AD was not correct in processTimestamp/TZ in avro writing in BigQuery. More readable function now.
Also adds the check for Date in avro writing.
Test updated
> BigQuery: Better disallow timestamp function usage

- flow/workflows/cdc_flow.go
Avoids a benign error in temporal logs when pausing mirror
> cdc: don't send normalize-done after sync flow finished

- flow/activities/flowable.go
Replaces a usage waitgroup with errgroup in replicateQRepPartitions in flowable.go
This is a preceding PR to #1368
> Flowable: Use errgroup in replicateQRep

- flow/activities/flowable.go
- flow/workflows/sync_flow.go
Turns out no retry policy means unlimited retries
When MaintainPull ReplPing fails, sync flow should be restarted
Tested this by calling `pg_terminate_backend` on source's `START REPLICATION` connection
> MaintainPull: ReplPing error is non retryable

- flow/e2e/postgres/peer_flow_pg_test.go
- flow/workflows/cdc_flow.go
- ui/app/mirrors/[mirrorId]/edit/page.tsx
- ui/app/mirrors/[mirrorId]/page.tsx
- ui/components/EditButton.tsx
1. Edit Mirror button is completely disabled unless mirror is paused.
2. Automatic unpausing once we finish processing config update.
3. Labels to convey automatic unpausing
> making UX for edit mirror simpler

- flow/activities/flowable.go
errgroup seems to prefer the error raised by one of its goroutines rather than the calling context's cancelation for Wait's return value, return context.Canceled to set Wait result & cancel pull
> errgroup: return context.Canceled instead of using another context

- flow/connectors/bigquery/avro_transform_test.go
- flow/connectors/bigquery/qrep_avro_sync.go
Not sure how this issue wasn't caught until now, but not explicitly specifying the column order in the QRep insert into select statement can cause it to fail due to column-value insert mismatch (ex: expected int but got bool for _peerdb_is_deleted)
> BigQuery: More reliable insert-into-select 

- flow/connectors/bigquery/merge_stmt_generator.go
- flow/e2e/bigquery/peer_flow_bq_test.go
Float, JSON (and other [non-groupable types in bigquery](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#groupable_data_types )) as primary key is not supported by our merge statement in BigQuery as during our primary key comparison, BigQuery cannot compare, for example, JSON values:
```
googleapi: Error 400: Equality is not defined for arguments of type JSON
```
This PR makes a step towards supporting such columns in primary keys for BigQuery merge by transforming it to string there for `PARTITION BY` and comparison
Test added
> Bigquery: Support JSON, FLOAT PKey For Merge

- flow/connectors/bigquery/merge_stmt_generator.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
Pause is now hard pause, so don't test that pause includes final sync
This part of test was a bit racy anyways
> Fix regressed signals test

- flow/cmd/api.go
- flow/cmd/snapshot_worker.go
- flow/cmd/worker.go
- flow/shared/constants.go
- flow/workflows/cdc_flow.go
- flow/workflows/snapshot_flow.go
Removes need for error check
Also previously both task queues had same iota value, so that was wrong
> Remove integer TaskQueueID

- flow/e2e/postgres/peer_flow_pg_test.go
- flow/model/signals.go
- flow/workflows/cdc_flow.go
- flow/workflows/normalize_flow.go
- flow/workflows/sync_flow.go
All of these should be logged instead of put in state, this avoids queries failing to due to size being too large
Since normalize/sync flows handle their logging, reduce signalling too
SyncFlowStatuses was being checked by dynamic signals test to test exact batch numbering.
Be looser: testing that data is being replicated properly is sufficient
> CDCFlowWorkflowState: remove Progress, Statuses, Errors

- ui/app/alert-config/new.tsx
- ui/app/alert-config/page.tsx
- ui/app/alert-config/validation.ts
- ui/app/api/alert-config/route.ts
- ui/components/AlertDropdown.tsx
- ui/components/DropDialog.tsx
- ui/package-lock.json
- ui/package.json
> UI: Edit Alerts

- flow/connectors/snowflake/snowflake.go
errgroup.Go unconditionally executes the function / waits, causing pauses to be ignored for awhile
> Snowflake normalize: check gCtx.Err() while iterating through tables

- flow/workflows/cdc_flow.go
Pause mirror second time onwards was not being respected as the state was not being wiped if only idle timeout / batch size is edited, because when additionTables is empty we just return nil before setting state to nil. This made flowConfigUpdate perenially not nil, which caused the mirror to never enter the pause loop.
This PR moves the setting of state to nil outside of processConfigUpdates and also adds logs
> CDC Flow: fix state wipe

- docker-compose-dev.yml
- docker-compose.yml
`postgresql` appears to be a plugin that doesn't support Temporal [advanced visibility](https://docs.temporal.io/visibility#advanced-visibility) which we use in `flow-api`. It now crashes on startup.
Reverting the change made in #1388
> revert change to Temporal database plugin

- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
- flow/workflows/cdc_flow.go
Customer workflow recently got stuck after sync-stop,
add test covering cdc_flow returning ContinueAsNew multiple times
cdc_flow had custom retry logic to pass tests before they were switched to integration tests,
get rid of that, it was racy with signals, rely on temporal retries for workflow errors
& restarting cdc entirely if sync/normalize finish for whatever reason
> Fix & test cdc rollover

- flow/.golangci.yml
- flow/cmd/handler.go
- flow/cmd/peer_data.go
- flow/connectors/clickhouse/qrep_avro_sync.go
shadow would need to ignore shadowing `err`,
& fieldalignment raises many warnings which can be evaluated in a future PR to reduce memory footprint
> Enable all govet lints besides fieldalignment/shadow

- flow/shared/telemetry/sns_message_sender.go
`subject[:100]` is byte based, not character based, causing AWS to reject control characters
Properly limit to 100 characters, rather than 100 bytes
> fix(telemetry): issue with aws sns

- .github/workflows/flow.yml
- flow/connectors/postgres/postgres_schema_delta_test.go
- flow/e2e/bigquery/bigquery.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/bigquery/qrep_flow_bq_test.go
- flow/e2e/congen.go
- flow/e2e/generic/peer_flow_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/postgres/postgres.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/s3/qrep_flow_s3_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/snowflake.go
- flow/e2e/snowflake/snowflake_schema_delta_test.go
- flow/e2e/sqlserver/qrep_flow_sqlserver_test.go
- flow/e2e/test_utils.go
- flow/e2eshared/e2eshared.go
- flow/model/qvalue/qvalue.go
- flow/workflows/cdc_flow.go
- flow/workflows/setup_flow.go
Lay out basic design for generic connector testing,
replacing `Test_Simple_Flow` with a single definition used for PG/SF/BQ
More can be ported in followup PRs,
so when new connectors are added they implement `GenericSuite` to have e2e tests
Also fix hstore comparison so it works with Snowflake
> POC: generic Test_Simple_Flow

- flow/connectors/s3/s3.go
- ui/components/PeerForms/S3Form.tsx
GCS Peer validation seemingly has regressed, failing in UI peer creation.
UI was setting the endpoint without the https prefix, and also this PR removes listing buckets as part of validation for storage peers, as that isn't an operation we do as part of mirrors.
Functionally tested with peer creation and functioning CDC mirror with initial load
> Fix GCS endpoint and validation

- flow/activities/flowable.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/snowflake.go
Snowflake validate could fail if the user creates an internal schema before hand, in which case permissions for schema creation are not necessary and may not be given. Our validate for snowflake will fail as it tries to create a dummy schema
The change this PR makes is to check if the raw schema exists (see note). If it doesn't then, create it. The remaining steps - table create, insert row etc. remain the same. `create schema if not exists` does not bypass snowflake's permission checks for schema creation
Removes drop schema step as that isn't something we do in mirrors
note - this is also done at raw table creation and qrep metadata table creation where we create schemas
> Validate peer: fix snowflake validate

- flow/activities/flowable.go
#1447 included a fix for flowable logs but removes context values which downstream code needs.
This PR restores the context.WithValue calls
> Flowable: restore log attributes in context

- flow/model/signals.go
- flow/workflows/cdc_flow.go
- flow/workflows/normalize_flow.go
- flow/workflows/sync_flow.go
Fixes #1448
Solves via two redundant angles:
1. drain normalize-done at start
2. don't send normalize-done when `ctx.Err() != nil`
The race was consistently happening when normalize received cancel while in normalize activity. It'd then send normalize-done to parent, who already having returned continue-as-new but waiting on children to finish, would have the signal buffer for its next run
> Fix normalize-done race causing sync/normalize to execute in parallel after pause/resume

- flow/shared/telemetry/sns_message_sender.go
break before reaching 100 characters limit as limit is `<100`
> fix(telemetry): sns subject length

- flow/activities/flowable.go
- flow/activities/snapshot_activity.go
- flow/alerting/alerting.go
Might be preferable to have these error receiving functions return that error, allowing a natural
```
return alerter.LogFlowError(ctx, flowName, fmt.Errorf("...: %w", err))
```
Instead of logging inner err & only returning the `fmt.Errorf` error. Which would also help recover some logging this PR removes while deduplicating logging error & alerter.LogFlowError
> alerting: also log to logger

- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_sql_sync.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/snowflake.go
- flow/model/numeric/scale.go
- flow/workflows/qrep_flow.go
- protos/flow.proto
1. somewhat support QRep from multiple watermark tables in a single mirror
2. Use `ConsolidateQRepPartitions` to gain atomicity for all table swaps
3. SF's `NUMBER` type is now more accurately created in PG (`NUMERIC` with derived precision and scale)
4. mirrors automatically restart if parameter `WaitBetweenBatchesSeconds` set
> improvements to SF->PG QRep

- flow/cmd/handler.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_sql_sync.go
- flow/connectors/utils/postgres.go
- flow/workflows/qrep_flow.go
- ui/app/api/mirrors/qrep/route.ts
- ui/app/mirrors/create/handlers.ts
- ui/app/mirrors/create/helpers/common.ts
- ui/app/mirrors/create/schema.ts
- Supports full refresh with schema changes every refresh interval
- Wire up UI
> SF QRep: support schema changes on refresh, clean up UI

- ui/app/api/peers/slots/[name]/route.ts
- ui/app/dto/PeersDTO.ts
- ui/app/peers/[peerName]/lagGraph.tsx
1. past month gets 8640 points, only send back at most 720 (randomly selected)
2. transmit numbers; formatting happens on client
3. always show HH:mm in timestamp
> Optimize slot lag graph

- flow/activities/flowable.go
- flow/connectors/core.go
- flow/connectors/postgres/postgres.go
When an error happens we must update replState.Offset still,
as with activity retries it's possible to end up in a scenario:
replState.Offset is 1, last offset in catalog is 1, repl connection is at 3
PullRecords will go ahead reading from 4, skipping LSN 2 & 3
> PullRecords: update replState.Offset in defer

- flow/activities/flowable.go
Wrapping an application error prevents preventing retries
> SyncFlow: fix NonRetryableError handling from PullRecords

- flow/connectors/postgres/qrep_query_executor_test.go
- flow/connectors/postgres/qvalue_convert.go
- flow/connectors/snowflake/avro_file_writer_test.go
- flow/connectors/sql/query_executor.go
- flow/connectors/utils/cdc_records/cdc_records_storage.go
- flow/connectors/utils/cdc_records/cdc_records_storage_test.go
- flow/e2e/bigquery/bigquery_helper.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/snowflake/snowflake_helper.go
- flow/e2e/test_utils.go
- flow/go.mod
- flow/model/qrecord_batch.go
- flow/model/qrecord_test.go
- flow/model/qvalue/avro_converter.go
- flow/model/qvalue/qvalue.go
- flow/model/record_items.go
Rational numbers are awkward decimals,
using a decimal type for decimal data has a few benefits:
1. perf-wise decimal representation is a *big.Int & an int32 exponent (same as pgtype.Numeric), instead of 2 *big.Ints
2. decimal has obvious conversion to/from decimal strings,
whereas *big.Rat can be wonky going through FloatString
4. with scripting most people will want to use their decimal values as decimals, not decimal rationals
A side effect of this is that we now convert NaN/inf/-inf numerics to null. Previously they'd all get converted to NaN. This would only be usable for pg<->pg, only causing trouble with other peers, & even then we'd want inf/-inf to be properly translated
Fixes #1175
> Replace *big.Rat with shopspring decimal.Decimal

- flow/connectors/bigquery/bigquery.go
We were returning a wrong error object in BigQuery's merge
> BigQuery: Fix return mergeErr

- ui/app/peers/page.tsx
- ui/app/peers/peersTable.tsx
- ui/next.config.js
Now users do not land on the Home page. The landing route is the peers page (`/peers`), where if there are no peers, the below look holds:
> UI: Redirect to peers page by default, add buttons there

- ui/app/peers/page.tsx
- ui/app/peers/peersTable.tsx
- ui/next.config.js
> UI: New default page and peer buttons

- flow/workflows/sync_flow.go
Would cause activity to run on different worker, causing it to get stuck waiting for source connector
> fix SyncFlow getting stuck waiting for source connector

- flow/activities/flowable.go
When ReplicateQRepPartition fails for some reason midway after it's synced a bunch of partitions, it now enters a retry flow where it skims through partitions it's synced already, checking if they're synced and skipping if so. 
This process can take longer than the heartbeat for that activity (1 minute)
So we need to add heartbeats in this process to prevent heartbeat timeouts
> Add heartbeats to account for QRepPartitionIsSynced

- flow/connectors/postgres/client.go
was a bug, `SET LOCAL` has no effect outside transactions, can cause replication connections to close
> revert SET LOCAL in replconn hold

- ui/prisma/schema.prisma
Unnecessary columns in `cdc_batches` table in Prisma schema which were later moved to `cdc_batch_table`. This makes UI fail
> UI: remove columns mistakenly added for a stats table in prisma schema

- flow/activities/flowable.go
- flow/cmd/worker.go
- flow/workflows/sync_flow.go
Kevin noticed MaintainPull was outliving parent workflow for some time,
temporal contexts only detect cancelation with RecordHeartbeat,
in order to reduce shutdown latency implement UnmaintainPull
> Close replication connection faster

- flow/activities/flowable.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/eventhub/hubmanager.go
- flow/connectors/eventhub/scoped_eventhub.go
- nexus/Cargo.lock
- nexus/analyzer/src/lib.rs
- nexus/catalog/src/lib.rs
- nexus/flow-rs/src/grpc.rs
- nexus/parser/src/lib.rs
- nexus/pt/src/lib.rs
- nexus/server/src/main.rs
- protos/peers.proto
- ui/app/api/peers/getTruePeer.ts
- ui/app/api/peers/info/[peerName]/route.ts
- ui/app/api/peers/route.ts
- ui/app/dto/PeersDTO.ts
- ui/components/DropDialog.tsx
- ui/components/PeerComponent.tsx
- ui/components/PeerTypeComponent.tsx
This PR performs a redesign of our Eventhubs peer architecture on the core engine side. Create Peer UI is going to be a follow up PR to this.
`Eventhub` and `Eventhub Group` peers are **removed.** However `EventhubConfig` and `EventhubGroupConfig` are still in use.
A new peer - `Eventhubs` is the only peer related to this queue.
The `Eventhubs` peer is an extension of the earlier `EventhubGroup` peer, with it now having a list of `EventhubConfig`s.
You can create an `Eventhubs` peer via the SQL Layer as follows:
```sql
CREATE PEER eventhubs_peer_x FROM EVENTHUBS WITH (
eventhubs = '[{"subscription_id":"my-sub-id",
"resource_group":"myresource",
"namespace":"mynamespace-1",
"location":"eastus",
"partition_count":5,
"message_retention_in_days":2
},
{"subscription_id":"my-sub-id", …
```
> Eventhub peer refactor

- flow/cmd/peer_data.go
Removes a condition on one of the joins - `con.contype= 'p'` (primary key) for the query which we use to get tables for table picker
> TablePicker SQL Query: remove unnecessary filter

- flow/connectors/utils/partition/partition.go
This issue was noticed with tables where CTIDs are _not_ unique ex: partitioned tables
We adjust(increment) the start values of partitions after the first partition. This is to avoid overlapping partitions.
This was not done for TID columns because the assumption was that they would always be unique.
As a result, this could lead to duplication of rows for initial load and XMIN where CTIDs are the watermark column.
> QRep: Adjust start value for TID watermark column

- flow/activities/flowable.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/kafka/kafka.go
- flow/connectors/postgres/cdc.go
- flow/connectors/pubsub/pubsub.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/utils/avro/avro_writer.go
- flow/model/cdc_record_stream.go
- flow/peerdbenv/config.go
- flow/shared/atomic.go
Renamed from PEERDB_EVENTHUB_FLUSH_TIMEOUT_SECONDS
Efforts made in kafka/pubsub to prevent flush blocking processing more records
Removed unnecessary calls to HeartbeatRoutine, these calls really only belong in flowable.go
Adjusted max batch size logic so that setting max batch size above math.MaxInt32 prevents batches ever finishing
A follow up improvement could be that when `MaxBatchSize == math.MaxUint32` flush will insert a new sync batch record, but normalization will be disabled. But need to consider better how we want to integrate queues in UI when sync batches don't really make sense
> kafka/pubsub: PEERDB_QUEUE_FLUSH_TIMEOUT_SECONDS

- flow/connectors/eventhub/eventhub.go
- flow/connectors/eventhub/hub_batches.go
- flow/connectors/eventhub/scoped_eventhub.go
- flow/connectors/utils/partition_hash.go
- flow/go.mod
- flow/go.sum
When script is empty stick to existing eventhubs behavior
Script can return quite a bit as a table:
1. value: EventData Body
2. contentType: EventData ContentType
3. messageId: EventData MessageID
4. headers: EventData Properties
Destination can also be overriden:
1. destination: overrides mirror's destination table value. Following values will overwrite values from this string
2. namespace: can pick other namespaces, but pick from hub configs
3. partitionColumn: setting without `key` will use existing partition-by-column logic
4. key: sets partition key value, bypassing hashing & everything
5. hub: sets eventhub name
By having destination apply first, users can
```lua
return { destination = r.target, key = "override" }
```
causing behavior to adapt existing behavior set by their …
> Add scripting to eventhubs

- flow/cmd/handler.go
- flow/connectors/eventhub/eventhub.go
- ui/app/api/peers/route.ts
- ui/app/dto/PeersDTO.ts
- ui/app/mirrors/create/cdc/cdc.tsx
- ui/app/mirrors/create/cdc/tablemapping.tsx
- ui/app/mirrors/create/handlers.ts
- ui/app/peers/create/[peerType]/handlers.ts
- ui/app/peers/create/[peerType]/helpers/common.ts
- ui/app/peers/create/[peerType]/helpers/eh.ts
- ui/app/peers/create/[peerType]/page.tsx
- ui/app/peers/create/[peerType]/schema.ts
- ui/components/PeerComponent.tsx
- ui/components/PeerForms/Eventhubs/EventhubConfig.tsx
- ui/components/PeerForms/Eventhubs/EventhubGroupConfig.tsx
- ui/components/PeerForms/Eventhubs/schema.ts
- ui/components/PeerForms/PubSubConfig.tsx
- ui/components/SelectSource.tsx
This PR adds Eventhubs as a peer in UI.
- Includes form validation
- Helper text
It also adapts the CDC create mirror page for Eventhubs.
- Info on target table semantics for Eventhub
- Automatically turns off and does not display initial load related and soft delete settings
> UI: Create Eventhub Peer and Eventhub Mirror

- flow/concurrency/bound_selector.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/test_utils.go
- flow/workflows/snapshot_flow.go
BoundSelector is only used by table cloning
Selector does some juggling so that Select waits on all futures, changing BoundSelector to use Selector avoids pathological cases
Imagine parallelism is 4. The time to clone tables is as follows: 15m 1m 2m 3m 4m 5m
Currently, cloning will take 20m (waits for 15m at 4m, then immediately adds 4m & 5m)
Optimally, cloning would take 15m. 4m would start after 1m & another minute later 5m would start
> Use Selector in BoundSelector to wait in parallel

- flow/connectors/bigquery/bigquery.go
- flow/connectors/snowflake/snowflake.go
This PR quotes column names for the insert into select command in RenameTables activity for Snowflake and BigQuery. A column with name 'rows' would make the query fail due to it being a reserved keyword. This PR fixes that
> Resync for SF and BQ: Quote column names for RenameTables

- .github/workflows/ci.yml
- .github/workflows/ui-build.yml
Originally kept mandatory because this CI item was required
> CI: skip nexus tests unless nexus/protos updated

- ui/app/mirrors/[mirrorId]/cdcDetails.tsx
- ui/app/mirrors/[mirrorId]/rowsDisplay.tsx
- ui/app/mirrors/[mirrorId]/syncStatus.tsx
Seems like 'us' is not a valid locale string for `Intl.NumberFormat()`. Noticing different results across systems for the same number.
Changing to `en-US` which is a more well documented choice.
Also switches another instance of number formatting to use `Intl` APIs instead of regex
Also use total rows as sum of rows in batch instead of inserts/updates/deletes
> UI Row display formatter: use en-US

- flow/connectors/bigquery/bigquery.go
- flow/connectors/clickhouse/cdc.go
- flow/connectors/snowflake/snowflake.go
This PR:
- Deletes (if not exists) raw table for snowflake
- Adds sync flow cleanup method for clickhouse (same as above)
- Deletes (if not exists) raw table for bigquery thereby fixing drop mirror for Qrep BQ mirrors
> Better sync flow cleanup

- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_sql_sync.go
- flow/e2e/postgres/qrep_flow_pg_test.go
Overwrite mode was using the sync records branch for Upsert, which expects unique key columns. It failed there.
This PR fixes this by making it use the append branch. It also moves the truncate step to this branch from setup flow, since after the first sync, qrep flow continues as new, enters setup flow again where it would truncate what it just synced even though no new rows were ingested necessarily
Automated test added
> Fix PG-PG QRep Overwrite

- flow/connectors/bigquery/bigquery.go
- flow/dynamicconf/dynamicconf.go
This PR adds support for partitioning the target tables we create in BigQuery mirrors by the `_PEERDB_SYNCED_AT` column, by **days**
This feature is gated by a dynamic configured env variable - `PEERDB_BIGQUERY_ENABLE_SYNCED_AT_PARTITIONING_BY_DAYS`
> BigQuery: add flag-gated time partitioning

- flow/activities/flowable.go
- flow/connectors/postgres/cdc.go
- flow/connectors/snowflake/qrep.go
- flow/workflows/qrep_flow.go
Logs in PullRecords and ConsolidatePartitions were missing the flow name key.
Added values to context in activity for the latter
For PullRecords, `p.logger` (and p.PostgresConnector.logger) for some reason does not print flow name even though it takes from loggerfromctx where ctx should have the flowName key. Using loggerfromctx in the pullrecords function explicitly instead, does print it
> Add missing flow name keys to some logs

- ui/app/mirrors/status/qrep/[mirrorId]/page.tsx
- ui/app/mirrors/status/qrep/[mirrorId]/qrepStatusTable.tsx
Bug in one of the qrep tables where run uuid was removed from the fetch but the column was still in the table causing the table headers to be mismatched. This PR fixes this
> UI Partitions table: remove extra column

- ui/app/mirrors/[mirrorId]/snapshot.tsx
- ui/app/mirrors/[mirrorId]/snapshotTable.tsx
This PR splits the initial load table in the mirror page into two - completed and in progress
> UI: split initial load table into 2

- flow/connectors/utils/cdc_store.go
Turns out cumulative in /gc/heap/allocs:bytes description means monotonic over lifetime of program
> CdcStore: use /memory/classes/heap/objects:bytes

- flow/pua/peerdb.go
- flow/pua/peerdb_test.go
Also implement __json/__msgpack methods on arrays to always serialize as arrays,
avoids having to check `string.sub(kind, 1, 6) == 'array_'` in scripts
> lua: peerdb.LuaRowTable

- flow/connectors/bigquery/qrep.go
- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/qrep_sql_sync.go
- flow/connectors/s3/qrep.go
- flow/connectors/snowflake/avro_file_writer_test.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/sql/query_executor.go
- flow/connectors/utils/avro/avro_writer.go
- flow/connectors/utils/stream.go
- flow/e2e/bigquery/bigquery_helper.go
- flow/model/conversion_avro.go
- flow/model/qrecord_batch.go
- flow/model/qrecord_stream.go
- flow/model/qvalue/qschema.go
There was no fallible case
SchemaChan pulling the schema was incompatible with calling Schema,
take a page from context.Context `chan struct{}`
With this schemaSet can be relied on, allowing schema to be non nullable
> Remove QRecordSchemaOrError

- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/utils/avro/avro_writer.go
- flow/connectors/utils/stream.go
- flow/model/qrecord_batch.go
- flow/model/qrecord_stream.go
Errors are non recoverable, indicating end of stream
Match existing APIs which have an Err method which should be checked after iteration
> Remove QRecordOrError

- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/qrep_sql_sync.go
- flow/connectors/utils/monitoring/monitoring.go
- flow/shared/postgres.go
1. `context.Background()` was being used in PG qrep destination in some places instead of the dedicated context
2. defer functions should not use context passed in, as the defer could have run due to context cancellation and so the defer will be useless. Primarily for pg tx rollbacks
> fixed some context usages in PG connector

- ui/app/peers/create/page.tsx
- ui/app/utils/titlecase.ts
- ui/components/SelectSource.tsx
Reduces clicks, with dropdown it's:
1. click dropdown
2. scroll list
3. click peer type
4. click create
Now user only needs one click
> UI Create Peer: replace drop down with columns of buttons

- ui/app/peers/[peerName]/lagGraph.tsx
Slot is only sampled every 5 minutes, pointless to view less than an hour
> Slot lag graph: don't show 1min/5min/15min options

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/qrep.go
- flow/connectors/clickhouse/cdc.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/postgres_schema_delta_test.go
- flow/connectors/snowflake/get_schema_for_tests.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/qrep_avro_consolidate.go
- flow/connectors/snowflake/snowflake.go
- flow/datatypes/numeric.go
- flow/e2e/snowflake/snowflake_schema_delta_test.go
- protos/flow.proto
This PR alters the DeltaAddedColumn proto file to now have one field - `Columns` of type FieldDescription, so that we now possess type modifier information.
This is then used to achieve creation of numerics with specified precision and scale in `ReplayTableSchemaDeltas` for Snowflake, like we do in `SetupNormalizedTable`
Test has been adapted for Snowflake
> Snowflake: Addition of dynamic numeric columns

- flow/activities/flowable_core.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/kafka/kafka.go
- flow/connectors/postgres/cdc.go
- flow/connectors/pubsub/pubsub.go
- flow/model/model.go
This is particularly important for queues, as to reduce reconnections long sync batches are desirable
> Queues: communicate flushes back to source in order to keep slot size down

- ui/app/mirrors/create/cdc/cdc.tsx
- ui/app/mirrors/create/cdc/fields.tsx
- ui/app/mirrors/create/helpers/cdc.ts
- ui/app/mirrors/create/helpers/common.ts
Adds a switch field in create CDC UI  for opting for pg type system - for source and destination set to Postgres peers.
> UI for opting into PG type system

- flow/connectors/connelasticsearch/elasticsearch.go
- flow/connectors/postgres/qrep.go
better logs mostly
DO NOT DELETE THIS BRANCH AFTER MERGING
> mainlining forage changes

- flow/connectors/connelasticsearch/elasticsearch.go
Currently for the error type `illegal_argument_exception` that contains the error when a index has "too many documents" which is an underlying Lucene limitation. Limit is 2b per Lucene shard.
Needs to be addressed better for ES in the future.
> error workflow in specific ES error

- flow/alerting/alerting.go
- flow/cmd/handler.go
- flow/cmd/validate_mirror.go
- flow/cmd/validate_peer.go
- flow/shared/telemetry/event_types.go
- flow/shared/telemetry/sns_message_sender.go
- Add new methods in `alerting.go` for different telemetry levels for non-flow events
- Integrate these methods in `handler.go`, `validate_mirror.go` and `validate_peer.go` to log warnings during validate_peer and validate_mirror
- Add new event types in `event_types.go` for telemetry
TODOs:
> feat(alerting): enhance telemetry logging

- ui/app/mirrors/[mirrorId]/configValues.ts
- ui/components/EditButton.tsx
- ui/components/MirrorActionsDropdown.tsx
- ui/components/PauseOrResumeButton.tsx
- ui/components/ResyncDialog.tsx
Resync dialog box was instantly disappearing. 
Simplified the mirror actions dropdown component to fix this
Remove tooltip for edit button as it was causing issues with width. Indicate pause neccessity with text instead
also remove staging path info in View More modal
> Fix mirror actions dropdown

- ui/app/mirrors/create/handlers.ts
- ui/app/mirrors/create/page.tsx
For append and upsert modes in qrep, we need start and end placeholders for partitioning. this PR adds validation and explanation text for this
> UI: check for start and end existence for qrep

- flow/connectors/clickhouse/qrep_avro_sync.go
Gets CH QRep append working by skipping the sign column for the final insert into select
> Fix Clickhouse QRep Append

- flow/connectors/bigquery/bigquery.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- ui/app/mirrors/create/cdc/cdc.tsx
- ui/app/mirrors/create/helpers/cdc.ts
- Add fields for synced_at and soft delete column names in UI under advanced section. 
- These are visible for BQ and SF destinations for now
- Fix default soft delete false for BQ CDC
> Add peerdb columns to ui, fix for BQ

- flow/connectors/postgres/postgres.go
GetTableSchema of SetupFlow can take a long time for a large number of tables, leading to activity heartbeat timeouts. This PR adds a heartbeat after fetching schema for each table
> Add heartbeat for gettableschema

- nexus/analyzer/src/lib.rs
- nexus/analyzer/src/qrep.rs
- nexus/catalog/src/lib.rs
- nexus/flow-rs/src/grpc.rs
- nexus/peer-mysql/src/ast.rs
- nexus/server/src/main.rs
- nexus/server/tests/server_test.rs
1. also remove CAST from OFFSET
2. remove explicit `public` schema. Needed for UDF passthrough
3. `jsonb` isn't in MySQL, so rewrite '...'::jsonb literals, in particular mapping [1,2,3] to array for StarRocks
This can be leveraged to use array functions in StarRocks:
```sql
CREATE OR REPLACE FUNCTION public.cardinality(jsonb)
RETURNS int AS $$
BEGIN
RETURN jsonb_array_length($1);
END
$$
LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION public.array_intersect(jsonb, jsonb)
RETURNS jsonb AS $$
BEGIN
RETURN (select jsonb_agg(a) from jsonb_array_elements($1) a join jsonb_array_elements($2) b on a = b);
END
$$
LANGUAGE PLPGSQL IMMUTABLE;
-- where postgres_fdw is specified in `extensions` option of fdw server
ALTER EXTENSION postgres_fdw ADD FUNCTION public.cardinality(jsonb);
ALTER …
```
> More MySQL rewrite rules

- flow/connectors/bigquery/bigquery.go
BigQuery has a [quota](https://cloud.google.com/bigquery/quotas#standard_tables) of 5 metadata update operations per table per 10 seconds. So currently if many columns are added in a PG to BQ CDC mirror, sync records fails with this error from BigQuery - even though we do `ADD COLUMN IF NOT EXISTS` (it still counts as an update operation)
This PR accounts for this by manually checking the table metadata for the column before adding it. This will atleast ensure that on sync flow retry, the remaining columns get added
> BigQuery Add Column: Account for update limit

- flow/cmd/validate_mirror.go
- ui/app/mirrors/create/handlers.ts
- ui/app/mirrors/create/helpers/common.ts
- ui/app/mirrors/create/helpers/qrep.ts
- Fix XMIN validation
- Change label to Create Watermark Table on Destination, and make it false by default
- Catch putting existing mirror name in UI
> Changes for Create Mirror

- dev-peerdb.sh
- docker-compose-dev.yml
- docker-compose.yml
- run-peerdb.sh
use an explicit external network this removes environment related problems that can cause problems with quickstart.
Also remove multiple flow workers in the default configuration
> Improve default docker compose

- flow/cmd/validate_mirror.go
Ensure mirror name validation is bypassed for query layer (where flow job entry happens before hand) and resync (where mirror name has to be the same)
> API: Fix mirror name validation for query layer, resync

- flow/connectors/utils/monitoring/monitoring.go
- flow/connectors/utils/stream.go
- flow/model/qrecord_stream.go
- flow/model/record.go
Race existed with parallel queue processing
> PopulateCountMap: use atomics

- dev-peerdb.sh
- docker-compose-dev.yml
- docker-compose.yml
- run-peerdb.sh
1. `run-peerdb.sh` should now support Podman too (needs to be tested)
2. implict network creation, check not needed
3. misc things to script
> Docker + run scripts minor fixes

- flow/cmd/handler.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- ui/app/mirrors/create/cdc/cdc.tsx
Removes upper casing of user-provided peerdb column names in handler.go for create cdc and qrep endpoints
Restrict custom names for these columns to just bigquery in UI
Functionally tested with soft delete
Added a custom name for these columns in a BQ test
> Remove forced upper case for peerdb columns

- flow/connectors/clickhouse/qrep_avro_sync.go
This PR tweaks the insert into select queries of clickhouse qrep to account for lower clickhouse versions where session token as an argument is not supported for the s3() table function.
https://github.com/ClickHouse/ClickHouse/issues/61230
> Clickhouse insert-select: account for lower version

- flow/cmd/peer_data.go
- Let's not list partitioned tables as what matters is the root table
- Fix duplicate columns showing in the table picker
> UI: Better table picker data

- ui/app/mirrors/create/cdc/cdc.tsx
This PR fixes a bug where replication slot name field was not respected for PG to queues. Functionally tested
> UI: Fix replication slot field for queues

- flow/datatypes/numeric.go
For bigquery we were checking for numeric scale being < precision, also need to make sure it is less than 20 as that is the scale we set for bignumeric in bq
> Numeric: fix scale check for bqnumeric

- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/clickhouse/qrep_avro_sync.go
Adds 
```
max_memory_usage
max_block_size
max_insert_threads
max_insert_block_size
```
> Stilgar: Add Clickhouse query level settings

- flow/activities/flowable.go
- flow/cmd/worker.go
- flow/connectors/core.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/go.mod
- flow/go.sum
- flow/otel_metrics/otel_manager.go
- flow/otel_metrics/peerdb_guages/attributes.go
- flow/otel_metrics/peerdb_guages/guages.go
- flow/otel_metrics/sync_gauges.go
- flow/workflows/scheduled_flows.go
- stacks/flow.Dockerfile
This is accomplished by clearing out the metric from the MetricsMap once Observed/Collected.
Use a query like:
```
max(peerdb_cdc_slot_lag_MB{}) without(k8s_pod_name, k8s_pod_uid, k8s_pod_ip, k8s_pod_start_time, k8s_node_name)
```
to deduplicate metrics across pods, they are only pushed once in 1 cycle in a pod
TODO:
> fix: duplicate metrics pushed via otel sdk

- flow/connectors/postgres/postgres.go
Ensure we get nice interval values when reading rows in cdc
functionally tested by switching to iso_8601 and back during cdc
> Add intervalstyle to replconfig map

- ui/app/mirrors/create/handlers.ts
Before we were setting initial load off for queues in handler
With #1675 and #1683, these steps aren't required
> UI for queues: remove queue specific setting handling 

- flow/connectors/bigquery/qrep_avro_sync.go
- flow/datatypes/bigint.go
- flow/datatypes/bigint_test.go
- flow/datatypes/numeric.go
- flow/model/qvalue/avro_converter.go
- flow/model/qvalue/dwh.go
Some fixes related to numerics.
- `.Round()` can turn a value like `999999....dot 99999...` to `1000...`. Changed this to `.Truncate`
- Included bigquery too for the snowflake specific steps in `processNumeric`
- Moved code snippets to functions
Functionally tested for BigQuery initial load
> Numeric: refactoring and truncate for BigQuery

- flow/connectors/utils/aws.go
- ui/app/peers/create/[peerType]/helpers/s3.ts
- ui/app/utils/gcsEndpoint.ts
- ui/components/PeerForms/S3Form.tsx
Environment variable for the Endpoint field for the S3 peer would not be used if access key id etc were set from UI. Thus we need a field for Endpoint in UI
Also adds empty string checks for roleArn
> S3: add endpoint field to UI

- flow/connectors/postgres/postgres.go
For a large number of tables in the mirror, when schema fetching for one of the tables fails, the top level caller of `getTableSchema` logs the error which can be too big to log, yielding a temporal message:
```
Complete result exceeds size limit
```
This PR adds a log so that we know which table schema fetch failed
> Add error log for fetch table schema

- flow/connectors/clickhouse/cdc.go
- flow/connectors/clickhouse/qrep_avro_sync.go
This function call is not actually used downstream and is an unnecessary call to clickhouse
> Clickhouse: remove gettableschema step in cdc

- flow/activities/flowable.go
- flow/cmd/handler.go
- flow/connectors/utils/peers.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/workflows/cdc_flow.go
Implement the reloadPeers function to support the edit peer functionality. When a flow is paused and resumed, reload the latest peer details for both the source and destination peers. This ensures that any changes made to the peer configuration during the pause are picked up when the flow resumes execution.
> feat(cdc): reload peers on flow resume

- flow/connectors/snowflake/snowflake.go
CURRENT_TIMESTAMP returns timestamp in local timezone which can be misleading when inspecting `peerdb_synced_at` values on Snowflake. SYSDATE() gives it in UTC
https://docs.snowflake.com/en/sql-reference/functions/sysdate
> Snowflake: use sysdate() for peerdb synced at

- flow/connectors/clickhouse/clickhouse.go
Clickhouse connections need to stay open for long running queries. The default values of timeouts being low is resulting in our queries to clickhouse in mirrors to fail with I/O timeout errors
This PR sets a safe 1 hour timeout for dialing and reading, which has helped recover mirrors in above cases
> Read and dial timeouts of 1 hour for clickhouse

- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/snowflake.go
This commit adds query tags to the Snowflake connector for the most frequently executed and expensive queries that contribute significantly to the overall cost. The tags are added using the `withMirrorNameQueryTag` method, which sets a tag with the format `peerdb-mirror-<flowJobName>` for each query.
Query tags have been added to key methods:
- `SyncRecords`
- `NormalizeRecords`
- `CreateRawTable`
- `SyncFlowCleanup`
- `SyncQRepRecords`
- `SetupQRepMetadataTables`
- `ConsolidateQRepPartitions`
These methods cover core functionality of syncing, normalizing, and managing QRep tasks. The tags will help identify and track the most expensive queries in the Snowflake web interface or using the `QUERY_HISTORY` table.
Some minor queries have been ignored to focus on the most impactful areas. The …
> Add query tags for Snowflake connector to track most expensive queries

- flow/connectors/clickhouse/cdc.go
- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/clickhouse/normalize.go
- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/connectors/clickhouse/s3_stage.go
- flow/connectors/utils/avro/avro_writer.go
- nexus/catalog/migrations/V27__ch_s3_stage.sql
- nexus/catalog/migrations/V28__ch_s3_stage_unique_constraint.sql
Move bulk of the operations to normalize, `syncRecords` will just push to S3, and free up PostgreSQL replication slot faster.
> ClickHouse Enhancement: Faster replication slot flush

- .github/workflows/flow.yml
- flow/connectors/postgres/qrep.go
You can't have tables be `TEMP` and `UNLOGGED` apparently, both lead to no WAL being written.
Removed schema as temporary tables go to a temporary schema as well.
> PG upsert create table fix

- flow/connectors/snowflake/client.go
- flow/connectors/snowflake/snowflake.go
This PR accounts for mixed case table name in Snowflake's RenameTables()
> SF RenameTables: fix for mixed case

- flow/workflows/qrep_flow.go
replicateQRepPartition activity settings:
- heartbeat timeout: increase to 5 minutes. We do heartbeat in the activity but 1 minute is too close
- maximum retry interval to 10 minutes instead of 1 hour.  An error in qrep can soon lead to having to wait for an hour to see a fix resolve the mirror
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> ReplicateQRepPartitions: Tweak activity params

- ui/app/mirrors/create/cdc/schemabox.tsx
- ui/app/mirrors/create/cdc/schemasettings.tsx
- ui/app/mirrors/create/handlers.ts
The rationale here is that editing the schema individually is not an ideal experience.
- Added `SchemaSettings` component for modifying target schema.
- Introduced `defaultTargetSchema` state to manage target schema.
- Implemented `fetchTablesForSchema` function to handle table fetching with the target schema.
- Modified `fetchTables` function to accept `targetSchemaName` parameter.
- Updated table row handling to use `value` instead of `defaultValue` for destination inputs.
- Improved schema box initialization with `useEffect` to fetch tables based on `defaultTargetSchema`.
> feat(cdc): enhance schema box with schema settings and target schema

- flow/connectors/bigquery/bigquery.go
When handling soft deletes, we perform equality checks for primary key columns in _resync and original tables. For a replica identity full table, we mark all columns as primary keys.
If one of the columns in that case is a JSON, `=` comparison fails. Need to use TO_JSON_STRING instead like how we do for merge.
> BigQuery rename tables: account for json column in replica identity full table

- ui/app/mirrors/create/qrep/qrep.tsx
When the watermark/source table changed, we had logic to reset the destination table name to the watermark table name. This was done improperly, causing a desync between the displayed value to the user and the actual value in config that the mirror is created with.
Fixed by removing the logic entirely, users should manually change the table if watermark table is updated after destination table.
> UI: fix dst table overwrite in QRep mirror creation

- docker-compose-dev.yml
- docker-compose.yml
1. `version` is apparently obsolete.
2. minio to latest, complains after a while otherwise
> minor docker fixes

- flow/connectors/postgres/ssh_wrapped_pool.go
in cases where provided host is only resolvable on the bastion
> pgx: custom LookupFunc during SSH tunneling to delegate DNS lookup

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/merge_stmt_generator.go
- flow/connectors/bigquery/qvalue_convert.go
- flow/e2e/bigquery/peer_flow_bq_test.go
Refactors `qvalue_convert.go` to now use `bigquery.FieldSchema` and not `FieldType`. No need to rely on hacks like `IsArray` while creating tables
Functionally tested with cdc and schema change of array
> BigQuery: better type handling

- flow/connectors/postgres/qrep_query_executor.go
Couldn't see where this is being called/used
> remove an unused function from qrep query executor

- flow/connectors/postgres/sanitize/sanitize.go
- flow/e2e/postgres/peer_flow_pg_test.go
pgvalue cdc initial load was breaking due to sanitize not supporting ctid args
> sanitize: support pgtype.TID

- ui/app/mirrors/[mirrorId]/configValues.ts
- ui/app/mirrors/[mirrorId]/page.tsx
- ui/app/mirrors/create/cdc/cdc.tsx
- ui/app/mirrors/create/qrep/qrep.tsx
1. soft delete toggle is only available for BQ, SF and PG destinations since other peers have issues.
2. Resync is only enabled when mirror is running or paused.
3. Watermark column dropdown only displays supported types (currently 5)
4. Publication name is now visible in CDC mirrors status page, if empty in config filling using default publication name
Closes #1778, #1777 and #1767
> fixing misc UI issues

- flow/model/record_items.go
When we truncate jsons for abiding by the avro size limit, we set it to empty string, which is not a valid json. Instead set it to empty object. 
An issue was seen due to this in BigQuery merge statement where parse_json fails
> Avro JSON size limit based truncation: make it empty object

- flow/workflows/cdc_flow.go
Currently, when we add a table to a mirror which has been resynced (therefore the mirror config has resync = true), the add tables flow inherits the resync = true property and so tries to "resync" the added tables, which fails at the soft delete handling step as the table was never pre-existing on target
This PR sets resync to false for add tables flow
> Fix addition of tables to a resynced mirror

- flow/cmd/handler.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/merge_stmt_generator.go
- flow/connectors/bigquery/merge_stmt_generator_test.go
- flow/connectors/postgres/normalize_stmt_generator.go
- flow/connectors/postgres/normalize_stmt_generator_test.go
- flow/connectors/snowflake/merge_stmt_generator.go
- flow/connectors/snowflake/merge_stmt_generator_test.go
- flow/connectors/snowflake/snowflake.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/workflows/cdc_flow.go
- nexus/analyzer/src/lib.rs
- nexus/flow-rs/src/grpc.rs
- nexus/pt/src/flow_model.rs
- protos/flow.proto
- ui/app/dto/MirrorsDTO.ts
- ui/app/mirrors/create/handlers.ts
- ui/app/mirrors/create/helpers/cdc.ts
- ui/app/mirrors/create/helpers/common.ts
- ui/app/mirrors/create/qrep/upsertcols.tsx
- ui/app/mirrors/types.ts
- ui/components/ResyncDialog.tsx
closes #1803 
makes all soft delete logic now depend on not empty column name, fasttrack to removing it entirely
> added option to disable all PeerDB columns

- flow/workflows/qrep_flow.go
We are seeing cases where getting min, max, count and partitions can take well over 5 hours
Also apply the same settings as replicateQrepPartition: make sure we dont have 1 hour wait for retry
> GetQRepParts: increase activity startToClose timeout, retry max interval

- flow/peerdbenv/dynamicconf.go
- flow/workflows/cdc_flow.go
- flow/workflows/local_activities.go
- nexus/catalog/migrations/V31__more_more_dynconf_settings.sql
currently limit to 64, need to raise SyncFlow's restart threshold otherwise
> dynamically configure number of syncs per CDC flow

- flow/cmd/peer_data.go
```
t.relispartition IS NOT TRUE ORDER BY t.relname, can_mirror DESC;
```
this is so that we only show the root table as we use publish_via_partition_root
> UI: Fix display of partitioned tables

- flow/alerting/slack_alert_sender.go
- ui/app/alert-config/new.tsx
- ui/app/alert-config/validation.ts
Adds a Members field in UI where you can add comma separated slack usernames to tag in the channel. If left empty, tags the whole channel
Also adds a guide to slack alerting in the alerts UI
Functionally tested:
> Slack alerts : can now specify members to tag in the channel

- flow/connectors/postgres/client.go
- flow/connectors/postgres/validate.go
This reverts commit 0923a68f3139b3347864bb258c6fd7091fad96b4.
Faced an issue with a customer instance where this check was throwing errors but SetupFlow passed successfully on removing the check. 
This blocks mirror creation so getting the reversion in first and then will re-apply the feature fixed
> Revert "Add primary key check for validate mirror (#1773)"

- flow/connectors/utils/stream.go
- flow/model/record_items.go
Ideally we'd handle base64/hex instead of binary strings, but this does the bad thing faster
> model toMap: encode to binary faster

- flow/cmd/handler.go
- flow/cmd/mirror_status.go
- flow/shared/constants.go
- flow/workflows/cdc_flow.go
- flow/workflows/qrep_flow.go
https://pkg.go.dev/go.temporal.io/sdk/client upgrade to v1.27.0 introduced a mandatory field while doing external workflow updates called `WaitForStage`, which is currently experimental,  underdocumented and is breaking our uses of external updates.
Need to find a better fix later, for now removing the update handlers entirely from code. We only have one currently, for setting workflow status to PAUSING or TERMINATING.
> fix update handler breaking with Temporal update

- flow/cmd/handler.go
- flow/cmd/mirror_status.go
- flow/shared/string.go
- protos/route.proto
- ui/app/mirrors/[mirrorId]/cdcDetails.tsx
- ui/app/mirrors/[mirrorId]/page.tsx
- ui/app/mirrors/[mirrorId]/qrepStatusButtons.tsx
- ui/app/mirrors/[mirrorId]/snapshotTable.tsx
- ui/app/utils/flowstatus.ts
Fix link in snapshot status table
Account for mirrorId being a clone job name instead of a regular name in the mirrors page.
Add logs for mirror status and flow state change endpoints
Functionally tested with initial load and qrep
Also improved UI a little bit on qrep page
> Fix broken link for UI initial load table, add more logs in backend

- flow/connectors/postgres/postgres.go
If mirror jobs table is not even there then that satisifies the step of deletion of job entry in that table
> pg-pg drop mirror: check jobs table existence first

- flow/cmd/peer_data.go
- flow/connectors/postgres/postgres.go
Noticed an issue where drop publication if exists fails with something along the lines of being unable to perform drop publication in a read only transaction
Manually checking the publication existence first should bypass the issue. Need to do some functional testing
> Postgres: Fix pull cleanup

- ui/app/mirrors/create/handlers.ts
- IsSchemaLessPeer -> changed to be a function ValidSchemaQualifiedTarget 
- Adds a check for this in CDC
Functionally tested for all target peers - CDC and QRep
> UI: Refactor schema qualification check

- flow/connectors/kafka/kafka.go
- flow/connectors/pubsub/pubsub.go
- flow/connectors/utils/lua.go
WithCancelCause ctx.Err() returns context.ErrCancelled,
need to call context.Cause to return cause,
context.Cause returns ctx.Err when cause function not cause of context done
This was preventing scripting errors from bubbling into mirror logs
> use context.Cause

- flow/cmd/mirror_status.go
Initial load UI for PG -> PG and SF would not load because dots weren't replaced with underscores for clone name
This PR does the equivalent of our shared code which is used for clone name construction:
```golang
// shared/string.go
var (
reIllegalIdentifierCharacters = regexp.MustCompile("[^a-zA-Z0-9_]+")
...
)
func ReplaceIllegalCharactersWithUnderscores(s string) string {
return reIllegalIdentifierCharacters.ReplaceAllString(s, "_")
}
```
in the clone query:
```sql
WHERE qr.flow_name ^@ ($1||regexp_replace(qr.destination_table, '[^a-zA-Z0-9_]', '_', 'g'))
```
> API clone summary: replace illegal chars in clone query

- flow/activities/flowable_core.go
Syntax error with "ON" usage in 
```
WHERE p.type = $1 AND EXISTS(SELECT * FROM flows f ON p.id = f.source_peer)
```
should be WHERE
> Fix syntax for getting postgres peer in Walheartbeat

- .github/actions/genprotos/action.yml
rest of our caching is handled by dependencies,
but that means we get 10GB free just for generated protobuf files
> replace actions/cache with ubicloud/cache

- flow/model/model.go
- flow/model/model_test.go
For a JSON column whose name matches one of its keys in one of its objects, our unnesting logic unnests the fields and then deletes the key with the column name, thereby overwriting and then deleting this one field.
This PR fixes and adds a test for it
> Unnest columns: edge case fix

- nexus/Cargo.lock
- nexus/catalog/src/lib.rs
- nexus/flow-rs/Cargo.toml
- nexus/pt/Cargo.toml
after this only remaining dependency on hyper 0.14 is yup-oauth2, which'll be addressed with next gcp-bigquery-client version
> tonic 0.12

- ui/app/mirrors/create/handlers.ts
We do not display initial copy setting for eventhubs in UI yet as it is yet to be supported, but the default of that setting is true. This PR sets it to false in case of an Eventhubs mirror
> UI: no initial copy for eventhubs mirror

- ui/app/mirrors/[mirrorId]/configValues.ts
- ui/app/mirrors/create/cdc/cdc.tsx
- ui/app/mirrors/create/handlers.ts
- ui/app/mirrors/create/helpers/cdc.ts
- ui/app/mirrors/create/helpers/qrep.ts
- ui/app/mirrors/create/qrep/qrep.tsx
- Bunch of settings (soft-delete, pg type system etc.) were not showing up in create cdc mirror UI - now these are restored
- Staging path fields shown only for BQ and SF targets
- Fix 'parallel tables' typo -> parallel workers
> UI: Fix enum comparisons, remove fluff

- .github/workflows/stable-docker.yml
Stable docker image workflow: Allows tags like v0.13.1a where the ending part can have alphabets
> Github actions: change stable tag regex

- ui/app/peers/create/[peerType]/helpers/ch.ts
In the clickhouse peer UI form, change the default textfield value of the Port field to `9440` instead of `9000`
> Clickhouse peer UI: change default port to 9440

- flow/connectors/clickhouse/cdc.go
- flow/connectors/clickhouse/clickhouse.go
In Clickhouse's RenameTables, we need to set the synced_at column of the resynced table to the current time.
Research suggests that using now() along with allowing non deterministic mutations in Clickhouse could be expensive and also lead to inaccuracies
This PR calculates the current timestamp in Go and substitutes it in the alter update command.
> Clickhouse resync: use Go time.now for setting synced_at column

- .github/workflows/stable-docker.yml
Technical difficulties with new tag-based image releases necessitates this PR which changes the regex for the stable docker image workflow file to an earlier value
> Actions: Revert to old stable docker image regex

- flow/connectors/clickhouse/clickhouse.go
Seems like in some versions/setups of Clickhouse, alter add column is altogether not supported for engine memory. Use mergetree instead when validating
> Clickhouse: use mergetree instead in validation

- docker-compose-dev.yml
- docker-compose.yml
- stacks/peerdb-server.Dockerfile
1. crates.io now defaults to sparse protocol, remove env
2. tagging a particular MinIO version
3. need extra_hosts for MinIO to work on Linux since `host.docker.internal` isn't the default address there
> docker fixes

- ui/app/mirrors/create/cdc/cdc.tsx
For Clickhouse mirrors in create CDC mirror UI, do not show the script field
> CH Mirror: no script field

- docker-compose-dev.yml
- docker-compose.yml
- ui/app/api/mirror-types/validation/scripting/route.ts
- ui/app/mirrors/create/cdc/cdc.tsx
- ui/peerdb-env/experimental_enable_scripting.ts
`PEERDB_EXPERIMENTAL_ENABLE_SCRIPTING` has been introduced in the docker compose files. Default is true in the docker-compose files.
The code checks if the var is true and true only so if not specified, it will be taken as false
> Add env var for scripting

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/clustering.go
When clustering the tables in `SetupNormalize` for BigQuery we must account for: https://cloud.google.com/bigquery/docs/clustered-tables#cluster_column_types
> BigQuery: check if pkeys can be used for clustering

- flow/cmd/validate_mirror.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/validate.go
This PR adds validation in create mirror for creating a publication when no publication is selected.
Refactored existing publication creation code into a common function used by setup flow and validate mirror
> Validate publication via create and drop

- flow/activities/flowable_core.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/test_utils.go
- flow/shared/postgres.go
1. `replState changed` is usually after something else happened, so no need to alert on its own
2. `slot is active` is annoyingly common, it autorecovers, don't alert
> don't alert for some common errors

- .github/workflows/ci.yml
- .github/workflows/flow-api-client.yml
Avoids having to include generated files in PRs, isolating them to a branch
Once this is validated & downstream updates to new module path, generated files can be removed from main
> Generate flow-api-client changes to its own branch

- flow/shared/schema_helpers.go
This PR includes nullableEnabled when building the tableschemamapping for setupNormalize.
Seems like this one wiring was missed for the nullable setting
> SetupNormalize: fix enable nullable

- flow/connectors/utils/peers.go
- nexus/peer-mysql/src/ast.rs
Avoids postgres_fdw enriching queries with syntax MySQL doesn't allow since MySQL timestamps always have tzinfo
DateTime is also the more suitable time type in MySQL, & StarRocks only has DateTime
> mysql: remove WITH TIMEZONE / WITHOUT TIMEZONE syntax from casts

- flow/cmd/peer_data.go
- flow/cmd/validate_mirror.go
- flow/connectors/postgres/validate.go
- protos/route.proto
- ui/app/mirrors/[mirrorId]/edit/page.tsx
- ui/app/mirrors/create/cdc/cdc.tsx
- ui/app/mirrors/create/cdc/schemabox.tsx
- ui/app/mirrors/create/cdc/tablemapping.tsx
- ui/app/mirrors/create/handlers.ts
If initial load only is selected in UI, allow non-mirrorable tables to be synced, and validation will not check replication and publication related things.
One item I tried was also allowing excluding primary key columns when initial load only is selected, but seems like this requires some refactoring on the pull side. Could do it in this PR or follow up
> Adapt validate mirror for initial load only

- flow/activities/flowable.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/clickhouse/cdc.go
- flow/connectors/clickhouse/normalize.go
- flow/connectors/core.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/connectors/snowflake/snowflake.go
- flow/workflows/qrep_flow.go
- flow/workflows/setup_flow.go
- protos/flow.proto
Resync is becoming an increasingly utilized feature. Users of our connectors, particularly Clickhouse, sometimes wish to make small table definition changes on target or source and then want to repopulate data. This is alongside the usual recovery use-cases of resync.
`RenameTables` (or resync in general) currently can fail in the following ways:
1. If, between original mirror kick off and resync, a column was added to the table and a row not inserted after, then that column would not have been added to the target via schema changes. In this case, upon resync, the `_resync` table and the original table have different schemas, causing the soft-delete transfer step to fail. This can then lead to:
2. It processes some tables but not all and hits a failure - upon retrying it tries to resync …
> Make resync more reliable for warehouse connectors

- flow/cmd/validate_mirror.go
- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/clickhouse/normalize.go
Partially addresses #2019 
Tests column name equality taking exclusion into account, PeerDB columns, engine and emptiness
> [clickhouse] validate certain aspects of existing destination tables

- flow/connectors/utils/monitoring/monitoring.go
Mistake in #2029 where there's an extra `WHERE` in the delete command for `qrep_runs`
> Delete stats: Fix extra WHERE

- flow/connectors/snowflake/client.go
- flow/connectors/snowflake/snowflake.go
The `checkIfTableExists` function needs the input - schema name and table name - to be in the right case. Tested this on Snowflake and also with a mirror
Also we should not skip `SetupNormalize`  if the mirror is a resync mirror so that we can REPLACE the table downstream
> Fix snowflake table check

- flow/connectors/clickhouse/clickhouse.go
Validation to existing table which peerdb created fails because in SetupNormalize we lower case synced_at column. So that needs to be done in validation as well because by default it is upper case PEERDB_SYNCED_AT
> Existing tables check in CH: lower case synced_at column

- flow/connectors/clickhouse/normalize.go
- ui/components/ResyncDialog.tsx
Do no skip table creation in case of resync mirror because we need it to be REPLACEd downstream
> CH: Resync guard for setup normalize skip

- flow/cmd/settings.go
value can be overwritten by the next iteration which creates an incorrect result.
> fix settings page rendering

- flow/otel_metrics/otel_manager.go
Our otel manager currently breaks because of schema url version mismatch
> OTEL: change semconv to 1.26.0

- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/clickhouse/normalize.go
- ui/app/peers/create/[peerType]/schema.ts
There's engines like Distributed and other MergeTree family which could also be used in special workloads. Until we have more understanding on how these work and how common they are, don't block creation of mirrors.
> [clickhouse] make table engines a warning instead of an error

- flow/connectors/clickhouse/normalize.go
> drop ORDER BY _peerdb_timestamp in CH normalize statement

- nexus/peer-bigquery/src/ast.rs
- nexus/peer-bigquery/src/lib.rs
- nexus/peer-postgres/src/ast.rs
- nexus/peer-snowflake/src/ast.rs
rewrite rule was screwing up cte identifiers
> nexus: don't rewrite single identifier relations

- flow/connectors/postgres/cdc.go
When messages are received while cdc storage is empty we do not need to worry about confirming lsn too early before destination has processed previous records, so go ahead & progress lsn
> Advance LSN when PKM requested before any records received

- flow/connectors/postgres/cdc.go
- flow/connectors/utils/cdc_store.go
- flow/e2e/kafka/kafka_test.go
avoids empty batches from logical_emit_message heartbeat tripping timeout
> bypass cdc storage when handling logical emit message

- flow/connectors/clickhouse/normalize.go
- flow/datatypes/numeric.go
- flow/model/qvalue/dwh.go
This PR:
- Fixes casting of numeric values in Normalize insert-into-select statements in the Clickhouse connector
- Changes the behaviour of our default precision and scale setting. We now first check if we can reduce the precision to the maximum supported value, and only if not possible do we set it to our default. So for example for a numeric column on Postgres of type `numeric(78,70)`:
Previous behaviour for Clickhouse:
Since 78 is higher than the maximum supported precision on Clickhouse, we would set it to PeerDB's chosen default precision (76) and default scale (38)
New behaviour:
We first see that the precision is above max so we just change precision to the max of 76. 
Then we check if the new (precision, scale) tuple is valid. If not, then fallback to the behaviour from before …
> Numeric type: improved interface, fix Clickhouse support

- flow/cmd/mirror_status.go
- protos/route.proto
This PR allows us to query the stats for CDC batches and initial load clone summaries without having to go through the status endpoint which first pings Temporal state
> Direct access to CDC and initial load stats in API

- flow/cmd/mirror_status.go
- protos/route.proto
Add a limit field to the request for the cdc stats endpoint. Default of 0 corresponds to no limiting
> Add Limit as a field for cdc stats request

- flow/connectors/clickhouse/cdc.go
Raw table DDL is now featuring merge tree with order by of batch ID and destination table name:
```sql
CREATE TABLE IF NOT EXISTS raw (
_peerdb_uid String NOT NULL,
_peerdb_timestamp Int64 NOT NULL,
_peerdb_destination_table_name String NOT NULL,
_peerdb_data String NOT NULL,
_peerdb_record_type Int NOT NULL,
_peerdb_match_data String,
_peerdb_batch_id Int,
_peerdb_unchanged_toast_columns String
) ENGINE = MergeTree() ORDER BY (_peerdb_batch_id, _peerdb_destination_table_name);
```
Functionally tested and normalize IIS seems to be slightly faster than what it is currently
> Clickhouse raw table: merge tree, different order by

- flow/activities/flowable.go
- flow/activities/flowable_core.go
- flow/activities/snapshot_activity.go
- flow/cmd/handler.go
- flow/cmd/validate_mirror.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/clickhouse/normalize.go
- flow/connectors/core.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/postgres_schema_delta_test.go
- flow/connectors/snowflake/get_schema_for_tests.go
- flow/connectors/snowflake/snowflake.go
- flow/e2e/elasticsearch/peer_flow_es_test.go
- flow/e2e/generic/generic_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/snowflake/snowflake_schema_delta_test.go
- flow/shared/postgres.go
- flow/shared/schema_helpers.go
- flow/workflows/cdc_flow.go
- flow/workflows/normalize_flow.go
- flow/workflows/qrep_flow.go
- flow/workflows/setup_flow.go
- flow/workflows/snapshot_flow.go
- flow/workflows/sync_flow.go
- flow/workflows/xmin_flow.go
- nexus/catalog/migrations/V39__table_schema_mapping.sql
- protos/flow.proto
This data could get pretty large in temporal history, & was being duplicated with each NormalizePayload
Since it's meant to be based on real world state (source database schema), activity replay getting a more up to date schema shouldn't be an issue
> Remove TableNameSchemaMapping from temporal state

- flow/activities/flowable.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/clickhouse/cdc.go
- flow/connectors/core.go
- flow/connectors/postgres/postgres.go
- flow/connectors/snowflake/snowflake.go
- protos/flow.proto
In #2090 I got so caught up fixing bug @heavycrystal pointed out that I forgot I wanted to clean the code out of existence
This has no change in behavior, just cleans up protobuf so there isn't this weird 'workflow send nils into activity, activity fills in at start' protocol
> RenameTableOptions: remove TableSchema

- flow/connectors/clickhouse/normalize.go
- flow/e2e/clickhouse/clickhouse.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
- flow/model/qvalue/kind.go
Date in Clickhouse has a limited range of `[1970-01-01, 2149-06-06]`. Whereas Date32 has the same range of DateTime64(6), allowing dates < 1970 to be synced
This PR now maps dates in postgres to date32 instead of date on CH
> PG to Clickhouse: map date to date32

- flow/connectors/clickhouse/normalize.go
- flow/e2e/clickhouse/clickhouse.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
- flow/peerdbenv/dynamicconf.go
when primary key updated row becomes duplicate because old version isn't marked outdated,
generate deletion records behind updates
on an update heavy workload where primary keys aren't updated this can be disabled with `PEERDB_CLICKHOUSE_DISABLE_PRIMARY_UPDATE` to omit `UNION ALL`
if custom ordering is on a non replica identity column then row data may be missing,
causing this to fail to prevent duplication
> clickhouse: fix normalizing updates to primary key

- flow/connectors/clickhouse/clickhouse.go
- flow/e2e/postgres/peer_flow_pg_test.go
We're observing that this function (called while creating or updating a peer to validate it) can sometimes fail midway and leave this table around, trying to reduce the possibility of that
> [clickhouse] defer dropping table during ValidateMirror

- flow/connectors/clickhouse/clickhouse.go
clickhouse-go error may not be exception when it propagates io errors,
io.EOF is indicative of a disconnect, which should be retried
> ch retries: also retry on io.EOF

- flow/connectors/utils/ssh.go
`ParsePublicKey` expects the public key in a different SSH wire protocol format while `ParseAuthorizedKey` expects what you see in an `id_rsa.pub` file (which gives an error - `short read` when trying to parse it with `ParsePublicKey`)
References:
- [ParsePublicKey](https://pkg.go.dev/golang.org/x/crypto/ssh#ParsePublicKey)
- [ParseAuthorizedKey](https://pkg.go.dev/golang.org/x/crypto/ssh#ParseAuthorizedKey)
> SSH host key parsing: use ParseAuthorizedKey

- flow/cmd/custom_sync.go
- flow/cmd/handler.go
- flow/cmd/mirror_status.go
- flow/cmd/validate_mirror.go
- nexus/flow-rs/src/grpc.rs
- protos/route.proto
- ui/app/mirrors/[mirrorId]/edit/page.tsx
- ui/app/mirrors/[mirrorId]/handlers.ts
- ui/app/mirrors/[mirrorId]/page.tsx
- ui/app/mirrors/create/handlers.ts
- ui/components/DropDialog.tsx
- ui/components/ResyncDialog.tsx
We have a mix of ok: false & returning errors,
now that customers are using API this is negatively impacting their UX
(not to mention our own struggles)
Consolidate on consistently returning HTTP errors, rather than 200 OK with ok: false
> routes: remove ok/error_message

- flow/connectors/postgres/postgres.go
this was a check for Aurora failovers (see comment near edited code)
slot invalidation had the same errcode, so was hitting this codepath and causing spam (no backoff)
> [cdc] avoid spamming connections on slot invalidation

- flow/connectors/clickhouse/normalize.go
- Separate order by column logic into new function getOrderedOrderByColumns
- Simplify primary key and order by clause generation
- Ensure primary key columns are always at the end of ORDER BY clause
- Remove redundant code and improve readability
> Refactor ClickHouse table creation SQL generation

- flow/activities/flowable.go
- flow/activities/snapshot_activity.go
- flow/connectors/core.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/e2e/postgres/qrep_flow_pg_test.go
defer close(replicationErr) would panic if SetupReplication returns error after defer
replicationErr channel write also hangs indefinitely were SlotCreated written to previously
reuse SlotCreated error mechanism so only one channel is being waited on
> SetupReplication: clean up replicationErr handling

- flow/alerting/alerting.go
If the status of the slot is "lost" or "unreserved", then alert it via slack
> Add alerting for bad WAL status

- flow/activities/flowable.go
- flow/otel_metrics/peerdb_gauges/gauges.go
This give flexibility wrt metrics names which are emitted from PeerDB
> feat(otel): make metrics namespace configurable

- flow/connectors/postgres/postgres.go
Current query results in a sequential scan.
Can be optimized to instead use NOT EXISTS and perform index scans
Functionally tested with soft deletes on a composite primary key table
> PG to PG: Optimize resync query

- flow/connectors/postgres/cdc.go
Do not warn for every unsupported message type
> Change to debug log for unsupported message types

- flow/connectors/clickhouse/clickhouse.go
I was trying to create mirror from postgresql peer to clickhouse peer and got this error:
```bash
udev21=> create mirror my_test_mirror from mydb1 to clickhouse with table mapping ( public.products: products) WITH (do_initial_copy= true);
ERROR:  unable to submit job: "status: Unknown, message: \"invalid mirror: failed to get information for destination tables: code: 47, message: Missing columns: 'table' while processing query: 'SELECT name, engine, total_rows FROM system.tables WHERE (database = 'default') AND (table IN ('products'))', required columns: 'name' 'engine' 'total_rows' 'database' 'table', maybe you meant: ['name','engine','total_rows','database']\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\"} }"
```
after some research, found out …
> [clickhouse] fix checkTablesEmptyAndEngine sql query

- flow/alerting/alerting.go
- flow/go.mod
- flow/peerdbenv/config.go
- flow/shared/telemetry/incidentio_message_sender.go
- flow/shared/telemetry/incidentio_message_sender_test.go
- flow/shared/telemetry/interface.go
- flow/shared/telemetry/sns_message_sender.go
With ClickHouse migrating from PagerDuty to [incident.io](https://incident.io/), PeerDB needs the ability to hook into their RESTful API.
This PR introduces a telemetry sender alongside the existing SNS publisher to achieve this.
> [OPS] incident.io wire-up

- flow/cmd/mirror_status.go
Designing client side applications is tricky when you have to account for fields being undefined/null. This PR ensures that our stats endpoints return empty arrays at the very least
> Mirror stats: ensure we dont send nulls

- flow/activities/flowable_core.go
- flow/alerting/alerting.go
- flow/cmd/alerts.go
- flow/cmd/api.go
- flow/cmd/peer_data.go
- flow/connectors/core.go
- flow/connectors/utils/peers.go
- flow/peerdbenv/config.go
- flow/peerdbenv/crypt.go
- flow/peerdbenv/env.go
See #2178 for why KMS shouldn't itself be used for encryption/decryption
> KMS encrypt PEERDB_ENC_KEYS

- flow/connectors/clickhouse/normalize.go
- ui/app/mirrors/create/cdc/columnbox.tsx
- ui/app/mirrors/create/cdc/schemabox.tsx
- ui/app/mirrors/create/cdc/sortingkey.tsx
- ui/app/utils/notify.tsx
User can now specify order key list by selecting from a dropdown. If they do this, then a warning banner also pops up. This links to a document explaining the various caveats of custom order keys
Instead of suffixing the primary keys at the end of the ordering key, the behaviour is now:
If user doesn't define order key - PKEY and ORDER BY in CH is PKEY in Postgres.
If user defines order key - PKEY and ORDER BY in CH is defined Order Key in Postgres.
> Create ClickHouse mirror: New sorting key UI and logic

- flow/peerdbenv/config.go
- flow/peerdbenv/env.go
kms should not be polled repeatedly, keep an in-memory cache of decrypted kms env variables
> kms: cache results

- flow/connectors/snowflake/qrep_avro_consolidate.go
not wiring as a dynamic config as if exposed in UI I'd want to put validation on it
https://docs.snowflake.com/en/sql-reference/sql/copy-into-table#copy-options-copyoptions
> env: PEERDB_SNOWFLAKE_ON_ERROR

- flow/connectors/clickhouse/normalize.go
in response to errors like
```
code: 44, message: Sorting key contains nullable columns, but merge tree setting allow_nullable_key is disabled
```
> set allow_nullable_key = 1 when PEERDB_NULLABLE true

- flow/cmd/peer_data.go
potentially leaks connections otherwise
> call connectors.CloseConnector when creating GetVersionConnector

- flow/connectors/clickhouse/normalize.go
- flow/connectors/clickhouse/qrep.go
- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
Quotes table name in our inserts and adds a test with a table called "table" (reserved keyword) in it
> ClickHouse: Quote table name in insertions

- flow/cmd/api.go
- flow/middleware/logging.go
- flow/middleware/oauth.go
- flow/peerdbenv/config.go
- flow/peerdbenv/oauth.go
Set `PEERDB_API_REQUEST_LOGGING_ENABLED` = true to enable request logging. Separating it from the oauth interceptor incase oauth is disabled and we wish to enable request logging
> feat: add request logging interceptor for API

- flow/cmd/mirror_status.go
- protos/route.proto
- ui/app/mirror-logs/table.tsx
- ui/app/mirrors/errors/[mirrorName]/page.tsx
- ui/components/LogsTable.tsx
using LIMIT/OFFSET is inaccurate when new logs come it while logs being viewed
this makes a minor improvement by instead being based on records before/after an id from previous page,
which is how I'd like to also add pagination to sync batches in mirror status
> improve logs pagination

- flow/cmd/mirror_status.go
- protos/route.proto
- ui/app/mirrors/[mirrorId]/aggregatedCountsByInterval.ts
- ui/app/mirrors/[mirrorId]/cdc.tsx
- ui/app/mirrors/[mirrorId]/cdcDetails.tsx
- ui/app/mirrors/[mirrorId]/cdcGraph.tsx
- ui/app/mirrors/[mirrorId]/handlers.ts
- ui/app/mirrors/[mirrorId]/page.tsx
- ui/app/mirrors/[mirrorId]/qrepGraph.tsx
- ui/app/mirrors/[mirrorId]/syncStatus.tsx
- ui/app/mirrors/[mirrorId]/syncStatusTable.tsx
- ui/app/peers/[peerName]/lagGraph.tsx
- ui/app/settings/page.tsx
- ui/components/LogsTable.tsx
Some customers have enough batches now that response size was exceeding grpc limit
Changing this meant loading pages & aggregating graph data on server
Removed searching specific batch id & changing sort column from ui
> Sync batch pagination

- docker-compose-dev.yml
- docker-compose.yml
Image exists, but not tested, should be fine
> fix: temporal admin tools image version

- flow/connectors/clickhouse/cdc.go
- flow/connectors/clickhouse/clickhouse.go
Currently, peerdb creates a _resync table and then tries to run 
```sql
DROP TABLE IF EXISTS target_table;
RENAME TABLE _resync_table TO target_table;
```
however, the problem is that this procedure breaks, once a depending dictionary is defined on these tables.
In order to enable such behavior, this PR modifies the ClickhouseConnector of Flow to 
- check whether the database engine supports the `EXCHANGE TABLES` command (https://clickhouse.com/docs/en/sql-reference/statements/exchange)
- If it does and the table already existed, runs `EXCHANGE TABLES` followed by a `DROP` which atomically swaps and therefore keeps the dictionary references
- If it doesnt, there's a fallback to the old method.
Currently, this will work with the Atomic() database engine.
> Implement table rename with atomic exchange

- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/clickhouse/normalize.go
- flow/connectors/external_metadata/store.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/snowflake.go
Searched for `if rows.Err` & removed all instances
Has tendency to typo into branch referencing `err` which code expects to be result of `rows.Err()`
> cleanup error handling, fixes 2 bugs

- flow/peerdbenv/dynamicconf.go
users predating PG14 should change the query or disable wal heartbeats
>  Enable wal heartbeats by default

- flow/connectors/clickhouse/normalize.go
- flow/peerdbenv/dynamicconf.go
uses channel to even out uneven workload distribution
> PEERDB_CLICKHOUSE_PARALLEL_NORMALIZE

- flow/peerdbenv/dynamicconf.go
- flow/workflows/local_activities.go
- flow/workflows/qrep_flow.go
Currently overwrite mode in query replication has the following behaviour:
Before new rows are synced, truncate the destination table
This PR introduces a dynconf-gated (default false) full refresh mode which if enabled, has the same behaviour as above but pulls the entire data from the source table at every wait time interval
> QRep Overwrite Mode: introduce full refresh code path

- docker-compose.yml
renovate will automatically pin the latest stable weekly to ensure that whenever docker compose up is run again after updating the repo, it will use the latest sha
> feat: use latest-stable in docker-compose.yml

- flow/cmd/worker.go
- flow/connectors/postgres/postgres.go
- flow/otel_metrics/otel_manager.go
- flow/otel_metrics/peerdb_gauges/gauges.go
- flow/otel_metrics/sync_gauges.go
Upstream added gauges in May: https://github.com/open-telemetry/opentelemetry-go/pull/5304
> Replace SyncGauge with upstream otel sdk gauges

- flow/e2e/test_utils.go
- flow/workflows/cdc_flow.go
- protos/flow.proto
Introduces a new flow state - `Completed` 
Currently this is the state for an initial load only mirror which has finished initial load
> Introduce Completed flow status

- flow/activities/flowable.go
- flow/alerting/alerting.go
- ui/app/peers/[peerName]/lagGraph.tsx
- Account for NaN values in LSN function
- Add alerts for failure to get postgres connector in maintainpull 
- Fix <= sign in slack alert log
> Miscellaneous fixes - add more alerting for maintainpull, fix lag graph function

- ui/app/settings/page.tsx
This PR opts for a card grid display for the settings page rather than a table - as the content was being cramped in to fit in that tabular layout
> Revamp settings page

- flow/connectors/clickhouse/normalize.go
This PR fixes a bug where we are returning the wrong error object resulting in flow-worker panics
> CH Normalize: fix error return

- flow/cmd/worker.go
Currently flow-worker panics due to assignment to nil map entry at the getOrInitMetric call in the int64 counter because the map is nil
> Otel: initialise int64counter

- flow/connectors/clickhouse/clickhouse.go
[A recent effort ](https://github.com/PeerDB-io/peerdb/pull/2256/files) was made to improve PeerDB's ingestion performance into ClickHouse by parallelizing the INSERT INTO SELECT queries which took data from the raw table and put it into the final tables. Just before this step, PeerDB moves data from S3 to the raw table.
In this implementation, every insert runs on a new ClickHouse session - which means the inserts could be running on different nodes/replicas. In this case, there exists a non-zero chance (albeit very unliikely) that the INSERT INTO SELECT does not read the rows in the raw table inserted by the first step.
This is documented here: https://clickhouse.com/docs/en/cloud/reference/shared-merge-tree#consistency
This PR adds the setting `select_sequential_consistency = 1` in the …
> Clickhouse: add select consistency

- flow/cmd/worker.go
- flow/otel_metrics/otel_manager.go
Move the initialization logic for OtelManager from worker.go into a dedicated constructor function NewOtelManager() in otel_metrics/otel_manager.go. This improves code organization and encapsulation by keeping OtelManager-related logic within its own package.
> refactor: move OtelManager initialization to constructor

- flow/connectors/snowflake/snowflake.go
closes #2312 
however this can cause data to be missed if the schema is missing incorrectly (as opposed to table being dropped)
> ignore tables in raw table if no schema known for table

- nexus/peer-postgres/src/stream.rs
- nexus/value/src/array.rs
> nexus: support uuid arrays

- flow/connectors/bigquery/qvalue_convert.go
- flow/connectors/postgres/qrep_query_executor_test.go
- flow/connectors/postgres/qvalue_convert.go
- flow/connectors/snowflake/avro_file_writer_test.go
- flow/connectors/sql/query_executor.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/model/qrecord_copy_from_source.go
- flow/model/qvalue/avro_converter.go
- flow/model/qvalue/equals.go
- flow/model/qvalue/kind.go
- flow/model/qvalue/qvalue.go
- flow/model/record_items.go
- flow/pua/peerdb.go
> qvalue: UUID array type

- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/model/cdc_stream.go
1. log when we're remapping child table OID to parent table OID
2. partition fetching query also allows non-partitioned tables, extensions use this
3. in case we see an unknown table OID after checking `childToParentRelIDMapping`, check again to ensure the table wasn't created in the middle of CDC
4. remove log since it could log PII
> [cdc] better manual handling of partitioned tables

- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/core.go
- flow/e2e/clickhouse/clickhouse.go
for generic schema changes e2e, alternative to #2114
> ch: implement GetTableSchemaConnector

- flow/connectors/bigquery/bigquery.go
- flow/connectors/clickhouse/normalize.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
previously: https://github.com/PeerDB-io/peerdb/pull/2317
came up with pg: https://github.com/PeerDB-io/peerdb/issues/2354
> port recent SF fix to BQ/PG/CH

- flow/connectors/postgres/qvalue_convert.go
We need to explicity deal with infinity/-infinity tstzrange values as time.Parse cannot parse those
> TSTZRange: Account for infinity modifier

- .github/workflows/flow.yml
- flow/e2e/bigquery/bigquery.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
BQ was being more flaky after matrix added. Limit concurrency on external services
> ci: only run BQ on pg16 & SF on pg17

- flow/connectors/postgres/postgres.go
still report this as an error during validation
> drop mirror: ignore `cannot execute DROP PUBLICATION in a read-only transaction (SQLSTATE 25006)`

- flow/workflows/sync_flow.go
This makes max back-off closer to 1 hour and also prevents alert spam.
> Change initial back-off interval for sync-flow to be 30s

- .github/workflows/golang-lint.yml
- flow/.golangci.yml
- flow/connectors/core.go
- flow/connectors/postgres/qrep_query_executor_test.go
- flow/connectors/sql/query_executor.go
- flow/connectors/utils/aws.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/sqlserver/sqlserver_helper.go
- flow/shared/telemetry/incidentio_message_sender.go
- flow/shared/telemetry/incidentio_message_sender_test.go
- flow/shared/telemetry/sender.go
- flow/shared/telemetry/sns_message_sender.go
Enable new linters: iface & recvcheck
> golangci-lint 1.62

- flow/activities/flowable.go
- flow/activities/flowable_core.go
- flow/shared/constants.go
> SyncFlow: top level heartbeat

- flow/connectors/bigquery/qrep.go
- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/connectors/elasticsearch/qrep.go
- flow/connectors/kafka/qrep.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/sink_pg.go
- flow/connectors/postgres/sink_q.go
- flow/connectors/pubsub/qrep.go
- flow/connectors/s3/qrep.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/utils/avro/avro_writer.go
- flow/model/qrecord_stream.go
- flow/model/qvalue/qschema.go
- flow/pua/stream_adapter.go
goroutines were leaking waiting on schemaLatch,
if provider hit error then schemaLatch could be left indefinitely open
> QRecordSchema: close schemaLatch in Close

- flow/activities/flowable.go
- flow/activities/flowable_core.go
- flow/model/qrecord_stream.go
if pull connector fails to initialize due to some reason and sync is already stuck on `chan receive`, then partClone workflow will hang indefinitely. fixed by closing stream explicitly before pull side errgroup goroutine returns.
> [snapshot] close stream when fail to get srcConn in errgroup

- flow/connectors/clickhouse/cdc.go
There are tricky situations pertaining to data consistency with transferring soft-deletes to the new table during a resync.
For example, there is currently a bug where, in the old table, if a record was deleted and re-inserted (for the same primary key), we would then mark an existing row as deleted in the new resync table when in fact it is not 
This PR removes soft-delete transferring altogether for ClickHouse connector's resync
> ClickHouse resync: remove soft-delete transfer

- flow/e2e/postgres/peer_flow_pg_test.go
- flow/workflows/cdc_flow.go
- flow/workflows/drop_flow.go
- flow/workflows/setup_flow.go
- flow/workflows/snapshot_flow.go
- flow/workflows/xmin_flow.go
Retrying in 1 sec very rarely changes things as we typically tend to wait for database auto-scaling, network issue resolution or other error types wherre we would anyways need to wait in the order of minuted.
It was also causing alert spamming in the systems basically making them not usable for a certain kind of errors.
> Increase retry initial backoff to 1 minute

- flow/activities/flowable.go
- flow/connectors/clickhouse/normalize.go
- flow/connectors/external_metadata/store.go
Just some log nits for monitoring syncs
> Edit some logs

- flow/e2e/clickhouse/peer_flow_ch_test.go
- flow/e2e/test_utils.go
- flow/workflows/cdc_flow.go
this prevents rewinding state to start of workflow from undoing changes to settings (such as table additions/removals)
> cdc flow: continue as new after state updates

- flow/connectors/utils/monitoring/monitoring.go
- nexus/catalog/migrations/v42__add_null_end_time_index_cdc_batches.sql
Existing query can cause problems on mirrors with very low sync interval as the batches table grows large
> fix: use condition instead of coalesce for updates on cdc_batches

- .github/workflows/golang-lint.yml
- flow/otel_metrics/observables.go
- flow/otel_metrics/otel_manager.go
> refactor: revert to using observables modified to sync gauges

- flow/connectors/postgres/postgres.go
changing publicationName to empty string only caused us to error later with the opaque:
error getting replication options: publication name is not set
caused when publication dropped on source
> fail faster when publication does not exist while setting up replication

- nexus/analyzer/src/lib.rs
Only look at first identifier in ObjectName, ideally parser should only accept single identifier there
> nexus: CREATE PEER should not include quotes in name

- flow/activities/flowable.go
- flow/activities/flowable_core.go
instead of every 30s, wait 1m, then 2m, then 4m, then 5m indefinitely
> normalize: slow down retries

- stacks/flow.Dockerfile
go 1.23.5 released, but image is still 1.23.4
go.work is used for gopls to work correctly,
not required for build but version mismatch breaks build
> flow.Dockerfile: rm -f go.work*

- flow/connectors/postgres/postgres.go
Follow-up to https://github.com/PeerDB-io/peerdb/pull/2372
Since this function is just for recording in a stat table, the error can just be logged.
> LSN Fetch for stats: Make it non-fatal for null LSN

- flow/activities/flowable.go
- flow/activities/snapshot_activity.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_partition_test.go
- flow/connectors/postgres/ssh_wrapped_pool.go
- flow/connectors/sqlserver/qrep.go
- flow/connectors/utils/monitoring/monitoring.go
- flow/connectors/utils/partition/partition.go
- flow/middleware/oauth.go
> misc cleanup

- flow/e2e/bigquery/bigquery.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/clickhouse/clickhouse.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
- flow/e2e/congen.go
- flow/e2e/elasticsearch/elasticsearch.go
- flow/e2e/elasticsearch/peer_flow_es_test.go
- flow/e2e/eventhub/peer_flow_eh_test.go
- flow/e2e/generic/generic_test.go
- flow/e2e/kafka/kafka_test.go
- flow/e2e/pg.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/postgres/postgres.go
- flow/e2e/pubsub/pubsub_test.go
- flow/e2e/s3/cdc_s3_test.go
- flow/e2e/s3/qrep_flow_s3_test.go
- flow/e2e/snowflake/peer_flow_sf_test.go
- flow/e2e/snowflake/qrep_flow_sf_test.go
- flow/e2e/snowflake/snowflake.go
- flow/e2e/sqlserver/qrep_flow_sqlserver_test.go
- flow/e2e/test_utils.go
split out from #2395, where this allows tests to run against both PG & MySQL
> e2e: SuiteSource

- flow/activities/flowable.go
- flow/activities/flowable_core.go
- flow/activities/maintenance_activity.go
- flow/alerting/alerting.go
- flow/cmd/handler.go
- flow/cmd/snapshot_worker.go
- flow/cmd/worker.go
- flow/connectors/postgres/cdc.go
- flow/main.go
- flow/otel_metrics/attributes.go
- flow/otel_metrics/otel_manager.go
Adds a few new metrics:
1. `error_emitted` - instantaneous gauge of whether an error is being
emitted
2. `errors_emitted` - counter of errors emitted over time
3. `records_synced` - number of records synced for every sync batch.
4. `synced_tables` - number of tables configured in each mirror
5. `instance_status` - a constant `1` metric every 5 minutes (same frequency as slots) with attributes differentiating the current status
6. `maintenance_status` - a constant `1` when maintenance is running, also has attributes differentiating the current status
TODO: maybe refactor code so that maybe all gauges/counters are initialized inside the otelManager?
ref #2341
> feat: add more metrics

- flow/activities/flowable.go
- flow/activities/flowable_core.go
- flow/connectors/bigquery/qrep_avro_sync.go
- flow/connectors/clickhouse/cdc.go
- flow/connectors/core.go
- flow/connectors/elasticsearch/elasticsearch.go
- flow/connectors/eventhub/eventhub.go
- flow/connectors/external_metadata/store.go
- flow/connectors/kafka/kafka.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/connectors/pubsub/pubsub.go
- flow/connectors/s3/s3.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/utils/monitoring/monitoring.go
- flow/model/cdc_stream.go
- flow/model/model.go
- flow/pua/stream_adapter.go
- nexus/catalog/migrations/V42__mysql_metadata.sql
for pg we currently use destination instead of catalog. mysql->pg will use catalog. therefore metadata tables on destination pg can ignore this change, avoiding issues upgrading existing pgpg setups
also update connector interfaces a bit
split out from #2395
> checkpoint: add text alongside int64

- flow/cmd/handler.go
- flow/workflows/drop_flow.go
- nexus/flow-rs/src/grpc.rs
- protos/flow.proto
- protos/route.proto
- ui/app/mirrors/[mirrorId]/edit/page.tsx
- ui/app/mirrors/[mirrorId]/handlers.ts
This PR introduces a flag for the input of drop mirror to not bother with trying to drop destination peer artifacts.
- Useful in cases where the target data store no longer exists, or if the user wishes for the cdc raw table to remain or has some dependencies on it
Open to renaming or rewiring the flag
Tested with API call:
```bash
curl --request POST \
--url http://localhost:3003/api/v1/mirrors/state_change \
--header 'Authorization: Basic OnBlZXJkYg==' \
--header 'Content-Type: application/json' \
--data '{
"flowJobName": "drop_this",
"requestedFlowState": "STATUS_TERMINATED",
"skipDestinationDrop": true
}'
```
> Drop mirror: introduce opt-in setting to skip destination dropping

- flow/connectors/clickhouse/normalize.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
Appending to end of query broke with UNION ALL introduced when using primary key updates
This method also works better with setting to run inserts in parallel, where chunks will be distributed to these inserts,
which can speed up single table mirrors
> Fix chunking with enabled primary key updates

- flow/model/signals.go
- flow/workflows/cdc_flow.go
In development heartbeat timeout happens between runs, which set off 10 minute timeout
Also, long sleeps in workflows using signals blocks those signals, causing things like taking minutes to start pausing.
Wrap `workflow.Sleep` in `workflow.Go` which sets off a `workflow.Future` which can be waited on alongside signals
> cdc flow: only sleep for 10 minutes for panics & application errors

- nexus/Cargo.lock
- nexus/peer-snowflake/Cargo.toml
- nexus/peer-snowflake/src/stream.rs
ureq-proto released a breaking change in 2.0.6 which broke our build
ureq used because of reddit: https://old.reddit.com/r/rust/comments/f39ueb/how_to_use_reqwest_without_async/fhiyw6n
instead use futures::unfold to properly implement async streams with an async http client,
as a bonus we replace our dependency on ureq with our existing dependency on reqwest
> remove ureq

- nexus/Cargo.lock
- nexus/value/Cargo.toml
- nexus/value/src/array.rs
bytes are encoded as base64, but then hex for arrays of bytes
always serialize to json as base64
> nexus: consistent binary serialization

- flow/cmd/peer_data.go
- protos/route.proto
- ui/components/PeerInfo.tsx
As mentioned here: https://github.com/PeerDB-io/peerdb/pull/2361, we would want the rendering of the edit button to not have to go through the hoops of getting version, connecting to the data stores etc
> Edit peer button: separate peer type fetch

- ui/lib/AppTheme/tailwind.css
tailwind v4 removed safelists,
explicitly add css rules tremor expects to be generated
> fix ui charts

- flow/activities/flowable.go
- flow/activities/flowable_core.go
- flow/cmd/snapshot_worker.go
- flow/cmd/worker.go
- flow/connectors/core.go
- flow/connectors/postgres/cdc.go
- flow/otel_metrics/attributes.go
- flow/otel_metrics/observables.go
- flow/otel_metrics/otel_manager.go
- flow/shared/context.go
- flow/workflows/cdc_flow.go
- flow/workflows/drop_flow.go
- flow/workflows/util.go
- protos/flow.proto
The context is propagated as temporal headers:
Metrics automatically have the desired attributes:
> feat: add context propagator and use it to enrich metrics with flow metadata

- flow/alerting/alerting.go
- flow/alerting/classifier.go
- flow/connectors/postgres/postgres.go
- flow/otel_metrics/attributes.go
- flow/peerdbenv/config.go
- flow/shared/exceptions/postgres.go
Will be good to have #2493 out first if possible
> feat: add alert classifier

- flow/connectors/mysql/cdc.go
- flow/model/cdc_stream.go
more conservative approach to bring over postgres/cdc.go logic relative to #2506
kind of surprised cdc worked without this
*edit: so it worked before because closing the record stream would close the channel which would give the receiver the default value `false` for `isEmpty`*
> mysql: SignalAsEmpty/SignalAsNotEmpty

- flow/workflows/scheduled_flows.go
Alerting tools like Prometheus have a staleness range of 5 mins, so we need to push metrics with a finer granularity
> feat(record-slot-size): increase frequency to 2 mins

- flow/connectors/postgres/qrep.go
- flow/shared/math.go
- flow/shared/math_test.go
Adjusts partition calculation to ensure count stays under 1000 by increasing rows per partition when needed. This prevents hitting Temporal platform limits.
> fix: limit partition count to 1000 for temporal platform

- flow/connectors/mysql/cdc.go
- flow/e2e/bigquery/peer_flow_bq_test.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
- flow/e2e/mysql.go
- flow/e2e/pg.go
- flow/e2e/snowflake/peer_flow_sf_test.go
also tests column exclusion with mysql as source
fails, added some logic which requires `binlog_row_metadata = full`
could put column number in table schema info to remap cdc column index to schema column index
should raise error if we detect we're going to panic
> mysql column exclusion

- flow/activities/flowable.go
- flow/activities/flowable_core.go
- flow/activities/snapshot_activity.go
There are some operations before the activity heartbeat loop we have in place in this activity that can take a while. We thus need a top level heartbeat routine
> MaintainTx: Add heartbeat routine

- flow/workflows/cdc_flow.go
- flow/workflows/qrep_flow.go
then `return state, nil` at start after setting up queries
old mirrors which had completed were running into non-determinism errors when queried,
as once completed they can't go through pause/resume for migrations
> cdc/qrep workflows: continue as new after setting state to completed

- flow/activities/flowable.go
- flow/cmd/snapshot_worker.go
- flow/cmd/worker.go
- flow/internal/context.go
- flow/otel_metrics/attributes.go
- flow/otel_metrics/observables.go
- flow/shared/context.go
- flow/shared/logger.go
- flow/workflows/cdc_flow.go
- flow/workflows/drop_flow.go
- flow/workflows/util.go
- protos/flow.proto
This can potentially resolve #2470
Maybe we should also set context in the child workflows, but should be fine for initial cases
This PR will lead to non-determinism in completed mirrors for releases that were upgraded from v0.24.0 to v0.25.0 (releases upgraded from version < 0.24.0) should be ok
They can be fixed by rerunning the old completed workflow with 2nd input as completed and updating catalog entry to point to the new wf
> feat(flow-context): add current flowStatus and resync information

- flow/cmd/peer_data.go
- flow/cmd/validate_peer.go
- flow/connectors/core.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/normalize_stmt_generator.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_partition_test.go
- flow/connectors/postgres/sink_pg.go
- flow/connectors/postgres/sink_q.go
- flow/connectors/postgres/validate.go
- flow/connectors/utils/escape.go
- flow/connectors/utils/identifiers.go
- flow/e2e/mysql.go
- flow/e2e/pg.go
- flow/e2e/postgres/postgres.go
- flow/workflows/snapshot_flow.go
1. move QuoteLiteral & QuoteIdentifier to connectors/utils. These functions are portable across ANSI SQL
2. implement ValidationConnector for PostgresConnector, remove specialized PG peer validation
3. replace getPGPeerConfig/getConnForPGPeer with connectors.GetByNameAs in cmd/peer_data
> Cleanup connpostgres usage outside connpostgres

- flow/connectors/clickhouse/normalize.go
pg only sends old items when replica identity updated
> primary key update: skip empty _peerdb_match_data rows

- ui/app/mirrors/create/cdc/schemabox.tsx
- ui/app/mirrors/create/cdc/tablemapping.tsx
Currently, excluded columns and engine selection are not populated in the table box for an existing table in the mirror (where the destination field, engine, columns are disabled)
This PR wires those through. Tested
> UI: Reflect column and engine values for existing tables

- flow/connectors/mysql/mysql.go
based on https://github.com/go-mysql-org/go-mysql/pull/997 without having to switch to `database/sql`
> mysql: context

- flow/internal/context.go
- flow/otel_metrics/observables.go
- protos/flow.proto
FlowContextMetadata is currently global and any change in child/parent will propagate to everywhere within the flow
This adds a secondary AdditionalContext which is passed by copy instead and any `context.WithValue` for it will apply only to the newly created contexts
Eg: Operation depends on the child context and is not global, the lifecycle of operation is that context itself
> feat: add additional non-proto metadata and move flowOperation

- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/clickhouse/normalize.go
Seems like we have facility to detect some retryable error codes when inserting into clickhouse, allowing us to retry on the spot rather than having normalise as a whole retry
Related [comment](https://github.com/PeerDB-io/peerdb/pull/2662#discussion_r1983113366)
> ClickHouse: use retryable exec for normalise insert

- flow/activities/flowable_core.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
When a column addition occurs, at the end we update the schema of the table in the table_schema_mapping table in catalog in `applySchemaDeltas`
We currently are not passing the `Env` map to `applySchemaDeltas`, and `Env` contains nullable_enabled information. If the nullable setting is set to true, then after this column addition, it would be reset to false, causing data inconsistencies
This PR adds this wiring
> applySchemaDeltas: add missing env wiring

- flow/alerting/classifier.go
Can also mark as `ErrorInternalClickHouse` or a fully new error code
> feat(classifier): mark ch auth failures as recoverable and push out ch error code always

- flow/activities/snapshot_activity.go
- flow/connectors/core.go
- flow/connectors/mysql/cdc.go
- flow/connectors/postgres/client.go
- flow/connectors/postgres/postgres.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
- flow/internal/dynamicconf.go
- flow/shared/postgres.go
- flow/workflows/snapshot_flow.go
- protos/flow.proto
This avoids keeping a long running connection during initial load, preventing connection drops from breaking initial load
> PEERDB_SKIP_EXPORT_SNAPSHOT

- flow/connectors/postgres/postgres.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
Turns out 'schema.table'::regclass does not handle case-sensitivity correctly. This PR alters the SQL for getting selected columns to account for mixed case table names
> Getting selected columns: use format along with regclass

- flow/connectors/clickhouse/normalize.go
- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/connectors/s3/qrep.go
- flow/connectors/snowflake/avro_file_writer_test.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/utils/avro/avro_writer.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
- flow/model/conversion_avro.go
- flow/model/qvalue/avro_converter.go
- flow/model/qvalue/avro_converter_test.go
- flow/shared/clickhouse/escape.go
Avro requires alphanumeric + underscore field names. However Postgres column names do not have the same restriction.
- This PR introduces a map of column names to an Avro compatible encoding of the same. Violating characters are replaced by underscore and the resulting string is suffixed with a serial number.
- This is utilized only for the initial load Avro loading since for CDC the columns will be that of our raw table columns.
- This PR only implements this support for ClickHouse target peers
- It also supports these columns for our normalize inserts by escaping the single quotes in column name argument of the JSONExtract* functions
- Functionally tested and the unprivileged columns E2E test has been adapted to include more columns to test this PR
Fixes #2701
> ClickHouse: Support for special characters in column names

- nexus/Cargo.lock
- nexus/Cargo.toml
- nexus/peer-mysql/Cargo.toml
- nexus/postgres-connection/Cargo.toml
- nexus/postgres-connection/src/lib.rs
with #2712 we've added aws-lc-rs to our dependencies
ring recently lost some confidence with https://github.com/briansmith/ring/discussions/2414
switch to using aws-lc-rs ourselves. ring remains a downstream dependency
> nexus: aws-lc-rs

- flow/connectors/postgres/validate.go
without this setting on a standby, replication slots can be invalidated due to `conflict with recovery`
so explicitly checking for this
> [postgres] validate hsfeedback on standby

- flow/e2e/generic/generic_test.go
schema change replay has a bug where in some edge cases, we blindly update the schema of a Postgres table and save it to catalog before we receive the `RelationMessage` from Postgres that would help us detect and apply the change on the destination
The root cause of this was in a function `applySchemaDeltas` we refreshed the schemas of *all* tables in catalog instead of the ones we saw changes for, so consider the following sequence of events
1. receive changes for table t2
2. schema change: add column for table t1
3. schema change: add column for table t2
4. receive changes for table t1 with new column
5. receive changes for table t2 with new column
If the current batch ends between 4 and 5. Postgres sends `RelationMessage` for t1 with the new column so we are able to add the column on …
> added e2e test for cutoff bug in schema change handling

- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/workflows/snapshot_flow.go
This avoids issues when setting multiple tables in a mirror to output to same table
This is incomplete, but a start
Also remove a soft delete reference since CH doesn't do soft deletion like that
> initial load: base clone workflow id on source, not destination

- flow/alerting/classifier.go
can happen when publication does not exist
> classify undefined object same as undefined table

- flow/connectors/clickhouse/validate.go
- flow/e2e/api/api_test.go
- flow/e2e/bigquery/bigquery_helper.go
also remove unused BQ code, all BQ integers are int64
> e2e api mirror validation

- flow/connectors/sql/query_executor.go
- flow/e2e/snowflake/snowflake_helper.go
generic sql code only used by sqlserver & snowflake,
ideally this would be entirely removed & consumers would directly use sqlx.DB
but for now keeping clean up simple
> generic sql: remove unused methods

- flow/e2eshared/e2eshared_test.go
- flow/model/qvalue/qschema.go
adds coverage since in normal use we never compare incompatible schemas
> e2eshared: couple unit tests

- flow/activities/maintenance_activity.go
- flow/model/signals.go
- flow/workflows/maintenance_flow.go
- protos/flow.proto
ref #2259 
To bypass maintenance for long running failing initial loads, we had to disable sync and maintenance in chart, and then remember to enable it in chart later when upgrading the next time.
This also caused laziness to skip upgrading altogether
This PR adds a new signal which can be used to bypass initial load checks for specified flows:
```json
{
"skipped_snapshot_wait_flows": [
"failing_flow_name_here"
]
}
```
> feat(maintenance): add signal to skip snapshot for specific flows

- flow/activities/flowable.go
- flow/connectors/postgres/postgres.go
- flow/otel_metrics/otel_manager.go
current_wal_lsn can be calculated as restart_lsn + slot lag (in bytes)
> feat(metrics): add more lsn information

- flow/activities/flowable_core.go
postgres connector errors with disconnect typed errors when it detects misconfiguration,
these errors should be propagated to alerting
> be more precise about ignoring temporal application errors

- flow/activities/maintenance_activity.go
- protos/flow.proto
resolves #2768 
If workflow does not exist in temporal, it probably means that it was dropped long back and the cancelled CDCFlowWorkflow is beyond its retention period. This PR aims to guess this and skip pausing for such mirrors
> fix(maintenance): skip for not found workflows if older than 90 days

- flow/connectors/mysql/cdc.go
- flow/connectors/mysql/qvalue_convert.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
overlooked some types:
* tinytext
* mediumtext
* longtext
* tinyblob
* mediumblob
* longblob
* specific geometry types
also enum/sets got lost, as in qrep they're sent as text, but in cdc they're int64 & we have to do some lookups
> mysql: map specific types same as their more generic type

- flow/connectors/mysql/qvalue_convert.go
should only happen with schema desynchronization, but avoids panic
> return error on invalid enum/set value

- flow/connectors/mysql/mysql.go
I tried, but GCP MySQL 8.0 doesn't support tls 1.3
> mysql: min version tls 1.2

- flow/alerting/classifier.go
- flow/connectors/mysql/mysql.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/ssh_wrapped_conn.go
- flow/internal/catalog.go
- flow/internal/config.go
- flow/internal/postgres.go
- flow/shared/crypto.go
- nexus/analyzer/src/lib.rs
- nexus/catalog/src/lib.rs
- protos/peers.proto
- ui/app/dto/PeersDTO.ts
- ui/app/peers/create/[peerType]/helpers/pg.ts
- ui/app/peers/create/[peerType]/schema.ts
- ui/components/PeerForms/ClickhouseConfig.tsx
- ui/components/PeerForms/MySqlForm.tsx
- ui/components/PeerForms/PostgresForm.tsx
pgx follows libpq's bad sslmode=prefer default
when root ca specified, behave like sslmode=verify-ca if host is IP, otherwise like sslmode=verify-full
include require tls option to behave like sslmode=require
https://github.com/golang/go/issues/21971
update pg & mysql to skip hostname verification when host is an IP address,
GCP instances have certs without CN/SAN, only relying on trusting root CA
> don't verify hostname for ip hosts, add root ca field to pg

- flow/connectors/clickhouse/validate.go
resync sets disallowEmpty to false
triggers check of dynconf variable which may set it to true again
> [clickhouse] make resync not trigger empty table check

- flow/alerting/classifier.go
- flow/alerting/classifier_test.go
When droppping a pipe during initial load it can take some time for the workflow to get cancelled. During this time the insert queries fail with errros like: `ID(a14c2a1c-edcd-5fcb-73be-bd04e09fccb7) not found in user directories`.
For now classifying as recoverable because if seen for a longer duration we should be alerted
ref https://github.com/ClickHouse/ch-go/pull/1058 for adding the new error code
> feat(classifier): add ACCESS_ENTITY_NOT_FOUND with condition as recoverable

- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/utils/cdc_store.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
UUID Array should be registered for the gob encoder, else can see an error like:
```
unable to encode value 0x4185435360: gob: type not registered for interface: qvalue.QValueArrayUUID
```
> Gob: register array uuid

- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/postgres.go
- flow/e2e/generic/generic_test.go
- flow/e2e/pg.go
- flow/e2e/test_utils.go
- flow/internal/dynamicconf.go
Most users of partitioned tables we've encountered so far use Postgres "native" partitioning, in which the parent table is marked with a special relation kind (`relkind`) of `p`. This is handled best by setting `publish_via_partition_root` on the publication (we create publications like this, users are encouraged to) but as a fallback for pre PG13 we also support "lookup" of child to parent tables and using that information to manually implement child-to-parent table mapping. We also recently made this lookup dynamic, so new partitions encountered after we start CDC should also be handled.
There is also the possibility of child tables for a regular table, either via extensions doing this or because Postgres supports [table inheritance](https://www.postgresql.org/docs/current/ddl-inherit.ht …
> Formalize how we handle table inheritance for partitioned tables

- flow/connectors/clickhouse/normalize.go
Currently, when an insert-into-select fails for a particular table in NormalizeRecords, the name of the failing table is not visible to the user.
This PR includes the table name is included - this is the destination table name.
> ClickHouse: Include table name in error message in normalize records

- flow/connectors/mysql/cdc.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/sink_q.go
- flow/e2e/mysql.go
flush in an attempt to not have mysql sit on binlog
avoid segfault in query executor test (or any other code that assumes nil error must be non-nil query batch)
update gtidset on query event [based on canal](https://github.com/go-mysql-org/go-mysql/blob/417b93a01264f5e7b6e2d8700f4064be48394b68/canal/sync.go#L171)
> ci: address mysql flakiness

- flow/connectors/mysql/cdc.go
- flow/e2e/generic/generic_test.go
- flow/e2e/mysql.go
- flow/workflows/cdc_flow.go
ofc it doesn't fail when I'm trying to observe it fail in #2846..
https://dev.mysql.com/doc/refman/8.4/en/set-variable.html
> If you change a global system variable, the value is remembered and used to initialize the session value for new sessions until you change the variable to a different value or the server exits. The change is visible to any client that accesses the global value. However, the change affects the corresponding session value only for clients that connect after the change. **The global variable change does not affect the session value for any current client sessions (not even the session within which the global value change occurs).**
> maria ci: fix heisenbug

- flow/activities/flowable.go
- flow/activities/flowable_core.go
- flow/activities/snapshot_activity.go
Currently the only information logs we store in catalog is "pushed x records"
It is important for us to show users more than just that
Note that this PR pertains to the logs table in UI. It has nothing to do with alerting
This PR logs info about some key moments during replication:
- Setting up of target tables
- Setup of replication slot and publication
- Replication of all partitions in QRep/Initial load
- Schema changes
- Resync completion
- Source cleanup of drop flow
- Destination cleanup of drop flow
- Removal of tables from publication
- Addition of tables from publication
> Add more information logs for UI logs table

- codecov.yml
- flow/activities/flowable.go
- flow/cmd/mirror_status.go
- flow/e2e/api/api_test.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/e2e/postgres/qrep_flow_pg_test.go
- flow/shared/math.go
avoids flaky coverage percentage based on whether scheduled task fired during CI or not
> e2e: run heartbeat workflow explicitly

- flow/connectors/clickhouse/qrep.go
- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/e2e/clickhouse/clickhouse.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
- flow/workflows/snapshot_flow.go
- protos/flow.proto
- ui/app/mirrors/create/helpers/common.ts
Currently to construct the column selectors for the Insert into Select to ClickHouse in initial load, we get the columns from ClickHouse. 
This results in initial load failing if there is an extra column on target vs source. 
The reason we were using the CH schema and not the source schema here was so that column exclusion was automatically taken care of. But this caused an unideal situation where we support source having extra columns for initial load and ClickHouse having extra columns for CDC normalize.
This PR re-wires things to make initial load use the source schema and gives it column exclusion info
> Support ClickHouse having extra columns compared to source for initial load

- flow/alerting/classifier.go
- flow/alerting/classifier_test.go
> feat(classifier): mark statement timeout related errors as recoverable

- flow/cmd/handler.go
- flow/e2e/api/api_test.go
This PR adds a test to check if resync picks up added tables and they are well and truly part of the CDC pipeline. 
It is a follow-up of #2917
> Add API test for adding a table before a resync

- flow/alerting/classifier.go
Add more cases when "pushing to view" is not present, and instead it could be `select from <destinationTable>`
> feat(classifier): more nested query cases

- flow/cmd/validate_mirror.go
- flow/connectors/mysql/mysql.go
- flow/connectors/mysql/qrep.go
- flow/connectors/mysql/validate.go
- flow/connectors/snowflake/snowflake.go
- flow/e2e/api/api_test.go
- flow/workflows/snapshot_flow.go
1. MySQL connections were setting compression unconditionally, respect setting instead
2. remove unused Snowflake SQL
3. remove binlog/replication validation from peer creation so we can do initial load only mirrors for MySQL
4. make binlog/replication validation during mirror creation conditional on initial load only
5. change double quotes to backticks for statements we run on MySQL during initial load, brings us closer to supporting Vitess which can't handle ANSI_QUOTES
> [mysql] general fixes

- flow/alerting/alerting.go
When flowName is passed explicitly, it overrides the contextial flowName in output metric. This causes initial load mirrors overriding the contextual flowName as `clone_mirror_` and further causing it to be screwed up. Now the error metric will always have the parent flowName (mirror name) via the context
> fix(alerting): remove explicit flowName to prevent collision

- flow/activities/flowable.go
- flow/connectors/bigquery/bigquery.go
- flow/connectors/clickhouse/cdc.go
- flow/connectors/external_metadata/store.go
- flow/connectors/postgres/postgres.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/snowflake.go
- flow/workflows/cdc_flow.go
- flow/workflows/drop_flow.go
This is to avoid race conditions where `metadata_last_sync_state` is removed by `DropFlowDestination` BEFORE `DropFlowSource` is able to cancel the goroutine that may insert data into the table.
If we hit this race condition during a resync, batchIDs and offsets being from an older mirror can cause many subtle issues and potential data inconsistency
> [dropflow] move metadata_last_sync_state cleanup to last activity

- flow/workflows/cdc_flow.go
- flow/workflows/qrep_flow.go
this avoids activity living on past ContinueAsNew, which was causing races
> sync flow: explicitly cancel & wait on cancellation before finishing

- flow/alerting/classifier.go
recently got this error with `io.ReadFull(header) failed. err EOF` in stack trace
> classify mysql.ErrBadConn as EOF

- flow/e2e/api/api_test.go
- ui/app/mirrors/[mirrorId]/edit/page.tsx
This PR extends the existing (now called) `TestEditTablesBeforeResync` test in `api_test.go`.
This test is meant to cover editing tables and resyncing after these table edits to see how the mirror behaves.
The test can be divided into - setup, add table, remove table and resync. Relevant metadata checks are being done for the table edits.
1. Create the first table called `original`.
2. Create the second table called `added`.
3. Insert a row into `original`.
4. Insert a row into `added`.
5. Create a mirror with only `original` in the table mapping.
6. Wait for initial load of this mirror with `original` to complete.
7. Check if equal tables for `original`.
8. Pause the mirror.
9. Send a flow state change request to add the table - `added`.
10. Wait for `added` table's initial load to …
> Extend API test for resync

- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/connectors/s3/qrep.go
- flow/connectors/snowflake/qrep_avro_sync.go
- flow/connectors/utils/avro/avro_writer.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
- flow/internal/dynamicconf.go
- flow/shared/watchwriter.go
particularly useful for mysql when custom partition key isn't used, ideally this would be based on chunk file size
something like 32GiB would be ideal
might be easier to structure around file size after switching to hamba/avro/v2
> Initial load chunking

- flow/connectors/clickhouse/clickhouse.go
- ui/app/mirrors/create/cdc/customColumnType.tsx
- ui/app/mirrors/create/cdc/schemabox.tsx
- ui/app/mirrors/create/cdc/tablemapping.tsx
- ui/app/mirrors/create/handlers.ts
Create frontend for [custom column type conversion.](https://github.com/PeerDB-io/peerdb/pull/2989).
It creates a dropdown of possible conversions determined by the backend. Right now only numeric -> string is supported.
If there are no available conversion, the option for `use custom column destination type` will be hidden.
Test: locally created a table that contains column with numeric type, create ClickPipe via UI, and see CH table get created with String type.
> add frontend for fetching type conversion

- flow/connectors/postgres/qvalue_convert.go
Undo a small perf regression I accidentally introduced in https://github.com/PeerDB-io/peerdb/pull/3012.
I assume >99% of the time `PostgresOIDToQValueKind` does not return an error. O(1) is cheap but not free, and given this function is in the hot path for CDC, I'll be pedantic about it.
> fix small perf regression

- flow/connectors/mysql/qrep.go
- flow/connectors/utils/partition.go
- flow/e2e/api/api_test.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
1. Fix comparison of previous partition with current partition.
2. Use a different query to obtain logical partitions for MySQL
> MySQL: Improve parallel snapshot

- flow/cmd/peer_data.go
- flow/connectors/mongo/schema.go
Implement connector interface for fetching databases, tables, and columns. For now, ~we use hard-coded _destination_ columns as placeholders.~ return empty columns.
Open discussion: since Mongo is schemaless, fetching column types becomes nontrivial:
- scanning the entire dataset and infer data types is too expensive
- a more practical approach would be to sample a small subset of rows and give a best-effort data types.
> mongo: implement connector interface for fetching schemas

- flow/connectors/clickhouse/qrep_avro_sync.go
- Retrieve fresh AWS credentials for each part and chunk to prevent expiration during long-running operations
- Refactor chunk handling to process individual files instead of wildcards
- Changed pushDataToS3 to return array of AvroFile pointers
- Updated pushS3DataToClickHouse to process each chunk separately
- Add detailed logging for chunk and part processing for better debugging
This ensures reliable data loading for large datasets with multiple chunks and parts by preventing credential timeout errors and enabling proper per-file credential refresh.
> fix: improve S3 credential handling and chunk processing in ClickHouse sync

- flow/connectors/clickhouse/cdc.go
- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/clickhouse/normalize.go
- flow/connectors/clickhouse/normalize_query.go
- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
- flow/shared/clickhouse/escape.go
- flow/shared/clickhouse/validation.go
hit error due to ?s in column names
looking at clickhouse-go's bind.go, ? can be escaped as `\?`
but this doesn't apply when no params passed, in which case we need to not prepend `\`
also `$1` can't be escaped so queries which mix user supplied identifiers & params are never safe
conclusion: never use params, we already handle escaping strings ourselves in most cases
on handling escaping ourselves: cleanup code to call Quote functions more diligently
> ch: never use params

- flow/connectors/mongo/mongo.go
- flow/connectors/mongo/qrep.go
- flow/connectors/mongo/qvalue_convert.go
- flow/connectors/mongo/schema.go
Previously we assume that `_id` must be ObjectId type in mongoDB. 
However, it's possible for `_id` to contain other data types. To start,  keep `_id` simple by always converting to a string type in destination table. 
This PR also removed partitioning logic for now -- will evaluate `$bucketAuto` on large collections to determine if  it scales well. 
Lastly, this PR moved conversion logic to `qvalue_convert.go` so it can be used by both snapshot and cdc.
Testing:
> mongo: always  convert  `_id` to string  + no parallel initial load

- flow/connectors/mysql/cdc.go
- flow/connectors/mysql/metered_dialer.go
- flow/connectors/mysql/mysql.go
- flow/connectors/mysql/qrep.go
cdc: only count row events which aren't ignored
qrep: meter connection rather than making terrible estimate based on decoded row values
based on talking upstream (https://github.com/go-mysql-org/go-mysql/issues/1044) this was the recommended approach
> mysql: more accurate bean counting

- flow/e2e/mongo/mongo_test.go
Add e2e tests for:
- update/replace/delete events
- "schema evolution"
Testing: tests should pass CI, will then point to `mongo-ci` branch.
> mongo: add more CI test for mongo connector

- .github/workflows/flow.yml
- flow/connectors/mongo/mongo.go
- flow/e2e/mongo/mongo.go
- flow/e2e/mongo/mongo_test.go
- Test mongo versions 6.0/7.0/8.0 pass CI
- Create dedicated user for changestream and test authentication works as expected.
> mongo: test mongo versions 6.0/7.0/8.0 + authentication

- flow/connectors/clickhouse/cdc.go
- flow/connectors/clickhouse/clickhouse.go
- flow/connectors/clickhouse/normalize.go
- flow/connectors/clickhouse/normalize_query.go
- flow/connectors/clickhouse/normalize_test.go
- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/connectors/snowflake/merge_stmt_generator.go
- flow/connectors/snowflake/snowflake.go
- flow/e2e/clickhouse/clickhouse.go
- flow/e2e/mongo/mongo_test.go
- flow/internal/dynamicconf.go
- flow/model/qvalue/kind.go
Currently QValueJson gets converted to String in ClickHouse. For Mongo we want to be able to write `_full_document` as JSON type. This PR will default to JSON in CH if these are all true:
1) Schema is QValueJson
2) CH version supports JSON (25.3 is when JSON is first introduced)
3) JSON is enabled by FF (default to false)
Test: 
- e2e test
- tested locally, with FF on (as JSON) and off (as String)
Next step: look into enabling this setting by default -- but for Mongo only.
> mongo: allow write to JSON in CH when FF is enabled

- flow/internal/dynamicconf.go
seeing errors on smaller instances over memory consumption & taking too long to process 30GB
> Lower s3 chunking default from 33GB to 10GB

- .github/workflows/flow.yml
- flow/connectors/mongo/mongo.go
- flow/connectors/mongo/validate.go
- flow/shared/mongo/util.go
- flow/shared/mongo/validation.go
- Check mongo version for validation.
- Small refactors to use bson struct tags for deserialization.
- Extract shared logic to shared/mongo/validation.go
- Default read preference mode to SecondaryPreferred, which read from primary only if secondary does not exists -- we should still support read from primary via uri if user prefers, will work on this as a subsequent PR as we separate out username/password from rest of uri.
Test: locally tested deserialization.
> mongo: mongo version check during validation

- flow/connectors/utils/avro_writer.go
- flow/model/conversion_avro.go
- flow/model/qvalue/avro_converter.go
- flow/workflows/cdc_flow.go
During a parallel initial load from MySQL to ClickHouse, it was observed that the PeerDBBinaryFormat call in QValueToAvro which gets the value of the binary format dynamic setting from catalog was taking ~60% of CPU utilisation of the flow-worker pod.
Makes sense - making a call to Postgres for every single record can be expensive
This PR moves this fetch outside the loop on the pulled records.
Also some lint in `cdc_flow.go`
> MySQL: Move binary format fetch outside

- flow/activities/flowable.go
- flow/cmd/peer_data.go
- flow/connectors/core.go
- flow/connectors/mongo/mongo.go
- flow/connectors/mysql/cdc.go
- flow/connectors/mysql/mysql.go
- flow/connectors/postgres/postgres.go
- ui/app/peers/[peerName]/stattable.tsx
performance schema was added in 5.5
> mysql: stat activity

- .github/workflows/flow.yml
- flow/connectors/mongo/mongo.go
- flow/e2e/mongo/mongo_test.go
- flow/go.mod
- flow/go.sum
- nexus/analyzer/src/lib.rs
- protos/peers.proto
- ui/app/peers/create/[peerType]/helpers/mo.ts
- ui/app/peers/create/[peerType]/page.tsx
- ui/components/PeerForms/MongoForm.tsx
- Separate out username and password to separate fields.
- Add default client options - currently give user override options via connection string, we can also choose to ignore user options always use default 
- Add TLS support
- Apply corresponding changes to frontend.
TODO: verify TLS works as expected
> mongo: update config with fields for username/password/tls

- flow/connectors/mongo/mongo.go
- flow/connectors/mongo/qrep.go
- flow/connectors/mysql/qrep.go
- flow/connectors/utils/monitoring/monitoring.go
Follow-up to https://github.com/PeerDB-io/peerdb/pull/3180
~(not sure if `monitoring` is the right package or if there's a better place for this util function)~
> mongo: use same partial reporting mechanism as mysql

- flow/cmd/mirror_status.go
- flow/e2e/api/api_test.go
- protos/route.proto
Currently to get the total rows synced by a mirror across CDC and initial load, clients of our API would have to call `CDCTableTotalCounts` and `InitialLoadSummary` and in the case of the latter they would have to sum the `NumRowsSynced` field of all entries. Not to mention both these API calls would be overfetching if we just want a single count.
This PR introduces a new endpoint dedicated to getting the sum total rows synced by CDC and initial load.
An API test has been included.
> API endpoint for total rows synced by mirror

- flow/connectors/mongo/mongo.go
- nexus/analyzer/src/lib.rs
- protos/peers.proto
- ui/app/peers/create/[peerType]/helpers/mo.ts
Implement backend to support passing ReadPreference as an explicit mongo config setting via UI
> mongo: add read preference to mongo config

- flow/connectors/bigquery/bigquery.go
- flow/connectors/bigquery/qrep.go
- flow/connectors/clickhouse/normalize_query.go
- flow/connectors/eventhub/hubmanager.go
- flow/connectors/mongo/validate.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/ssh_wrapped_conn.go
- flow/connectors/pubsub/pubsub.go
- flow/connectors/snowflake/qrep.go
- flow/connectors/snowflake/qrep_avro_consolidate.go
- flow/connectors/snowflake/snowflake.go
- flow/connectors/utils/aws.go
- flow/workflows/cdc_flow.go
1. if-err cleanup
2. don't wait on sync to cancel when pausing, this was causing pausing to sometimes take 10+ seconds
3. set timezone UTC on postgres connections
4. parse datetime as UTC in ClickHouse
4 addresses this:
```
select parseDateTimeBestEffort('2025-07-11 19:30:02.313462+0000')
SELECT parseDateTimeBestEffort('2025-07-11 19:30:02.313462+0000')
Query id: 0d4bbad2-fdab-414f-85c8-2c80c61ad0ab
┌─parseDateTimeBestEffort('2025-07-11 19:30:02.313462+0000')─┐
│                                        2025-07-11 15:30:02 │
└────────────────────────────────────────────────────────────┘
```
where the ClickHouse server has a non-UTC timezone. The problem is our timezone hygiene isn't clear enough bringing data from postgres & ingesting into ClickHouse to handle this, between initial loads & …
> Timezone cleanup

- flow/connectors/mongo/mongo.go
- nexus/analyzer/src/lib.rs
- protos/peers.proto
- ui/app/peers/create/[peerType]/helpers/mo.ts
- ui/app/settings/page.tsx
Use enum instead of string for readPreference to match driver; more compact for wiring over the network as well.
> mongo: use enum for readPreference instead of string

- flow/connectors/utils/partition.go
Mongo's case handling is not correct. This didn't surface as an issue since we currently don't support partitioned load.
> mongo: fix bug in `getPartitionForStartAndEnd`

- flow/connectors/mongo/qrep.go
- flow/connectors/utils/monitoring/monitoring.go
- flow/shared/mongo/qrep.go
@Amogh-Bharadwaj  noticed an issue where initial load does not populate stats to db.
- Fix a bug where `nil` partition is returned.
- Make sure mongo also populate `qrep_partitions` table
Test: ran test locally and see that qrep_partition populated for mongo:
```
postgres=# select rows_synced, parent_mirror_name from qrep_partitions where parent_mirror_name = 'stats3';
rows_synced | parent_mirror_name
-------------+--------------------
4 | stats3
```
> mongo: always return full table partition

- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/connectors/s3/qrep.go
- flow/internal/dynamicconf.go
on prem customers were running into s3 "too many requests" errors, which can happen when blobs are uploaded with a common prefix
> s3/ch: PEERDB_S3_UUID_PREFIX

- flow/workflows/cdc_flow.go
- flow/workflows/snapshot_flow.go
- flow/workflows/util.go
- protos/flow.proto
or TERMINATED when workflow context canceled (probably means canceled through temporal ui)
partially addresses #3234
> update workflow status to FAILED when completing with error

- flow/connectors/mongo/cdc.go
- flow/connectors/mongo/resume_token.go
- flow/connectors/mongo/resume_token_test.go
- flow/e2e/mongo/mongo_test.go
See https://github.com/PeerDB-io/peerdb/issues/3246 for problem description.
Evaluated a few options:
1. persist previous table mapping so we can gracefully remove table from pipeline when we detect a table is deleted by doing so after changestream has been successfully resumed
- pro: relatively simple to implement
- con: need to store table mapping to catalog which may require db schema change
2. persist per-table resume tokens to `lastCheckpointText`, so we can always resume to a different table's token that exists in the pipeline
- pro: we can re-use `lastCheckpointText` without changing db schema
- con:  overhead of ser/deser resume tokens to/from string on checkpoint; more complex logic to find the "next best resume token" if last resumeToken doesn't work
3. decode resume token to …
> mongo: handle resume token from table not in changestream

- flow/activities/flowable.go
- flow/cmd/api.go
- flow/e2e/postgres/peer_flow_pg_test.go
- flow/main.go
- flow/workflows/register.go
- flow/workflows/scheduled_flows.go
Adds a flag to api so that it runs the scheduled tasks itself using a couple tickers rather than pushing this through temporal
Eventually this flag will be the default, & the old code path can be removed
Put it in api for now since we'd rather not introduce yet another process, & api process was already chosen for killing/starting scheduled tasks. This is because api pod isn't expected to need horizontal scaling
This greatly cleans up temporal ui being flooded in record-slot-size workflows, & reduce temporal costs
Closes #2380
> scheduled tasks as one long running activity

- flow/connectors/mongo/mongo.go
- flow/connectors/mongo/qrep.go
- flow/connectors/mysql/qrep.go
- flow/connectors/postgres/qrep.go
- flow/connectors/utils/partition.go
- flow/e2e/mongo/mongo_test.go
- stacks/mongo/init-mongo.sh
Need to give `WatermarkColumn` as input, otherwise falls back to full table partition.
Only `ObjectID` partitioning is supported, so it is intended for use with `_id` but should be general.
Also added "adjusted partitions" logic to MySQL
TODO testing
> [mongo] parallel snapshot for ObjectID key

- flow/activities/snapshot_activity.go
- flow/connectors/core.go
- flow/connectors/mongo/qrep.go
- flow/connectors/mysql/qrep.go
- flow/connectors/postgres/postgres.go
- flow/connectors/postgres/qrep.go
- flow/workflows/snapshot_flow.go
- protos/flow.proto
The PR adds a new activity, `GetDefaultPartitionKeyForTables,` during Snapshot, which is supposed to return the default "partition" key for each table if not overridden by the user. For Postgres, we check for PG14+ (when TID range scan was added), and if that is there, we also check if the Timescale extension is installed and for compressed hypertables. If any are found, disable the partition key for those.
For Mongo/MySQL it currently returns an empty key for every table. But can be changed.
> fallback to full table partitions for Timescale compressed hypertables

- flow/connectors/clickhouse/qrep_avro_sync.go
- flow/connectors/mongo/codec.go
- flow/connectors/mongo/codec_test.go
- flow/e2e/mongo/mongo_test.go
- Remove codec + test for float32 handling (Mongo does not have a float32 equivalent so everything coming from changestream is float64)
- With this change, CDC path honors Double from Mongo to ClickHouse. However, QRep path does not. Given the same codec is used for marshaling, the difference in behavior here has to with how we handle data in qrep vs cdc.  
```
07bd249d78c1 :) SELECT JSONExtractString('{"number": 1.0, "number2": 1.1}');
┌─JSONExtractSt⋯er2": 1.1}')─┐
1. │ {"number":1,"number2":1.1} │
└────────────────────────────┘
```
JSONExtractString converts `_full_document` column to JSON during initial load, erasing the explicit decimal and result in an Int64. Haven't thought of a good workaround for this without introducing a staging table similar to CDC.  Ideas welcome.
Update: …
> mongo: preserve float type from mongo to ch

- flow/connectors/kafka/kafka.go
- nexus/analyzer/src/lib.rs
- protos/peers.proto
- ui/app/peers/create/[peerType]/helpers/ka.ts
- ui/components/PeerForms/KafkaConfig.tsx
Hello there!
In our company we use custom certificates to authenticate to our Kafka instances. Unfortunately PeerDB doesn't support uploading custom certificates for Kafka peers.
This PR adds the possibility. The PR reuses the same logic as used for Clickhouse peers.
Thank you for your work, review, feedback & eventual merge ❤️🙏
> feat(kafka): add support for custom certificates

- flow/cmd/validate_mirror.go
- flow/connectors/clickhouse/validate.go
We get source schemas for validating destination tables' schemas, which in the case of resync we do not do. Hence no need to fetch schemas from source in the case of resync
> Validate mirror: no need to get source schemas for resync

- flow/connectors/mongo/codec_test.go
Really a nit but for the complete peace of mind
> Mongo codec: test more carefully around the float limit boundary

- flow/connectors/mongo/validate.go
- flow/shared/mongo/commands.go
- flow/shared/mongo/validation.go
Change Streams API is documented to work out-of-the-box for sharded cluster. This PR updates the shared validation code to:
- check to make sure that the instance is either replica set or sharded cluster (previously, it ran `replSetGetStatus` to check this, we can instead use 'hello' command which is more general)
- add explicit validation for required roles (`readAnyDatabase`, `clusterMonitor`)
- better separation of concern by creating a `commands.go` file for all the db commands, while `validation.go` implements the validation logic -- will follow up with ClickPipes side as well. 
Testing:
> mongo: enable ShardedCluster + better code sharing for validation

- flow/connectors/mongo/schema.go
- flow/shared/mongo/schema.go
Moved ListDatabases and ListSchema to shared logic for reuse.
Test: validated logic locally in peerdb, system dbs/tables and views are not included.
> mongo: move schema logic to shared logic

- flow/activities/flowable.go
- flow/activities/flowable_core.go
- flow/connectors/clickhouse/normalize.go
- flow/internal/dynamicconf.go
- flow/shared/concurrency/lastchan.go
tracks changes to atomic.Int64 so normalization always receives latest value,
each update closing a series of channels for synchronization
> replace normalize requests channel

- flow/connectors/postgres/cdc.go
- flow/otel_metrics/otel_manager.go
Before we disable anything, let's first see if the store is helping and how often we're still producing nulls
> Add a metric for backfilled TOAST values from CDC store

- flow/activities/flowable_core.go
- flow/connectors/clickhouse/avro_sync.go
- flow/connectors/clickhouse/normalize.go
- flow/connectors/external_metadata/store.go
- flow/connectors/mongo/cdc.go
- flow/connectors/mongo/mongo.go
- flow/connectors/mongo/qrep.go
- flow/connectors/mysql/cdc.go
- flow/connectors/mysql/mysql.go
- flow/connectors/mysql/qrep.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/qrep.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/sink_q.go
- flow/connectors/utils/avro_writer.go
- flow/connectors/utils/metered_dialer.go
- flow/model/cdc_stream.go
If something is slow, hanging or not hanging, we should be able to tell what it is from logs.
Add progress logs where they're missing, in pull, sync, normalize, qrep/cdc
Standardize cadence to 50000 records (10000 in OCF is a bit spammy)
Consistently log # of records, bytes, channel length (correlated with memory consumed by that pipe/partition), whether we're waiting for commit
Tabulate start/end for long running operations
Unify names of some properties so we can do a column in grafana
Rename CH qrep_avro_sync.go to avro_sync.go as it's actually shared with CDC
> Log all progress

- flow/shared/constants.go
Quick and dirty way to reduce memory usage when snapshot parallelism is too big for the node. Current channel size is 256K, previous value (#315) was 16K, so going to 128K should help with memory but not be too low.
> Reduce QRep channel size

- flow/activities/flowable_core.go
- flow/connectors/core.go
Implementation in https://github.com/PeerDB-io/peerdb/pull/3367 misses the fact that GetConnector which we call under the hood opens a destination connection, and only after we successfully get a connector do we assert that the connector supports T.
This PR clones GetByNameAs and passes in an `expectedType` parameter which is used to error out with unsupported early
> Last offset fetch: prevent destination connection by returning early

- flow/connectors/mongo/cdc.go
- flow/connectors/mongo/mongo.go
- flow/connectors/mongo/qrep.go
- flow/e2e/mongo/mongo.go
- flow/e2e/mongo/mongo_test.go
- flow/shared/constants.go
Shorten default name from `_full_document` to `doc`.
> mongo: shorten _full_document to doc

- flow/activities/flowable.go
- flow/internal/catalog.go
health check only runs once a minute, so pool wasn't aggressively culled
meanwhile MinConns counterbalance keeps cold services lukewarm
> catalog pool: don't set MinConns to 1

- flow/activities/flowable.go
- flow/connectors/mysql/cdc.go
- flow/connectors/postgres/cdc.go
@ilidemi noticed 10% of cpu usage in pg/mysql was attributed to metrics
reuse pattern used by qrep where we add to atomic counters & regularly empty those counters
mongo cdc already does this
> pg/mysql cdc: report fetched bytes metric with interval

- flow/alerting/alerting.go
- flow/alerting/classifier.go
many libraries create this error themselves, & check this way, as historically go did not expose net.ErrClosed type
> explicit check for "use of closed network connection" suffix

- flow/activities/flowable_core.go
Missed a code path in https://github.com/PeerDB-io/peerdb/pull/3296
This PR catches non-desync temporal app errors which includes missing slot and publication in PullRecords. Functionally tested
> Catch missing slot / publication for alerting in PullRecords

- flow/alerting/classifier.go
this occurs when server removed thread, often due to connection errors
> mysql: classify ER_NO_SUCH_THREAD as connection error

- flow/connectors/mongo/codec.go
- flow/connectors/postgres/cdc.go
- flow/connectors/postgres/json.go
- flow/connectors/postgres/json_test.go
- flow/connectors/postgres/qrep_query_executor.go
- flow/connectors/postgres/qrep_query_executor_test.go
- flow/e2e/clickhouse/peer_flow_ch_test.go
Python transparently makes ints bigints, serializes to JSON as is, PG accepts that JSON, then we and CH can't consume that JSON. Go can produce such JSON too if you put a big.Int in there
The software that hit this is https://github.com/JudgmentLabs/judgeval and we're The leading database for AI
Add a custom decoder so that we replace what we can't parse into float64 with strings. This is backcompatible because only the values that were previously failing would see the new behavior and succeed
> Support very long numbers as strings in PG JSON

- flow/alerting/classifier.go
- flow/connectors/postgres/cdc.go
- flow/model/model.go
- flow/shared/exceptions/primary_key_modfied.go
~~PG requested WAL segment ... has already been removed with 58P01 seems to be non-retryable~~
Neon NeonWALPageRead is constantly reoccurring on one service and comes after we read 0 records for a while while the slot is growing
Our CDC store doesn't allow private key columns to be dropped so that's not recoverable but when we remove CDC store we could defer that to Postgres to decide
> Classify more errors

- flow/connectors/mongo/cdc.go
- flow/connectors/mysql/cdc.go
- flow/connectors/postgres/cdc.go
- flow/connectors/utils/avro_writer.go
A neon peer was pulling records for longer than the batch timeout but unclear why
Also their batch time was 3 hours so hard to browse through the logs
> Minor: improve CDC logging

- flow/connectors/mysql/mysql.go
This PR is a breaking change across resyncs and new MySQL mirrors, as it changes the way we obtain timestamp values from source in initial load.
Fixes #3457 
When we do a SELECT in MySQL in initial load, timestamp column values are retrieved in wall-clock fashion which is then treated as UTC downstream and in ClickHouse.
For example if your ClickHouse server has its global timezone setting set to UTC + 7 and on MySQL server the timezone is UTC + 5:30, and on MySQL you have a timestamp value of 10am today, after initial load once you do a SELECT on the ClickHouse table you will see it as 5pm (17:00) today.
The source MySQL server timezone is not being accounted for here.
When we insert the same 10 am today row during CDC and inspect the binlog, we see something like:
```
#250916 12:53:42 …
```
> MySQL: explicitly set timezone at session to UTC

- flow/connectors/clickhouse/normalize_query.go
We set `throw_on_max_partitions_per_insert_block` in initial load INSERTs to ClickHouse and the same reasoning for that applies to our INSERTs in CDC normalize as well.
This PR thus adds this setting to our ClickHouse inserts.
> ClickHouse: Add setting throw_on_max_partitions_per_insert_block in CDC

- flow/alerting/classifier.go
- flow/alerting/classifier_test.go
These errors are independent of databases, and should be returned as the underlying error instead of being wrapped by a database library-specific error and classified there.
> [classifier] move net error classifications above per-db

- flow/connectors/utils/monitoring/monitoring.go
Move PeerDBMetricsRecordAggregatesEnabled check before transaction start
to avoid nested catalog pool connection acquisition. Previously, the
function would:
1. Acquire connection for transaction (pool.Begin)
2. Call PeerDBMetricsRecordAggregatesEnabled which internally acquires another connection via `dynLookup > GetCatalogConnectionPoolFromEnv`
With concurrent calls and pool size of 3, all connections would be held
by transactions while each waited for a 4th connection to check the
dynamic config, causing deadlock with idle transactions stuck in BEGIN.
Fixes deadlock observed with 3 connections in "idle in transaction"
state blocking all subsequent catalog operations.
> fix(monitoring): prevent catalog pool deadlock in AddCDCBatchTablesForFlow

- flow/alerting/classifier.go
Mongo like to use value receiver for error implementations instead of pointer receiver.
> mongo connector sse error handling

- flow/alerting/classifier.go
Catches:
> The last transaction was aborted due to Zero Downtime Patch. Please retry.
> The last transaction was aborted due to Zero Downtime Restart. Please retry.
and any other similar errors of this sort.
> MySQL retryable error
