flow/connectors/postgres/postgres.go, flow/connectors/postgres/qrep.go, flow/connectors/postgres/qrep_sync_method.go, flow/e2e/qrep_flow_test.go, flow/model/qrecord_batch.go
Only multi-insert mode which is infact using copy from binary which makes it more efficient.
=> [postgres] Support QueryReplication for Postgres

flow/activities/flowable.go, flow/connectors/bigquery/qrep.go, flow/connectors/core.go, flow/connectors/postgres/qrep.go, flow/connectors/snowflake/qrep.go, flow/connectors/snowflake/qrep_avro_sync.go, flow/workflows/qrep_flow.go
drop the stage towards the end after copy to dest
=> Consolidate all the partitions into one stage

docker-compose.yml, flow/activities/fetch_config.go, flow/cmd/api.go, flow/connectors/bigquery/qrep.go, flow/connectors/bigquery/qrep_sync_method.go, nexus/Cargo.lock, nexus/analyzer/Cargo.toml, nexus/analyzer/src/lib.rs, nexus/catalog/Cargo.toml, nexus/catalog/migrations/V4__add_query_string_to_flows.sql, nexus/catalog/src/lib.rs, nexus/flow-rs/src/lib.rs, nexus/pt/src/lib.rs, nexus/server/src/main.rs, stacks/catalog.docker-compose.yml, stacks/nexus.Dockerfile
=> wiring for creating mirror for select (Qrep)

flow/connectors/postgres/qrep_query_executor.go, flow/connectors/postgres/qrep_query_executor_test.go
- This is in a series of commits where i try to increase the test coverage.
=> [postgres] Add tests for qrep query executor

flow/connectors/postgres/qrep.go, flow/connectors/postgres/qrep_partition_test.go, flow/connectors/postgres/qrep_query_executor.go, flow/connectors/postgres/qrep_query_executor_test.go
- Also make the ranges open bounded `[start, end)`, this makes it easy to reason about things.
=> Add tests for Postgres connector

docker-compose.yml, flow/cmd/worker.go, flow/connectors/bigquery/qrep_avro_sync.go, flow/connectors/postgres/qrep_query_executor.go, flow/connectors/snowflake/snowflake.go, flow/model/conversion_avro.go, flow/model/qrecord_batch.go, flow/model/qvalue/avro_converter.go, stacks/flow-api.Dockerfile, stacks/flow-worker.Dockerfile
- fix null timestamp and numeric value
=> Fix wiring up profiling

nexus/Cargo.lock, nexus/parser/Cargo.toml, nexus/parser/src/lib.rs, nexus/peer-bigquery/Cargo.toml, nexus/peer-cursor/Cargo.toml, nexus/peer-postgres/Cargo.toml, nexus/peer-postgres/src/stream.rs, nexus/peer-snowflake/Cargo.toml, nexus/server/Cargo.toml, nexus/server/src/main.rs, nexus/value/Cargo.toml
1. Nested Empty statements must be handled
2. Better handling from name and name array types
=> Fix issues that prevented DataGrip from connecting to PeerDB

docker-compose.yml, flow/cmd/main.go
- there were inconsistencies before this fixes it
=> use PEERDB_CATALOG_DATABASE instead of PEERDB_CATALOG_DB

flow/cmd/api.go, flow/e2e/peer_flow_eh_test.go, flow/e2e/peer_flow_test.go, flow/workflows/peer_flow.go
- this is important for history size considerations
=> make peer flow continue as new

flow/connectors/postgres/qrep.go
fix https://github.com/PeerDB-io/peerdb/issues/217
=> When partitions overlap adjust to make them exclusive

nexus/Cargo.lock, nexus/Cargo.toml, nexus/catalog/Cargo.toml, nexus/catalog/src/lib.rs, nexus/peer-postgres/Cargo.toml, nexus/peer-postgres/src/lib.rs, nexus/postgres-connection/Cargo.toml, nexus/postgres-connection/src/lib.rs, nexus/server/src/main.rs
We don't verify the server cert yet, this matches the default behaviour of psql.
=> Allow connecting to servers that enforce tls

nexus/Cargo.lock, nexus/peer-cursor/src/util.rs, nexus/peer-postgres/Cargo.toml, nexus/peer-postgres/src/stream.rs, nexus/server/tests/assets/seed.sql, nexus/server/tests/results/expected/postgres.sql.out, nexus/server/tests/sql/postgres.sql, nexus/value/Cargo.toml, nexus/value/src/lib.rs
Supports querying these types. 
8 tests added
=> INET and CIDR support for PostgreSQL Query Layer

flow/activities/flowable.go, flow/connectors/bigquery/qrep.go, flow/connectors/bigquery/qrep_avro_sync.go, flow/connectors/bigquery/qrep_sync_method.go, flow/connectors/core.go, flow/connectors/eventhub/qrep.go, flow/connectors/postgres/qrep.go, flow/connectors/postgres/qrep_sync_method.go, flow/connectors/s3/qrep.go, flow/connectors/snowflake/avro_file_writer_test.go, flow/connectors/snowflake/qrep.go, flow/connectors/snowflake/qrep_avro_sync.go, flow/connectors/sqlserver/qrep.go, flow/connectors/utils/avro/avro_writer.go, flow/model/qrecord_batch.go, flow/model/qrecord_stream.go
- only implemented for SyncQRepRecords for now
- shortly will follow it up with cursor based impl for postgres
=> Add QRecordStream for streaming the query replication

flow/activities/flowable.go, flow/connectors/bigquery/qrep_avro_sync.go, flow/connectors/bigquery/qrep_sync_method.go, flow/connectors/postgres/qrep.go, flow/connectors/postgres/qrep_query_executor.go, flow/connectors/utils/avro/avro_writer.go, flow/connectors/utils/metrics/metrics.go, flow/e2e/peer_flow_s3_test.go, flow/e2e/qrep_flow_test.go, flow/model/qrecord_stream.go
- Add the functionality to pull pg records in stream
- This wille eventually extend to all the pullable sources
=> [postgres] pull qrep records in a stream

flow/connectors/bigquery/qrep_avro_sync.go, flow/connectors/utils/logrus.go
- Adds stream splitting for logrus
- Adds heartbeat messages at many places in BigQuery Avro sync functions
=> Better Go and Activity Logs

flow/connectors/bigquery/bigquery.go, flow/connectors/bigquery/merge_stmt_generator_test.go, flow/utils/random.go
- Backticks for columns to account for keywords
- Unique temporary table name
=> Fix statements in normalize flow

flow/connectors/postgres/client.go, flow/workflows/snapshot_flow.go
- Destination name as variable in `cloneTables()`
- Fixes normalize statement in Postgres CDC
- Logs in `snapshot_flow.go`
=> Fixes for Snapshot Flow

docker-compose.yml, flow/cmd/main.go, flow/cmd/worker.go, flow/connectors/postgres/cdc.go, flow/connectors/postgres/postgres_cdc_test.go, flow/go.mod, flow/go.sum, flow/model/model.go, flow/workflows/peer_flow.go
- also use pyroscope for better info
=> Pass QValue by pointer to significantly reduce gc pressure

nexus/server/src/main.rs
Improper locking of the catalog in the mirror for select query handler was causing it to hang. This PR fixes that
=> Fixes catalog locking

flow/connectors/sql/query_executor.go, nexus/catalog/src/lib.rs, nexus/flow-rs/src/grpc.rs
- Better UUID mapping for SQL Server
- Better Create Peer experience
=> SQL Server Improvements

.gitignore, README.md
- Prevent OOM when building docker images
- Add compatible psql versions
=> docs: add requirements for building docker images and connecting to peerdb

flow/connectors/eventhub/eventhub.go, flow/connectors/eventhub/hub_batches.go, flow/connectors/eventhub/hubmanager.go, flow/connectors/utils/env.go
`PEERDB_BETA_EVENTHUB_PUSH_ASYNC=true` enables this
=> Add the ability to push to eventhubs in an asynchronous way

docker-compose.yml, flow/cmd/api.go, flow/cmd/main.go, flow/cmd/snapshot_worker.go, flow/cmd/worker.go
=> added env var for configuring Temporal namespace

flow/connectors/postgres/cdc.go
This reverts commit 41dfd4f024caa432feb7deef89659108ae421fe6.
=> Revert "for eventhub disable commit lock (#546)"

flow/activities/flowable.go, flow/connectors/utils/env.go
`PEERDB_CDC_IDLE_TIMEOUT_SECONDS` is the env var
=> Make idle timeout configurable

ui/app/api/peers/route.ts, ui/app/peers/create/[peerType]/handlers.ts, ui/app/peers/create/[peerType]/page.tsx
- Fixes enum comparison in create peer api call
=> UI improvements in create peer

flow/connectors/postgres/cdc.go, flow/connectors/utils/heartbeat.go, flow/workflows/sync_flow.go
=> added timeout for long CDC pulls

nexus/analyzer/src/qrep.rs, ui/app/mirrors/create/handlers.ts, ui/app/mirrors/create/helpers/qrep.ts, ui/app/mirrors/create/qrep.tsx
Asserts unique_key_columns parameter for upsert mode in QRep
=> Asserts unique_key_columns parameter

flow/cmd/peer_data.go, ui/app/api/mirrors/cdc/route.ts, ui/app/mirrors/create/cdc.tsx, ui/app/peers/[peerName]/datatables.tsx, ui/app/peers/[peerName]/helpers.tsx
Uses peer's user for postgres peer stats
For destination peer as postgres - default sync modes (cdc and snapshot) is copy with binary aka sql
For destination peer as snowflake, it's avro
=> Improvements for Stats and Mirror Create UI 

ui/app/dto/MirrorsDTO.ts, ui/app/mirrors/create/handlers.ts, ui/app/mirrors/create/page.tsx, ui/app/mirrors/create/tablemapping.tsx, ui/components/Search.tsx
Uses one state value throughout the table list component
=> Lint: Better state management in TableMapping

.github/workflows/ci.yml, .github/workflows/customer-docker.yml, .github/workflows/dev-docker.yml, .github/workflows/flow.yml, .github/workflows/golang-lint.yml, .github/workflows/rust-lint.yml, .github/workflows/stable-docker.yml, .github/workflows/ui-build.yml, .github/workflows/ui-lint.yml
Makes CI stricter so that it currently be fails until #621 merged
=> ci: eslint --max-warnings 0

nexus/server/src/main.rs
Not sure how to write tests for this crate, but this updates psql interface to reject
```sql
CREATE MIRROR m FROM source TO target WITH (s.t1:s.t2, s.t1:s.t3)
CREATE MIRROR m FROM source TO target WITH (s.t1:s.t3, s.t2:s.t3)
```
As this kind of mirror doesn't work today & is support is not prioritized
This leaves capability to create these kinds of broken mirrors over grpc open, that should be alright since this change's goal is to fail fast for users to know what's allowed
=> nexus/server: reject duplicate source tables or duplicate target tables

nexus/Cargo.lock, nexus/analyzer/Cargo.toml, nexus/analyzer/src/qrep.rs
Use of Vec can be replaced with slices in QREP_OPTIONS, making it const
=> nexus/analyzer: remove unnecessary lazy_static

stacks/peerdb-server.Dockerfile
https://blog.rust-lang.org/2023/07/13/Rust-1.71.0.html
https://blog.rust-lang.org/2023/08/24/Rust-1.72.0.html
https://blog.rust-lang.org/2023/10/05/Rust-1.73.0.html
https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html
No vital changes here
=> peerdb-server.Dockerfile: rust 1.74

dev-peerdb.sh, docker-compose-dev.yml, docker-compose.yml, stacks/peerdb-ui.Dockerfile
Also clean up peerdb-ui.Dockerfile a bit
=> temporalio: update images

docker-compose-dev.yml, docker-compose.yml
Sets `PEERDB_PASSWORD` responsible for UI login to empty so that users can use the UI without hinderance
=> Set UI password empty

ui/app/api/login/route.ts, ui/app/login/page.tsx, ui/app/mirrors/layout.tsx, ui/app/peers/layout.tsx, ui/components/Logout.tsx
Polishes UI of login screen and makes logout button appear everywhere (not just home page)
=> Login improvements

docker-compose-dev.yml, docker-compose.yml
This will enable advanced visibility and support other filters and search attributes
=> Use pg12 for temporal

ui/app/peers/[peerName]/datatables.tsx, ui/app/peers/[peerName]/page.tsx, ui/app/peers/[peerName]/slottable.tsx, ui/app/peers/[peerName]/stattable.tsx, ui/app/peers/[peerName]/style.ts, ui/components/CopyButton.tsx
- Displays connection string for postgres peer
- Search bar for query in stats table
=> UI: Better postgres peer page

ui/app/peers/[peerName]/page.tsx
Removes the connection string display in postgres peer page
=> Remove connection string display

ui/app/mirrors/edit/[mirrorId]/aggregatedCountsByInterval.ts, ui/app/mirrors/edit/[mirrorId]/cdc.tsx, ui/app/mirrors/edit/[mirrorId]/syncStatusTable.tsx, ui/app/mirrors/status/qrep/[mirrorId]/page.tsx, ui/app/mirrors/status/qrep/[mirrorId]/qrepConfigViewer.tsx, ui/app/mirrors/status/qrep/[mirrorId]/qrepGraph.tsx, ui/app/mirrors/status/qrep/[mirrorId]/qrepStatusTable.tsx, ui/app/utils/graph.ts
Changes default to Batch ID by descending in CDC page:
=> Adds sort buttons, graph for qrep

flow/activities/flowable.go, flow/activities/snapshot_activity.go, flow/connectors/bigquery/qrep_avro_sync.go, flow/connectors/eventhub/eventhub.go, flow/connectors/postgres/cdc.go, flow/connectors/postgres/postgres_repl_test.go, flow/connectors/postgres/qrep_query_executor.go, flow/connectors/postgres/slot_signal.go, flow/connectors/snowflake/qrep_avro_sync.go, flow/connectors/utils/avro/avro_writer.go, flow/connectors/utils/heartbeat.go
Slight perf optimization that also clearly indicates that the value given to channel does not mean anything
=> Replace `chan bool` with `chan struct{}`

.github/workflows/ci.yml, .github/workflows/flow.yml, .github/workflows/golang-lint.yml, .github/workflows/rust-lint.yml, .github/workflows/ui-build.yml
Testing Ubicloud's ARM support
=> ubicloud-standard-2-ubuntu-2204-arm

flow/cmd/version.go
I missed adding this in a previous commit
=> Re-add versions.go

ui/app/mirrors/create/page.tsx, ui/app/mirrors/edit/[mirrorId]/cdc.tsx, ui/app/mirrors/edit/[mirrorId]/syncStatusTable.tsx, ui/app/mirrors/status/qrep/[mirrorId]/qrepStatusTable.tsx, ui/components/SelectSource.tsx
- Adds Sort Option for QRep Table
- Fixes width issue of Select components where when typing it shrinks
- Align table button options better
- Set sort for initial copy to be descending by default
=> More Sort UI

docker-compose-dev.yml, docker-compose.yml, scripts/mirror-name-search.sh
Also add shebang & update docker-compose to execute script directly
=> chmod +x scripts/mirror-name-search.sh

.github/workflows/dev-docker.yml
these are provisioning latency sensitive
=> use ubuntu latest for dev-docker

flow/connectors/bigquery/bigquery.go, flow/connectors/bigquery/qrep_avro_sync.go
Bigquery DDLs take a while to propagate, we need to wait.
=> bigquery add wait for table

flow/connectors/bigquery/merge_statement_generator.go, flow/connectors/snowflake/qrep.go, flow/connectors/utils/array.go, flow/connectors/utils/map.go, flow/e2e/test_utils.go, flow/model/model.go
Also pass map size hints in a few more places
=> Use maps.Keys where applicable

flow/activities/flowable.go, flow/connectors/bigquery/bigquery.go, flow/connectors/core.go, flow/connectors/eventhub/eventhub.go, flow/connectors/external_metadata/store.go, flow/connectors/postgres/cdc.go, flow/connectors/postgres/postgres.go, flow/connectors/s3/s3.go, flow/connectors/snowflake/snowflake.go, flow/model/model.go
Only keep `LastSyncState` around enough for backwards compatibility
=> GetLastOffset: return int64

ui/app/mirrors/create/cdc/cdc.tsx, ui/app/mirrors/create/cdc/columnbox.tsx, ui/app/mirrors/create/cdc/schemabox.tsx, ui/app/mirrors/create/cdc/tablemapping.tsx
- Fixes SelectAll and SchemaExpand issues
- Moves Column view to separate component for readability
- Moves table picker below the settings for CDC and has more height
- useMemo for table search
- overall code improvements
=> UI: Improve table picker component

flow/.golangci.yml, flow/connectors/postgres/cdc.go, flow/connectors/postgres/client.go, flow/connectors/postgres/qrep_partition_test.go, flow/connectors/postgres/qrep_query_executor_test.go, flow/connectors/postgres/qvalue_convert.go, flow/connectors/snowflake/avro_file_writer_test.go, flow/connectors/snowflake/client.go, flow/connectors/snowflake/snowflake.go, flow/connectors/sql/query_executor.go, flow/connectors/sqlserver/qrep.go, flow/connectors/utils/cdc_records/cdc_records_storage.go, flow/connectors/utils/cdc_records/cdc_records_storage_test.go, flow/e2e/bigquery/peer_flow_bq_test.go, flow/e2e/bigquery/qrep_flow_bq_test.go, flow/e2e/postgres/peer_flow_pg_test.go, flow/e2e/postgres/qrep_flow_pg_test.go, flow/e2e/s3/cdc_s3_test.go, flow/e2e/s3/qrep_flow_s3_test.go, flow/e2e/snowflake/peer_flow_sf_test.go, flow/e2e/snowflake/qrep_flow_sf_test.go, flow/e2e/snowflake/snowflake_schema_delta_test.go, flow/e2e/sqlserver/qrep_flow_sqlserver_test.go, flow/e2e/test_utils.go, flow/peerdbenv/config.go
durationcheck, nolintlint, sqlclosecheck, thelper
=> flow: enable more lints

.github/workflows/flow.yml, flow/connectors/utils/cdc_records/cdc_records_storage_test.go, flow/e2e/bigquery/bigquery_helper.go, flow/e2e/bigquery/peer_flow_bq_test.go, flow/e2e/s3/s3_helper.go, flow/e2e/snowflake/peer_flow_sf_test.go, flow/e2e/snowflake/snowflake_helper.go, flow/e2e/snowflake/snowflake_schema_delta_test.go, flow/e2e/test_utils.go, flow/e2eshared/e2eshared.go
Splitting up changes from #871
=> e2eshared & remove testify/suite from cdc_records_storage_test.go

flow/connectors/utils/cdc_records/cdc_records_storage.go, flow/connectors/utils/cdc_records/cdc_records_storage_test.go
=> Fix time encoding

flow/connectors/postgres/postgres_repl_test.go, flow/connectors/postgres/postgres_schema_delta_test.go, flow/e2e/bigquery/peer_flow_bq_test.go, flow/e2e/bigquery/qrep_flow_bq_test.go, flow/e2e/congen.go, flow/e2e/postgres/peer_flow_pg_test.go, flow/e2e/postgres/qrep_flow_pg_test.go, flow/e2e/s3/cdc_s3_test.go, flow/e2e/s3/qrep_flow_s3_test.go, flow/e2e/snowflake/peer_flow_sf_test.go, flow/e2e/snowflake/qrep_flow_sf_test.go, flow/e2e/snowflake/snowflake_schema_delta_test.go, flow/e2e/sqlserver/qrep_flow_sqlserver_test.go, flow/e2e/test_utils.go, flow/e2eshared/e2eshared.go
Accidentally merged #871 (for some reason automerge triggered after merge with 0/6 CI steps complete)
=> Revert "Remove use of testify/suite"

ui/grpc_generated/google/protobuf/descriptor.ts, ui/grpc_generated/google/protobuf/timestamp.ts
When I run generate_protos.sh I get a different result, is my environment outdated?
Maybe this should be a CI check
=> Regenerate protobuf files

README.md
Post #949, can't do local development without generating protos first.
=> updating README for protobuf generation

flow/connectors/bigquery/bigquery.go
Resync works by performing initial load to a table with the suffix `_resync`, renaming it to the destination table name and then resuming CDC. This ensures maximum availability of the table for the customer as the downtime is scoped to the renaming phase.
Since soft-deleted rows are not present on the source, this can lead to such rows disappearing after resync, as initial load just copies the source tables over.
This is fixed by adding an additional step to `INSERT` rows from the destination table with primary keys not present in the `_resync` table, before the renaming. This ensures all soft-deleted rows are captured and retained after resync. The synced at column is also updated for these rows.
=> fixed interactions with soft delete and CDC resync

flow/cmd/mirror_status.go, flow/geo/geo.go, flow/workflows/snapshot_flow.go
also format mirror_status.go & remove nolint:all from geo.go
=> propagate errors from cloneTables

flow/workflows/snapshot_flow.go
for a hotfix, will be reverted shortly
=> Return nil snapshot

flow/workflows/snapshot_flow.go
undoing earlier PR as part of hotfix
=> undoing early return

flow/activities/flowable.go, flow/connectors/bigquery/qrep_avro_sync.go, flow/connectors/eventhub/eventhub.go, flow/connectors/postgres/cdc.go, flow/connectors/postgres/qrep_query_executor.go, flow/connectors/snowflake/qrep_avro_sync.go, flow/connectors/utils/avro/avro_writer.go, flow/connectors/utils/heartbeat.go
#1020 reverted #997
Reimplement so only func declaration moves into HeartbeatRoutine
=> HeartbeatRoutine: return cancel func instead of chan struct{}

flow/e2e/bigquery/peer_flow_bq_test.go, flow/e2e/postgres/peer_flow_pg_test.go, flow/e2e/postgres/qrep_flow_pg_test.go, flow/e2e/snowflake/peer_flow_sf_test.go, flow/e2e/test_utils.go
Adds tests for enum for postgres, bigquery and snowflake. We wish for enums to be texts on the destination
=> Add tests for enum

flow/cmd/mirror_status.go, ui/app/api/alert-config/route.ts, ui/app/api/mirrors/alerts/route.ts, ui/app/mirrors/edit/[mirrorId]/page.tsx, ui/app/mirrors/page.tsx, ui/app/mirrors/status/qrep/[mirrorId]/page.tsx, ui/app/mirrors/status/qrep/[mirrorId]/qrepConfigViewer.tsx, ui/app/peers/[peerName]/page.tsx
Removes dynamic rendering forcing in a lot of places, adds some logs to grpc backend
=> UI improvement For Harp

docker-compose-dev.yml, docker-compose.yml
Must specify http or else the callback upon login fails
=> Fix nextauth url in docker compose files

flow/connectors/bigquery/bigquery.go, flow/connectors/bigquery/merge_stmt_generator.go, flow/connectors/bigquery/merge_stmt_generator_test.go
partitioning based on unchanged toast columns wasn't being done right
=> fix a mistake in generating merge statements

flow/connectors/eventhub/eventhub.go, flow/connectors/eventhub/hub_batches.go, flow/connectors/eventhub/hubmanager.go, flow/connectors/eventhub/scoped_eventhub.go
=> Enable partition routing

flow/connectors/bigquery/merge_stmt_generator.go
#1062 renamed parameter #1066 used
=> Fix regression due to merge mixup between fixes & lints

flow/cmd/peer_data.go
In UI we get data from `information_schema.table_constraints` for primary key based filtering.
This can be unreliable as according to [postgres docs](https://www.postgresql.org/docs/current/infoschema-table-constraints.html), it won't work for read-only users.
This PR modifies two of our queries we use for the table picker to not use this view
=> UI: Remove use of information_schema.table_constraints

flow/activities/flowable.go, flow/connectors/bigquery/bigquery.go, flow/connectors/core.go, flow/connectors/eventhub/eventhub.go, flow/connectors/postgres/postgres.go, flow/connectors/s3/s3.go, flow/connectors/snowflake/snowflake.go, flow/model/model.go
=> Remove InitializeTableSchema

nexus/Cargo.lock, nexus/Cargo.toml, nexus/parser/Cargo.toml, nexus/peer-bigquery/Cargo.toml, nexus/peer-cursor/Cargo.toml, nexus/peer-postgres/Cargo.toml, nexus/peer-snowflake/Cargo.toml, nexus/server/Cargo.toml, nexus/server/src/main.rs, nexus/value/Cargo.toml
Changes necessary because of
1. https://github.com/sunng87/pgwire/pull/144
2. https://github.com/sunng87/pgwire/pull/147
Tests were failing due to hanging in 0.19.0, [0.19.1 fixed hang](https://github.com/sunng87/pgwire/pull/148)
=> pgwire 0.19

flow/connectors/eventhub/eventhub.go, flow/connectors/postgres/postgres.go, flow/connectors/postgres/qrep_sync_method.go, flow/connectors/postgres/qvalue_convert.go, flow/connectors/utils/postgres.go, flow/e2e/postgres/peer_flow_pg_test.go, flow/e2e/test_utils.go, flow/geo/geo.go, flow/model/model.go, flow/model/qrecord_batch.go, flow/model/qvalue/qvalue.go
Adds support for hstore and geospatial types for postgres as destination for qrep and cdc.
Tests added
=> HStore and Geospatial for Postgres

flow/connectors/snowflake/qrep.go, flow/connectors/snowflake/snowflake.go
Was returning empty schema, which got as far as
COPY INTO "PUBLIC2"."SequelizeMeta"() FROM (...)
failing because an empty set of columns is a syntax error
=> snowflake getTableSchemaForTable: error when table does not exist

flow/workflows/setup_flow.go, flow/workflows/sync_flow.go
https://pkg.go.dev/go.temporal.io/sdk@v1.25.1/workflow#ExecuteLocalActivity
Local activities are a hybrid between activities & side effects,
useful for short lived activities without heartbeats
=> Use local activities in sync_flow / setup_flow

flow/workflows/cdc_flow.go
This became particularly important after sync flow began waiting for initial records
Also move checking for cdc parameters after signal processing,
updating cdc parameters to latest for next flow if parameters changed while pause
=> cdc_flow: listen for shutdown request while sync flow in progress

flow/cmd/handler.go, flow/e2e/s3/cdc_s3_test.go, flow/workflows/cdc_flow.go
Only used by 1 test, convert it to WaitFor
=> Remove TotalSyncFlows

flow/.golangci.yml, flow/connectors/postgres/client.go, flow/connectors/postgres/postgres_schema_delta_test.go, flow/connectors/postgres/qrep_partition_test.go, flow/connectors/utils/cdc_records/cdc_records_storage_test.go, flow/e2e/s3/qrep_flow_s3_test.go, flow/e2e/snowflake/peer_flow_sf_test.go, flow/model/conversion_avro.go, flow/model/qrecord_test.go, flow/model/qvalue/avro_converter.go
Also fix %v/%w flagged by errorlint,
but don't enable for now since it had more complaints
=> flow lints: add testifylint & wastedassign

nexus/Cargo.lock, nexus/postgres-connection/Cargo.toml, nexus/postgres-connection/src/lib.rs, stacks/peerdb-server.Dockerfile
Removes our openssl dependency
=> Replace postgres-openssl with tokio-postgres-rustls

flow/.golangci.yml, flow/connectors/clickhouse/clickhouse.go, flow/connectors/clickhouse/qrep.go, flow/connectors/postgres/client.go, flow/connectors/postgres/escape.go, flow/connectors/postgres/ssh_wrapped_pool.go, flow/connectors/snowflake/snowflake.go, flow/connectors/utils/partition/partition.go, flow/e2e/bigquery/bigquery_helper.go, flow/hstore/hstore.go, flow/shared/signals.go
nonamedreturns bans https://go.dev/tour/basics/7
=> flow lints: enable gocritic & nonamedreturns

flow/connectors/postgres/client.go, flow/connectors/postgres/postgres.go, flow/connectors/postgres/qrep.go, flow/connectors/snowflake/merge_stmt_generator.go, flow/connectors/snowflake/snowflake.go
Remove trailing comma so only `strings.Join(..., ",")` is needed
Also fix some missed QuoteIdentifier spots where `\"%s\"` was being used
=> Remove use of `strings.TrimSuffix(strings.Join(..., ""), ",")`

flow/connectors/postgres/client.go, flow/connectors/postgres/postgres.go
Also error out when we see replident 'n'/NOTHING for now
=> return all columns as pkeyCols in case of replident FULL and no pkey

flow/connectors/postgres/client.go, flow/connectors/postgres/normalize_stmt_generator.go
1) `wal_status` was introduced in PG13, introduced workaround for PG12
2) fixed regression with fallback statements, used <PG15
closes #990
=> fixed issues wrt PG compatibility

protos/route.proto, ui/app/api/mirrors/drop/route.ts, ui/app/api/mirrors/state_change/route.ts, ui/app/mirrors/edit/[mirrorId]/cdc.tsx, ui/app/mirrors/edit/[mirrorId]/cdcDetails.tsx, ui/app/mirrors/edit/[mirrorId]/page.tsx, ui/tsconfig.json
=> pause and resume mirror buttons, along with state reflection

flow/workflows/snapshot_flow.go
1. identifier quoting wasn't using QuoteIdentifier
2. mapping.Exclude wasn't being used to actually remove excluded columns
=> Cleanup snapshot flow, fixing two issues

flow/connectors/clickhouse/clickhouse.go, flow/connectors/core.go, flow/connectors/eventhub/eventhub.go, flow/connectors/s3/s3.go
Also remove some commented code & unnecessary lint directives
=> Clickhouse: metadataSchemaName should be _ch_ not _s3_

flow/connectors/postgres/cdc.go
When we encounter an error, we don't get any new messages until we re-establish START_REPLICATION. The added complexity isn't worth special-handling this error.
=> Fix hang when logging WAL segment removed

flow/e2e/bigquery/peer_flow_bq_test.go, flow/e2e/snowflake/peer_flow_sf_test.go
This test doesn't really make sense,
since the goroutine can finish before or after the workflow runs
=> e2e: remove Test_Toast_Nochanges

flow/connectors/clickhouse/clickhouse.go, flow/connectors/eventhub/eventhub.go, flow/connectors/external_metadata/store.go, flow/connectors/s3/s3.go, flow/e2e/s3/s3_helper.go, nexus/analyzer/src/lib.rs, protos/peers.proto, ui/app/peers/[peerName]/omitKeys.ts, ui/app/peers/create/[peerType]/helpers/ch.ts, ui/app/peers/create/[peerType]/helpers/s3.ts, ui/app/peers/create/[peerType]/schema.ts, ui/components/PeerForms/S3Form.tsx
Always use catalog. There's no demand for this complexity
=> Remove configurable postgres metadata database

.github/workflows/flow.yml, .github/workflows/golang-lint.yml
Forgot to update actions in #1219
=> go 1.22: also GH actions

flow/e2e/test_utils.go, flow/model/qvalue/avro_converter.go, flow/model/qvalue/qvalue.go
Fixes avro conversion for float32 to bigquery, adds tests for real data type which gets translated to float32
=> Fix float32 handling and add tests for real type

ui/app/peers/create/[peerType]/helpers/pg.ts, ui/components/PeerForms/PostgresForm.tsx
=> UI: SSH fields in Create PG: change field to file upload

ui/components/PeerComponent.tsx
Noticing latency upon clicking the peer button. This PR adds a spinner there when clicked
=> Add spinner for peer button

ui/components/PeerComponent.tsx
=> Fix for peer spinner button 

flow/activities/flowable.go, flow/workflows/sync_flow.go, protos/flow.proto
StartFlow can call GetLastOffset itself
=> Remove GetLastSyncedID

flow/activities/flowable.go, flow/e2e/test_utils.go
Also extend e2e workflow error check to print stacktrace for panics
=> StartFlow: pass errCtx to dstConn to cancel on srcConn error

flow/connectors/clickhouse/normalize.go
Introduced by expediated #1260
=> clickhouse: fix lint due to line too long

flow/connectors/clickhouse/clickhouse.go
We may not have permissions to list all buckets. Makes more sense to list paths in provided bucket
=> Clickhouse S3 Validation: use listobjects

flow/connectors/postgres/qvalue_convert.go, flow/connectors/utils/array.go
Ideally we'd preserve nulls, but this'll do for now
=> Generalize recent []int32 nil handling fix to rest of array types

ui/app/mirrors/[mirrorId]/edit/page.tsx, ui/app/mirrors/create/handlers.ts, ui/components/EditButton.tsx, ui/tsconfig.json
- Add spinner + disabled for edit mirror button
- Toast for potential failure in the status change endpoint
- Fix glitch with default destination table setting related to typescript enum
=> UI: Improvements for edit mirror page

flow/cmd/peer_data.go, flow/cmd/validate_mirror.go, flow/connectors/postgres/validate.go
- Replication connection can't perform queries so removed that
- Exclude dropped columns from being displayed in table picker
- Refactor create pub check to check privileges since transactions don't work on publications and don't want to risk creating and not dropping one. this has been functionally tested
=> Improve api for UI

flow/connectors/postgres/validate.go
If the user is a superuser, they have ownership rights over all tables so no need to check that. Currently validation errors for a superuser for tables it didn't create since the owner is listed as the user which created the table
=> Validate publication: skip ownership test if user is super

flow/connectors/postgres/postgres.go
Missed a %s when linting.
Also pretty sure wrapping publication and slot drop statements in a transaction has no effect
=> Fix PullFlowCleanup

ui/app/mirrors/[mirrorId]/edit/page.tsx
Fix state_change endpoint typo
=> UI: fix typo

flow/connectors/clickhouse/clickhouse.go, flow/connectors/clickhouse/normalize.go, flow/model/numeric/scale.go, flow/model/qvalue/avro_converter.go, flow/model/qvalue/dwh_type.go
This PR adds support for decimal data type for clickhouse with dynamic precision and scale mapping. This PR has been functionally tested.
=> Clickhouse: Dynamic Decimal Type

flow/cmd/handler.go, flow/workflows/drop_flow.go
The workflow cancels after start to close timeout. Somehow missed pushing this  in #1312
=> drop flow: increase start to close timeout

flow/workflows/cdc_flow.go, ui/app/mirrors/[mirrorId]/page.tsx, ui/components/ResyncDialog.tsx
also minor bug fix with addpub, multiple state updates wouldn't have worked
=> disable resync button for CH or PG destinations

.github/workflows/ci.yml, .github/workflows/cleanup.yml, .github/workflows/flow.yml
Updates from node16 to node20, silencing warning
=> Update create-json action to 1.2.3

flow/e2e/snowflake/snowflake_helper.go
https://docs.snowflake.com/en/sql-reference/sql/create-database
=> e2e/snowflake: create database as transient & without retention

flow/e2e/bigquery/bigquery_helper.go
Set expiry durations of 1 hour for tables/partitions in bq e2e tests
=> e2e/bigquery: specify 1 hour expiration times

flow/activities/snapshot_activity.go, flow/cmd/snapshot_worker.go, flow/connectors/core.go, flow/connectors/postgres/postgres.go, flow/e2e/test_utils.go, flow/workflows/snapshot_flow.go
=> Use pg_export_snapshot when InitialSnapshotOnly

flow/activities/snapshot_activity.go, flow/workflows/cdc_flow.go
Mix up had #1347 merge before logging feedback implemented
=> log how long snapshot export maintained, & when snapshot flow fails

flow/cmd/api.go, flow/workflows/cdc_flow.go, flow/workflows/drop_flow.go, flow/workflows/normalize_flow.go, flow/workflows/qrep_flow.go, flow/workflows/setup_flow.go, flow/workflows/snapshot_flow.go, flow/workflows/xmin_flow.go
=> Use log.With to have flowName always included in workflow logs

flow/workflows/cdc_flow.go, flow/workflows/qrep_flow.go, flow/workflows/xmin_flow.go
https://pkg.go.dev/go.temporal.io/sdk/workflow#Now
=> use workflow.Now in workflows, not time.Now

flow/activities/flowable.go, flow/workflows/cdc_flow.go
Trying to avoid issues being ran into with one sync & resets:
```
source connector missing from CdcCache
```
=> cdc_flow: move WaitForSourceConnector into SyncFlow

flow/connectors/postgres/postgres.go, flow/workflows/cdc_flow.go
Otherwise activity retries & continually hits same error
=> Use NewNonRetryableApplicationError when replState mismatch occurs

.github/workflows/ci.yml, .github/workflows/customer-docker.yml, .github/workflows/dev-docker.yml, .github/workflows/flow.yml, .github/workflows/golang-lint.yml, .github/workflows/rust-lint.yml, .github/workflows/stable-docker.yml, .github/workflows/ui-build.yml, .github/workflows/ui-lint.yml
=> Update buf-setup-action to 1.29.0-1

ui/app/api/mirrors/cdc/route.ts, ui/app/api/mirrors/cdc/validate/route.ts, ui/app/api/mirrors/drop/route.ts, ui/app/api/mirrors/qrep/route.ts, ui/app/api/mirrors/state/route.ts, ui/app/api/mirrors/state_change/route.ts, ui/app/api/peers/route.ts, ui/middleware.ts
We now log request and response metadata in our middleware.
Request: Method, URL, IP, OS, Browser, Device
Response: Status
The two are linked by a UUID
=> API: Add Access logging

flow/workflows/cdc_flow.go, flow/workflows/sync_flow.go
This is a more desired behavior when a user clicks pause
=> Pause will drop the current Sync and Normalize and hard-pause

flow/activities/flowable.go
avoids pull continuing after sync returns 0 records
also stop syncing records if pull records hits error
=> qrep: stop pulling records if sync completes

.github/workflows/golang-lint.yml
=> update golangci github action to v4

flow/activities/flowable.go
Avoids context.Canceled error being wrapped
mixup in #1407
=> invert taskCtx with errCtx

flow/connectors/postgres/qvalue_convert.go, flow/e2e/bigquery/peer_flow_bq_test.go, flow/e2e/test_utils.go, flow/model/qrecord_batch.go, flow/model/qvalue/avro_converter.go, flow/model/qvalue/qvalue.go
Supports INET and CIDR for initial load for BigQuery and Snowflake
=> Datatypes: fix inet and cidr

ui/app/alert-config/new.tsx, ui/app/alert-config/page.tsx, ui/app/mirrors/[mirrorId]/cdc.tsx, ui/app/mirrors/[mirrorId]/cdcGraph.tsx, ui/app/mirrors/[mirrorId]/syncStatusTable.tsx, ui/app/mirrors/[mirrorId]/tablePairs.tsx, ui/app/mirrors/create/mirrorcards.tsx, ui/app/mirrors/create/page.tsx, ui/app/mirrors/create/qrep/qrep.tsx, ui/app/mirrors/create/qrep/upsertcols.tsx, ui/app/mirrors/status/qrep/[mirrorId]/qrepGraph.tsx, ui/app/mirrors/status/qrep/[mirrorId]/qrepStatusTable.tsx, ui/app/mirrors/tables.tsx, ui/app/page.tsx, ui/app/peers/[peerName]/lagGraph.tsx, ui/app/peers/[peerName]/page.tsx, ui/app/peers/[peerName]/style.ts, ui/app/peers/create/[peerType]/page.tsx, ui/app/peers/create/page.tsx, ui/app/peers/page.tsx, ui/app/peers/peersTable.tsx, ui/app/styles/select.tsx, ui/components/PeerInfo.tsx, ui/components/ReloadButton.tsx, ui/components/SelectSource.tsx, ui/components/SidebarComponent.tsx, ui/lib/Layout/Layout.styles.ts, ui/lib/Layout/Layout.tsx
- Collapsible sidebar
- Remove extra borders from tables
- Change dropdown colors
https://github.com/PeerDB-io/peerdb/assets/65964360/e5c1c47f-c4b4-431f-ab60-a9881330dd5a
=> UI: Collapsible sidebar and fixes

flow/activities/flowable.go, flow/activities/snapshot_activity.go, flow/cmd/mirror_status.go, flow/workflows/cdc_flow.go, flow/workflows/qrep_flow.go, flow/workflows/setup_flow.go, flow/workflows/snapshot_flow.go, flow/workflows/xmin_flow.go
Explicitly passing flow name in no longer necessary after #1357
=> Fix cases of !BADKEY in datadog

flow/connectors/snowflake/merge_stmt_generator.go, flow/connectors/snowflake/snowflake.go
Now Snowflake's NormalizeRecords merges one batch at a time (along with updating the normalized batch id one at a time)
=> Snowflake: merge one batch at a time

flow/connectors/snowflake/snowflake.go, flow/peerdbenv/config.go
Set to 1 to disable parallelism
Set to -1 to enable unlimited parallelism
=> Add environment variable to control parallelism of snowflake merge

ui/app/peers/page.tsx, ui/app/peers/peersTable.tsx, ui/next.config.js
=> Revert "UI: Redirect to peers page by default, add buttons there"

nexus/Cargo.lock, nexus/catalog/Cargo.toml, nexus/catalog/src/lib.rs, nexus/flow-rs/Cargo.toml, nexus/flow-rs/src/grpc.rs, nexus/pt/src/lib.rs, nexus/server/Cargo.toml
server wasn't using prost, catalog uses reexported prost
=> pt: reexport prost/tonic

flow/connectors/eventhub/eventhub.go, flow/go.mod, flow/go.sum, flow/model/record_items.go, flow/pua/peerdb.go, flow/pua/peerdb_test.go
Implement json marshaling for `*RecordItems` so `json.encode(row)` works
=> lua: add msgpack preload, remove peerdb.RowToJSON

flow/cmd/handler.go, flow/connectors/bigquery/bigquery.go, flow/connectors/bigquery/qrep.go, flow/connectors/bigquery/qrep_avro_sync.go, flow/connectors/clickhouse/cdc.go, flow/connectors/clickhouse/clickhouse.go, flow/connectors/clickhouse/normalize.go, flow/connectors/eventhub/eventhub.go, flow/connectors/external_metadata/store.go, flow/connectors/kafka/kafka.go, flow/connectors/postgres/qrep_sql_sync.go, flow/connectors/pubsub/pubsub.go, flow/connectors/s3/s3.go, flow/connectors/snowflake/qrep.go, flow/connectors/snowflake/qrep_avro_sync.go, flow/connectors/snowflake/snowflake.go, flow/e2e/bigquery/qrep_flow_bq_test.go, flow/e2e/postgres/qrep_flow_pg_test.go, flow/e2e/s3/qrep_flow_s3_test.go, flow/e2e/snowflake/qrep_flow_sf_test.go, flow/e2e/sqlserver/qrep_flow_sqlserver_test.go, flow/e2e/test_utils.go
Embed compositions for implicit connector implementations
=> PostgresMetadata: implement connector interfaces

flow/cmd/validate_peer.go, flow/connectors/postgres/client.go, flow/connectors/postgres/postgres.go
Return PGVersion, leaving caller to do comparisons
=> pg: replace MajorVersionCheck with MajorVersion

ui/app/dto/MirrorsDTO.ts, ui/app/mirrors/create/mirrorcards.tsx, ui/app/mirrors/create/page.tsx, ui/app/mirrors/create/styles.tsx, ui/app/mirrors/layout.tsx, ui/app/mirrors/page.tsx, ui/app/mirrors/tables.tsx
Improves the empty mirrors page by showing buttons to take the user to create the relevant mirror they want
Also some add text and link to quickstart
=> UI: Add create mirror buttons

flow/connectors/postgres/cdc.go, flow/connectors/utils/cdc_records/cdc_records_storage_test.go, flow/model/model.go, flow/model/record.go, flow/model/record_items.go, flow/pua/peerdb.go
We never make use of slice ordering
=> RecordItems: only track values in map[string]qvalue.QValue

flow/activities/flowable.go, flow/connectors/core.go, flow/connectors/postgres/qrep.go, flow/connectors/postgres/qrep_query_executor.go, flow/connectors/snowflake/avro_file_writer_test.go, flow/connectors/sql/query_executor.go, flow/connectors/sqlserver/qrep.go, flow/model/qrecord_batch.go
sqlserver now writes batch to stream,
removing need for if/else in activity
=> Update PullQRepRecords to PullQRepRecordStream

flow/connectors/bigquery/bigquery.go, flow/connectors/bigquery/merge_stmt_generator.go, flow/connectors/postgres/normalize_stmt_generator.go, flow/connectors/postgres/normalize_stmt_generator_test.go, flow/connectors/postgres/postgres.go, flow/connectors/snowflake/merge_stmt_generator.go, flow/connectors/snowflake/merge_stmt_generator_test.go, flow/connectors/snowflake/snowflake.go
mergeStmtGenerator struct should be immutable info,
allowing sharing across threads & reuse per loop iteration
=> PG/SF/BQ: hoist mergeStmtGenerator out of loop

flow/cmd/validate_peer.go, flow/connectors/postgres/client.go, flow/connectors/postgres/postgres.go, flow/shared/postgres.go
This is a preceding PR to #1574
=> Postgres: move version fetching to shared folder

flow/connectors/postgres/qvalue_convert.go, flow/e2e/test_utils.go, flow/model/qvalue/avro_converter.go
=> Remove unused [16]byte cases, fix macaddr

flow/connectors/postgres/qvalue_convert.go, flow/connectors/utils/gcp.go, flow/model/model.go, flow/model/record.go
=> Misc cleanup

flow/connectors/postgres/qvalue_convert.go, flow/model/qrecord_batch.go, flow/model/qvalue/equals.go
Accidentally mapped to QValueCIDR instead of QValueMacaddr in #1585
=> Fix macaddr fix

ui/app/scripts/new/page.tsx, ui/app/scripts/page.tsx
Sort scripts. Adjust UI since editor doesn't handle resizing well. Tighten header
=> Touch up Scripts UI

flow/connectors/postgres/postgres.go
seems to be flaky, hangs sometimes
=> remove SendBatch in PG normalize

ui/components/PeerForms/S3Form.tsx
Link for GCS create peer meant to point to google cloud doc
=> UI: Fix GCS Link

flow/pua/peerdb.go
This allows disambiguating a null value as unchanged for toast columns
Ignore UnchangedToastColumns on DeleteRecord since queues don't care about soft delete
=> Lua: add unchanged_columns field to Record

flow/connectors/postgres/cdc.go, flow/connectors/postgres/postgres.go
Pass processor itself rather than passing callbacks that pass processor
=> Remove some indirection in pgvalue/qvalue cdc code

flow/connectors/bigquery/bigquery.go, flow/connectors/clickhouse/cdc.go, flow/connectors/postgres/client.go, flow/connectors/postgres/postgres.go, flow/connectors/snowflake/snowflake.go, flow/shared/string.go, flow/workflows/snapshot_flow.go, ui/app/mirrors/create/schema.ts, ui/app/peers/create/[peerType]/schema.ts
Avoids repetition while also avoiding unnecessary recompilations
=> Consolidate regexen, don't allow digits at start of names

ui/app/mirrors/create/cdc/tablemapping.tsx
Wrong link meant for grants for postgres tables
=> UI: Fix broken link for postgres permissions

ui/app/mirrors/create/handlers.ts, ui/app/mirrors/create/helpers/common.ts, ui/app/mirrors/create/helpers/qrep.ts, ui/app/mirrors/create/page.tsx, ui/app/mirrors/create/qrep/qrep.tsx, ui/app/utils/qreptemplate.ts
- Check if query box is unfilled
- Add explanation text for the query box
- Set Create Destination Table default to true
- Remove Staging Path field
- Remove some dead code
=> UI: Better Create QRep

flow/connectors/snowflake/avro_transform_test.go, flow/connectors/snowflake/qrep_avro_consolidate.go, flow/e2e/bigquery/qrep_flow_bq_test.go, flow/e2e/elasticsearch/qrep_flow_es_test.go, flow/e2e/postgres/qrep_flow_pg_test.go, flow/e2e/s3/qrep_flow_s3_test.go, flow/e2e/snowflake/qrep_flow_sf_test.go, flow/e2e/snowflake/snowflake_helper.go, flow/e2e/test_utils.go, flow/workflows/qrep_flow.go
This PR makes soft delete false instead of null for snowflake initial load.
Test added.
=> Soft delete false for Snowflake initial load

flow/connectors/kafka/kafka.go
- fix for usage with confluent cloud
=> fix: enable support for TLS 1.2

flow/activities/flowable_core.go, flow/connectors/connelasticsearch/elasticsearch.go, flow/connectors/connelasticsearch/qrep.go, flow/connectors/core.go, flow/connectors/postgres/cdc.go, flow/connectors/postgres/postgres.go, flow/e2e/elasticsearch/elasticsearch.go, flow/e2e/elasticsearch/peer_flow_es_test.go, flow/e2e/elasticsearch/qrep_flow_es_test.go, flow/model/model.go, flow/workflows/snapshot_flow.go
Current limitations:
1) soft-delete does not work, needs to be handled specifically from the ES side
2) relies on implicit index creation, no custom mapping or other index configuration is possible
3) TOAST columns aren't handled properly
=> Elasticsearch connector for CDC

flow/cmd/validate_peer.go
Log non flow error only if not nil for validate peer
=> Telemetry for peer: only televise non nil validate peer err

nexus/Cargo.lock, nexus/Cargo.toml, nexus/peer-ast/Cargo.toml, nexus/peer-ast/src/lib.rs, nexus/peer-bigquery/Cargo.toml, nexus/peer-bigquery/src/ast.rs, nexus/peer-mysql/Cargo.toml, nexus/peer-mysql/src/ast.rs
=> More fixes for MySQL peer

ui/app/peers/create/[peerType]/schema.ts
- Allows for empty partition field
- Adds some error messaging for the zod schema
=> UI: Fix kafka zod

flow/connectors/postgres/postgres.go
Also need to use `activity.IsActivity` outside activity specific code
=> Fix CI regression, #1658 merged too soon

flow/activities/flowable.go, flow/connectors/core.go
turns out reading release notes once in a while helps
=> swapping out custom error for errors.ErrUnsupported

flow/cmd/peer_data.go
fix this issue: https://github.com/PeerDB-io/peerdb/issues/1680
=> fix GetColumns script

ui/app/peers/create/[peerType]/helpers/ch.ts, ui/components/PeerForms/ClickhouseConfig.tsx
- Adds placeholder for s3 path field
- Link to doc for setting up s3 bucket
=> CH UI: Help for user bucket setup

e2e_cleanup/go.mod, flow/go.mod, stacks/flow.Dockerfile, stacks/peerdb-server.Dockerfile, stacks/peerdb-ui.Dockerfile
reduces the number of high and medium vulns to zero.
=> Move to alpine to reduce vulns

stacks/flow.Dockerfile, stacks/peerdb-server.Dockerfile
=> flow/nexus docker: nonroot

flow/connectors/clickhouse/clickhouse.go, flow/connectors/clickhouse/qrep_avro_sync.go
Add more memory settings for queries set to unlimited
=> Stilgar: clickhouse: add more settings to 0

flow/connectors/utils/avro/avro_writer.go
=> Revert "increase the partsize for s3 upload"

docker-compose.yml
=> fix duplicate restart in docker-compose.yml

dev-peerdb.sh, flow/connectors/utils/peers.go, ui/app/peers/create/[peerType]/page.tsx, ui/components/PeerForms/SnowflakeForm.tsx, ui/components/PeerInfo.tsx, ui/components/SelectSource.tsx
fixes: https://github.com/PeerDB-io/peerdb/issues/1743 in combination with https://github.com/PeerDB-io/peerdb/pull/1763
=> Add edit peer UI that is accessible from the peer page

flow/activities/flowable.go
Add heartbeat routine in ReplicateQRepPartitions activity
=> Add heartbeat routine in ReplicateQRepPartitions

flow/peerdbenv/dynamicconf.go
CodeQL didn't like uint32 conversion to int64
=> PEERDB_ALERTING_GAP_MINUTES is int64

ui/app/api/settings/route.ts, ui/app/mirrors/status/qrep/[mirrorId]/page.tsx, ui/app/settings/layout.tsx, ui/app/settings/page.tsx, ui/components/SidebarComponent.tsx, ui/prisma/schema.prisma
Introduced a new settings page for managing dynamic settings with backend API routes and frontend components.
- Error handling in API routes.
- State management for editing in UI.
- Updated database indexing for efficient querying.
https://www.loom.com/share/ce7541a92538431f8c55b3ffcf712eea?sid=04cf9b72-6631-49be-9073-6ef8161432d4
=> fead: Add Settings Page for Dynamic Settings

nexus/.cargo/config.toml, nexus/Cargo.lock, nexus/postgres-connection/src/lib.rs, nexus/server/Cargo.toml, nexus/server/src/main.rs
Was making it awkward to build individual crates,
& has less value as most of product is golang now
=> Remove tokio unstable flag

flow/e2e/bigquery/peer_flow_bq_test.go, flow/e2e/congen.go, flow/e2e/elasticsearch/peer_flow_es_test.go, flow/e2e/eventhub/peer_flow_eh_test.go, flow/e2e/generic/generic_test.go, flow/e2e/kafka/kafka_test.go, flow/e2e/postgres/peer_flow_pg_test.go, flow/e2e/pubsub/pubsub_test.go, flow/e2e/s3/cdc_s3_test.go, flow/e2e/snowflake/peer_flow_sf_test.go, flow/e2e/test_utils.go
CDCStagingPath is not needed for tests anymore
SetupQuery take config instead of configgen
=> bit of e2e cleanup

flow/connectors/kafka/kafka.go, flow/connectors/postgres/cdc.go, flow/connectors/postgres/postgres.go, flow/connectors/utils/lua.go, flow/model/record.go, flow/pua/peerdb.go, flow/shared/postgres.go
People would like to use pg_logical_emit_message instead of heartbeat tables
=> cdc: MessageTypeMessage

flow/connectors/connelasticsearch/elasticsearch.go, flow/connectors/postgres/client.go, flow/connectors/postgres/postgres.go, flow/connectors/utils/cdc_store.go, flow/connectors/utils/stream.go, flow/e2e/kafka/kafka_test.go, flow/e2e/postgres/peer_flow_pg_test.go
fixes elasticsearch segfaulting on MessageRecord
fixes postgres erroring on MessageRecord
=> e2e: test LogicalDecodingMessage handled by cdc

flow/connectors/clickhouse/qrep_avro_sync.go
Minor improvements in clickhouse avro handling for better monitoring
=> Clickhouse avro: better name and log

docker-compose-dev.yml, docker-compose.yml, flow/activities/flowable.go, flow/e2e/kafka/kafka_test.go, nexus/Cargo.lock, nexus/catalog/Cargo.toml, nexus/server/Cargo.toml, nexus/server/src/main.rs
Recent cleanup removed a dependency enabling this feature, causing our logs to spam TRACE messages
Also make log file optional
=> tracing: env-filter feature

flow/connectors/postgres/cdc.go, flow/model/record.go, flow/pua/peerdb.go
=> cdc: copy content

flow/connectors/clickhouse/normalize.go
split off from #1837 as need to address some issues with normalize warnings
=> [clickhouse] delay before starting normalize

.github/actions/genprotos/action.yml, flow-jvm/README.md, flow-jvm/src/main/java/io/peerdb/flow/jvm/DefaultExceptionHandlerProvider.java, flow-jvm/src/main/java/io/peerdb/flow/jvm/iceberg/resource/IcebergResource.java, flow-jvm/src/main/java/io/peerdb/flow/jvm/iceberg/service/IcebergService.java, flow-jvm/src/main/resources/application.yaml, flow/connectors/iceberg/qrep.go, protos/flow-jvm.proto
This uses streams instead of sending all the records in 1 go.
=> feat(iceberg): add streaming support to improve performance and memory footprint

ui/app/api/peers/info/[peerName]/route.ts, ui/app/api/peers/slots/[name]/route.ts, ui/app/mirrors/[mirrorId]/aggregatedCountsByInterval.ts, ui/app/mirrors/[mirrorId]/cdcGraph.tsx, ui/app/mirrors/status/qrep/[mirrorId]/qrepGraph.tsx, ui/app/peers/[peerName]/lagGraph.tsx, ui/app/utils/graph.ts
1. redacting more things, and including peer types not covered before. This isn't the ideal approach, have another idea I'll try when I have bandwidth
2. graph generation code refactor and switching to enums
=> UI cleanup

flow/connectors/core.go, flow/connectors/postgres/postgres.go, ui/app/mirrors/[mirrorId]/page.tsx
didn't feel like testing resync using BQ
=> resync for Postgres CDC

flow/connectors/bigquery/merge_stmt_generator.go, flow/connectors/bigquery/qvalue_convert.go, flow/connectors/postgres/normalize_stmt_generator.go, flow/connectors/postgres/qvalue_convert.go, flow/connectors/postgres/schema_delta_test_constants.go, flow/connectors/snowflake/avro_file_writer_test.go, flow/connectors/snowflake/merge_stmt_generator.go, flow/connectors/sql/query_executor.go, flow/connectors/sqlserver/qvalue_convert.go, flow/connectors/utils/cdc_store.go, flow/e2e/bigquery/bigquery_helper.go, flow/e2e/postgres/peer_flow_pg_test.go, flow/model/qrecord_copy_from_source.go, flow/model/qvalue/avro_converter.go, flow/model/qvalue/equals.go, flow/model/qvalue/kind.go, flow/model/qvalue/qvalue.go, flow/model/record_items.go, flow/pua/peerdb.go
Code assumed bit was a single bit in places,
sent bytes as binary which was then base64 decoded,
or converted to ASCII bytes of binary digits
=> Send bytes as base64, remove bits

flow/cmd/handler.go, flow/shared/postgres.go, flow/workflows/cdc_flow.go, flow/workflows/local_activities.go
=> CDC resync: inherit changes to mirror

ui/app/mirrors/[mirrorId]/page.tsx
=> fix dbType comparison to enable resync button

flow/activities/flowable_core.go, flow/cmd/handler.go, flow/cmd/peer_data.go, flow/connectors/core.go, flow/connectors/utils/peers.go, flow/e2e/congen.go, flow/peerdbenv/config.go, flow/peerdbenv/env.go, flow/shared/enc.go, nexus/Cargo.lock, nexus/catalog/Cargo.toml, nexus/catalog/migrations/V33__aes.sql, nexus/catalog/src/lib.rs, nexus/flow-rs/src/grpc.rs, nexus/server/src/main.rs, nexus/server/tests/server_test.rs, protos/route.proto, ui/app/api/peers/info/[peerName]/route.ts, ui/app/api/peers/route.ts, ui/components/PeerInfo.tsx
This commit enhances security by encrypting peer options in the 'peers' table using AES encryption. AES was chosen for its reliability and widespread adoption in securing sensitive data. Changes include:
- Added `enc_key_id` column to the `peers` table.
- Modified `LoadPeer` and `CreatePeerNoValidate` functions to handle encryption/decryption.
- Updated environment configuration to support encryption key management.
=> Encrypt credentials stored in peers table

flow/cmd/handler.go, flow/cmd/mirror_status.go
remove ILIKE in a couple of places in our API as they are leading to issues with substrings
=> api: No ILIKE usage

flow/cmd/peer_data.go
Show partitioned tables (parents) in the watermark table drop down in Create QRep UI
=> QRep: Show partitioned tables in dropdown

nexus/Cargo.lock, nexus/Cargo.toml, nexus/server/src/main.rs
`cargo outdated` seems to have issues checking workspace dependencies
=> pgwire 0.23

flow/cmd/alerts.go, flow/cmd/handler.go, protos/route.proto, ui/app/alert-config/new.tsx, ui/app/alert-config/page.tsx, ui/app/api/alert-config/route.ts, ui/app/api/peers/info/[peerName]/route.ts, ui/app/dto/AlertDTO.ts, ui/components/AlertDropdown.tsx, ui/components/DropDialog.tsx
in prep for encrypting alerting configs
=> deprisma alerting config

flow/workflows/sync_flow.go
One minute was tripping up, rely on other network timeouts
Also disable retries
=> raise MaintainPull heartbeat timeout to one hour

flow/cmd/settings.go, protos/route.proto, ui/app/scripts/page.tsx, ui/app/settings/page.tsx
Scripts and settings pages were not rendering properly - a regression
This PR restores these
Functionally tested - add script, edit script, edit setting, edit peer
=> UI: fix scripts and settings pages

flow/connectors/postgres/postgres.go, flow/e2e/postgres/peer_flow_pg_test.go
Account for mixed case table and column in Postgres replaytableschemadeltas function
test added
=> Postgres schema changes: account for mixed case

flow/cmd/settings.go, flow/peerdbenv/dynamicconf.go, flow/shared/proto.go, flow/workflows/cdc_flow.go, nexus/catalog/migrations/V36__reduce_dynamic_settings.sql, protos/route.proto
avoids needing a migration when adding config,
originally put in database to available to ui through prisma,
but prisma is gone
=> move dynamic settings metadata into static array

flow/connectors/postgres/qrep.go
This can happen when table has been truncated
=> CheckForUpdatedMaxValue: return false while nil

flow/connectors/postgres/qrep.go, flow/connectors/postgres/sink_pg.go
doesn't work otherwise since it doesn't see the temp staging table
=> use tx to CopyFrom during QRep pgvalue upsert

flow/cmd/handler.go, ui/app/mirrors/[mirrorId]/qrepStatusButtons.tsx
QRep UI - resume button was sending STATUS_PAUSED as requested state change instead of STATUS_RUNNING
=> UI QRep: Fix resume button

nexus/server/src/main.rs
SASLScramAuthStartupHandler has state, so cannot be shared between connections
=> fix scram auth

flow/activities/flowable_core.go
Recently observed race: https://github.com/jackc/pgx/pull/2067
The issue is on our end, caused by this sequence:
1. create connector, setup defer
2. start errgroup using connector & another task
3. other task fails, before connector task stops errGroup.Wait returns & defer runs
defer may not run while connector task is meant to have exclusive access
Solve this by moving connector create/defer into task
Left dstConn qrep since it's being used to check already synced, can be followup
=> Fix connectors.Close race

flow/connectors/clickhouse/qrep.go, nexus/server/src/main.rs
can update cutomers not exposing nexus to run this as an `InitContainer` or something
=> nexus: mode to only run migrations

flow/connectors/clickhouse/cdc.go, flow/connectors/clickhouse/clickhouse.go, flow/connectors/clickhouse/normalize.go, flow/connectors/clickhouse/qrep.go, flow/connectors/clickhouse/qrep_avro_sync.go, flow/e2e/clickhouse/clickhouse.go
Remove transactional schema updates because clickhouse isn't transactional
=> Bypass clickhouse database/sql abstraction layer

flow/connectors/clickhouse/clickhouse.go
Adds validation for adding column, renaming table, and update table
=> Clickhouse peer: more validation

ui/app/mirrors/[mirrorId]/aggregatedCountsByInterval.ts, ui/app/mirrors/[mirrorId]/cdcGraph.tsx, ui/app/mirrors/[mirrorId]/qrepGraph.tsx
String concatenation was happening for the rows synced numbers in the rows synced graph
Explicityly convert to Number so that it actually adds
=> UI Graphs: convert to Number

ui/app/mirrors/create/cdc/guide.tsx
Links to setup documentation for Clickhouse peer UI
=> Clickhouse UI: link to doc

.github/actions/genprotos/action.yml, .github/workflows/ci.yml, .github/workflows/cleanup.yml, .github/workflows/flow.yml, .github/workflows/golang-lint.yml
https://www.ubicloud.com/docs/github-actions-integration/ubicloud-cache
=> use ubicloud cache more

flow/connectors/clickhouse/qrep_avro_sync.go
As an attempt to get past memory overcommit tracker killing our queries, I'm trying to perform this hotfix of:
```sql
SELECT * FROM s3() WHERE mod(toUInt128(toUUID(_peerdb_uid)),17) = x;
```
=> Harp: try modulo uid for clickhouse insertion

flow/flow-api-client/go.mod
=> Fix typo in package name

nexus/Cargo.lock
messed up commit when holding back mysql_async
=> fix Cargo.lock

.gitattributes, flow/connectors/clickhouse/qrep_avro_sync.go, flow/flow-api-client/README.md
* Add `.gitattributes` file
* Remove dead code from `flow/connectors/clickhouse/qrep_avro_sync.go`
* Add `README.md` to flow api client package
=> Add `.gitattributes` file

flow/connectors/clickhouse/normalize.go
identified this issue while debugging something completely different
=> Update end normalize batch id for clickhouse

nexus/peer-mysql/src/ast.rs
=> missed small fix for starrocks

flow/connectors/clickhouse/clickhouse.go, flow/connectors/clickhouse/normalize.go
Fixes #2037 
Accounts for CH Cloud
=> Clickhouse: fix merge tree family validation

flow/cmd/validate_mirror.go
Account for mixed case table names in publication creation validation
=> Quoting in publication creation validation

ui/components/ResyncDialog.tsx
Adds a link to resync peerdb documentation: https://github.com/PeerDB-io/docs/pull/174
Also keeps the close resync button enabled
=> Add link to doc for resync

ui/app/mirrors/create/cdc/schemabox.tsx
=> TablePicker: Add placeholder for engine select

flow/connectors/clickhouse/normalize.go
1. Fix NPE in tableMappigns.len
2. Default to ReplacingMergeTree to support upsert key columns
=> Fix issues with CH qrep

ui/app/api/supabase/route.ts, ui/app/supabase/page.tsx
=> supabase: render errors

ui/app/mirrors/create/handlers.ts, ui/app/mirrors/create/helpers/cdc.ts
invalid json was causing ui to get stuck spinning
=> validate envString json

flow/connectors/bigquery/qrep_avro_sync.go, flow/connectors/clickhouse/cdc.go, flow/connectors/clickhouse/normalize.go, flow/connectors/clickhouse/qrep.go, flow/connectors/clickhouse/qrep_avro_sync.go, flow/connectors/utils/avro/avro_writer.go, flow/peerdbenv/dynamicconf.go
This reverts commit aa0631d23190467142c1415f20674c062419ac11.
=> Revert "feat: Add method to write Avro files to S3 in parts (#1770)"

flow/connectors/clickhouse/normalize.go, flow/e2e/clickhouse/clickhouse.go, flow/e2e/clickhouse/peer_flow_ch_test.go
We need to specify Nullable when specifying the type argument of JSONExtract, else it will convert to default
=> Clickhouse: nullable fix for normalize in CDC

flow/activities/flowable.go
looks like it was removed from flowable at some point
=> [postgres] update end batch time for Postgres destinations

ui/components/DropDialog.tsx
Show drop stats only in drop mirror dialog and not other drop dialogs
Mistake in #2029  - option appearing in drop scripts as well for example
=> UI: Drop stats checkbox only drop mirror

flow/connectors/clickhouse/cdc.go, flow/connectors/clickhouse/clickhouse.go, flow/connectors/clickhouse/normalize.go, flow/connectors/clickhouse/qrep.go
has impacted multiple customers
=> ch: retry queries for some kinds of errors

flow/connectors/utils/peers.go
customer currently hitting this error, want to be sure what kind of config is actually being received
=> improve CreatePeerNoValidate error message

flow/connectors/clickhouse/normalize.go, flow/connectors/postgres/client.go, flow/connectors/postgres/postgres.go, flow/connectors/postgres/postgres_schema_delta_test.go, flow/connectors/postgres/schema_delta_test_constants.go, flow/e2e/clickhouse/peer_flow_ch_test.go, protos/flow.proto, ui/app/mirrors/create/cdc/columnbox.tsx
this way is consistent with other clickpipe engines
=> also allow for per column nullable enabled on clickhouse

flow/cmd/peer_data.go, flow/connectors/clickhouse/clickhouse.go, flow/connectors/core.go, flow/connectors/postgres/client.go, flow/connectors/postgres/postgres.go, protos/route.proto, ui/app/peers/[peerName]/lagGraph.tsx, ui/components/PeerInfo.tsx
to make debugging simpler, no need to ask customer version everytime
=> [ui] list version in peerinfo for Postgres and ClickHouse peers

flow/activities/flowable.go
Following https://opentelemetry.io/docs/specs/semconv/general/metrics/
=> refactor(otel-metrics): use UCUM standards

flow/connectors/postgres/postgres.go
Missing a space between words in the rename query
=> PG Resync Query: Fix syntax

ui/app/mirrors/create/cdc/guide.tsx
=> docs(ui): fix peer setup links

flow/activities/flowable.go, flow/cmd/handler.go, flow/cmd/settings.go, flow/connectors/postgres/client.go, flow/workflows/drop_flow.go, ui/app/mirrors/tables.tsx, ui/app/peers/peersTable.tsx, ui/app/scripts/list.tsx, ui/components/AlertDropdown.tsx, ui/components/DropDialog.tsx
=> cleanup, remove `]:` from logs

flow/cmd/validate_mirror.go, flow/cmd/validate_peer.go
=> validate: 1 minute timeout

nexus/server/src/main.rs
=> feat(nexus): add flag for disabling migrations

flow/cmd/peer_data.go, protos/route.proto, ui/app/peers/[peerName]/lagGraph.tsx
Unfortunately we aren't tracking latest wal so no line to show how far behind confirmed is from latest
=> slot lag graph: also have lsn graph

flow/activities/flowable.go, flow/cmd/handler.go, flow/workflows/drop_flow.go, protos/flow.proto
move flow entries removal to an activity, and make it before dropping source and destination as that can fail and the workflow will be cancelled
=> drop flow refactor

flow/cmd/peer_data.go
Foreign keys that were unique columns and not pkeys had their column exclusion disabled in the UI as the current query to fetch column data was counting them as primary keys. This PR fixes this
```sql
-- Create a projects table
CREATE TABLE projects (
id SERIAL PRIMARY KEY, 
application_id INT
);
-- Create the applications table
CREATE TABLE applications (
id INTEGER UNIQUE
);
-- Create foreign key relationship
ALTER TABLE projects
ADD CONSTRAINT fk_application
FOREIGN KEY (application_id)
REFERENCES applications (id);
```
Before checking out to this PR, id in the applications table will be disabled in UI, post checkout - will be non-disabled
=> API/GetColumns: fix foreign keys being considered pkeys

flow/connectors/clickhouse/qrep_avro_sync.go
otherwise partitions will repeat themselves because we think it hasn't synced
=> [clickhouse] actually call FinishQRepPartition to store partition state

flow/connectors/clickhouse/normalize.go, flow/connectors/external_metadata/store.go
Reverts PeerDB-io/peerdb#2219
seems to degrade perf
=> Revert "ClickHouse: Normalize one batch at a time"

flow/cmd/handler.go, flow/connectors/postgres/client.go, flow/connectors/postgres/postgres.go, flow/connectors/postgres/validate.go, flow/e2e/clickhouse/peer_flow_ch_test.go, flow/e2e/congen.go, flow/e2e/test_utils.go
=> e2e: resync weird names

flow/connectors/postgres/postgres.go
This PR fixes the intended drop if exists logic for _resync tables when a Postgres to Postgres mirror is resynced, along with a casing issue
=> Fix resync logic for postgres to postgres

flow/connectors/postgres/cdc.go, flow/connectors/postgres/client.go, flow/connectors/postgres/postgres.go, flow/connectors/postgres/qrep.go, flow/connectors/postgres/qrep_bench_test.go, flow/connectors/postgres/qrep_query_executor.go, flow/connectors/postgres/qrep_query_executor_test.go, flow/e2e/postgres/postgres.go, flow/e2e/test_utils.go, flow/shared/postgres.go
=> [postgres] reduce unnecessary queries

flow/peerdbenv/dynamicconf.go
=> update s3 part size config description

flow/connectors/bigquery/merge_stmt_generator.go, flow/connectors/bigquery/qvalue_convert.go, flow/connectors/postgres/postgres.go, flow/connectors/postgres/qvalue_convert.go, flow/connectors/snowflake/merge_stmt_generator.go, flow/model/qrecord_copy_from_source.go, flow/model/qvalue/avro_converter.go, flow/model/qvalue/kind.go, flow/model/qvalue/qvalue.go, flow/workflows/qrep_flow.go
- TSTZRange: Introduce logic to construct the final string in range format
- Supports JSON array
- Supports JSONB and JSONB array
=> Postgres to Postgres: Introduce support for more types

flow/workflows/cdc_flow.go
Set status to running after the initial load only check
=> Optimise state setting for initial load only

flow/peerdbenv/dynamicconf.go
Already unused in rest of code
=> Remove PEERDB_MAX_SYNCS_PER_CDC_FLOW

flow/connectors/utils/cdc_store.go
Need to register tstsrange qvalue type which we newly introduced in gob
=> Register tstzrange in gob

renovate.json
=> renovate: hold back react

renovate.json
=> renovate: also ignore react siblings

flow/activities/flowable.go, flow/workflows/cdc_flow.go, protos/flow.proto
migration introduced in 0.18.1
=> remove table name schema migration

flow/connectors/postgres/postgres.go
https://github.com/PeerDB-io/peerdb/pull/2323#discussion_r1888186520
=> [cdc] always initialize childToParentRelIDMapping

flow/e2e/postgres/peer_flow_pg_test.go, flow/workflows/cdc_flow.go
=> revive custom sync test

flow/activities/flowable_core.go
pointed out by @iamKunalGupta in #2341
=> send flow name with batch id metrics

ui/lib/AppTheme/tailwind.css, ui/lib/Layout/Row.styles.ts, ui/package-lock.json, ui/package.json, ui/postcss.config.js, ui/tailwind.config.ts
ran npx @tailwindcss/upgrade@next --force & then removed erroring lines from tailwind.config.ts
=> tailwindcss v4

flow/connectors/mysql/cdc.go
sync start gets logged by underlying library, which we supply logger to
=> mysql: cleanup while comparing with logging in cdc.go

flow/connectors/mysql/mysql.go
also fix filepos query for mariadb
=> [mysql] disable MariaDB GTID for now

flow/alerting/classifier.go
This error may not be directly mitigable and extra support may be required as per feedback from @saisrirampur
=> chore: move oom-mv to oom category

ui/app/alert-config/layout.tsx, ui/app/config/config.ts, ui/app/mirror-logs/layout.tsx, ui/app/mirrors/layout.tsx, ui/app/page.tsx, ui/app/peers/layout.tsx, ui/app/rest/layout.tsx, ui/app/scripts/layout.tsx, ui/app/settings/layout.tsx, ui/app/supabase/layout.tsx, ui/components/SidebarComponent.tsx
when no password was configured, & no secret supplied, next-auth raised MissingSecretError
we only use session to maintain login & logout
when no password configured, don't use next-auth SessionProvider
=> ui: no session when no password

flow/connectors/mysql/cdc.go, flow/connectors/mysql/mysql.go, flow/connectors/postgres/qvalue_convert.go, flow/connectors/utils/cdc_store.go, flow/e2e/clickhouse/peer_flow_ch_test.go
MySQL includes 0000-00-00 as a valid time outside its accepted range. ClickHouse makes no such special value
So map 0000-00-00 to unix epoch
=> mysql: test more time types

flow/cmd/peer_data.go, flow/connectors/postgres/postgres.go, flow/connectors/postgres/qrep_partition_test.go, flow/connectors/postgres/ssh_wrapped_conn.go, flow/connectors/utils/ssh.go
will make mysql ssh non-impactful to pg code
=> decouple pg & ssh

flow/alerting/classifier.go
Not ignoring everything in netError, will do gradually
=> feat(classifier): ignore notifying user for connection resets

flow/alerting/classifier.go
add psql too many connections as a connectivity error
=> feat(classifier): add too many connections

flow/activities/flowable.go, flow/connectors/mysql/cdc.go, flow/connectors/postgres/cdc.go, flow/otel_metrics/otel_manager.go
InstantaneousFetchedBytesGauge is for billing and RecordsSyncedCounter is for dashboarding
=> feat(metrics): add gauge and counter counterparts of fetched bytes and records synced

flow/alerting/classifier.go
Not sure, but maybe it will require a deeper dive or fixing the downstream MV or View?
=> feat(classifier): add too many parts (when pushing to mv)

flow/connectors/utils/lua.go, flow/go.mod, flow/go.sum
generating correct lua code involved using my fork of flatbuffers,
I thought fixes would get merged upstream but flatbuffers maintainers ignored me
https://github.com/google/flatbuffers/pull/8071
https://github.com/google/flatbuffers/pull/8251
https://github.com/google/flatbuffers/pull/8252
https://github.com/google/flatbuffers/pull/8254
https://github.com/google/flatbuffers/pull/8258
https://github.com/google/flatbuffers/pull/8262
=> remove flatbuffers from lua

flow/e2e/generic/generic_test.go, flow/model/qvalue/equals.go
also extend simple test to include initial load
=> mysql: test JSON

flow/activities/snapshot_activity.go, flow/connectors/mysql/cdc.go, flow/connectors/mysql/mysql.go, flow/e2e/clickhouse/peer_flow_ch_test.go, flow/e2e/generic/generic_test.go, flow/e2e/mysql.go, flow/workflows/snapshot_flow.go, nexus/analyzer/src/lib.rs, nexus/peer-snowflake/src/lib.rs, nexus/peer-snowflake/src/stream.rs, protos/peers.proto, ui/app/peers/create/[peerType]/helpers/my.ts, ui/app/peers/create/[peerType]/schema.ts
prevent splitting transaction across multiple batches
=> mysql: transactional consistency

flow/connectors/bigquery/bigquery.go, flow/peerdbenv/dynamicconf.go
Addresses final `TODO (kaushik)`
=> PEERDB_BIGQUERY_TOAST_MERGE_CHUNKING

flow/alerting/classifier.go
Not touching the existing cases for now, will clean them up later.
=> feat(alerting): classify all other mv related error correctly

flow/activities/flowable.go, flow/activities/flowable_core.go, flow/activities/snapshot_activity.go, flow/alerting/alerting.go
excluded xmin for now
activity/wf interceptors would be ideal instead
=> feat: add alerts on connector setup errors

flow/connectors/mysql/mysql.go, flow/connectors/postgres/postgres.go, flow/connectors/snowflake/snowflake.go
split out from #2597 cleanup & fixing mysql connections even when ca certs properly configured
=> mysql: ServerName

flow/connectors/utils/aws.go
forgot https://github.com/PeerDB-io/peerdb/pull/2598 was set to automerge
=> minor lint miss

flow/cmd/api.go, flow/cmd/snapshot_worker.go, flow/cmd/worker.go, flow/main.go, flow/otel_metrics/otel_manager.go
Currently we return nil instead of error from grpc in many cases -> this leads to incorrect grpc status code
=> feat(flow-api): add grpc server metrics

flow/connectors/mysql/mysql.go
@heavycrystal pointed out DialContext only uses context for connection setup, it has no impact on query
There's ReadTimeout/WriteTimeout which may be able to be bent to act like a context,
but in meantime simplify code to only have one connection at a time
=> mysql: one connection

ui/app/mirrors/[mirrorId]/cdcDetails.tsx, ui/app/mirrors/[mirrorId]/handlers.ts, ui/app/peers/[peerName]/page.tsx, ui/app/peers/create/[peerType]/handlers.ts, ui/app/scripts/handlers.ts
=> also prefer async function to top level async lambda

flow/connectors/bigquery/clustering.go, flow/connectors/mysql/qvalue_convert.go, flow/e2e/clickhouse/clickhouse.go, flow/e2e/clickhouse/peer_flow_ch_test.go, flow/e2e/generic/generic_test.go, flow/e2e/test_utils.go
split out Kevin's code from #2557
Co-authored-by: @heavycrystal
=> Enable generic schema changes for pg to clickhouse

flow/connectors/postgres/postgres.go, flow/connectors/postgres/qrep.go, flow/connectors/utils/monitoring/monitoring.go, flow/shared/postgres.go
avoid logging error when pgx.ErrTxDone wrapped in CatalogError
=> always use shared.RollbackTx

flow/workflows/drop_flow.go
=> avoid nil dereference in drop flow

flow/connectors/clickhouse/cdc.go, flow/connectors/clickhouse/normalize.go, flow/connectors/s3/s3.go, flow/connectors/snowflake/snowflake.go
Found some more call chains in flow code where Env is part of the input but not specified
=> More wiring of Env mapping

flow/connectors/postgres/qvalue_convert.go, flow/e2e/postgres/peer_flow_pg_test.go
=> pg: fix timetz with timezone

flow/activities/flowable_core.go, flow/connectors/core.go, flow/connectors/mysql/cdc.go, flow/connectors/mysql/qrep.go, flow/connectors/postgres/cdc.go, flow/connectors/postgres/qrep.go, flow/connectors/postgres/qrep_query_executor.go, flow/connectors/postgres/sink_pg.go, flow/connectors/postgres/sink_q.go, flow/connectors/sqlserver/qrep.go, flow/otel_metrics/otel_manager.go
1. sqlserver source reports 0 bytes
2. PGPG reports 0 bytes (would need to wrap writer to count bytes)
3. MySQL estimates byte size of fields, ignores compression
=> qrep: fetched bytes

.github/actions/genprotos/action.yml, .github/workflows/ci.yml, .github/workflows/cleanup.yml, .github/workflows/flow.yml, .github/workflows/golang-lint.yml, .github/workflows/stable-docker.yml, .github/workflows/ui-build.yml, .github/workflows/ui-lint.yml
=> remove ubicloud

flow/cmd/mirror_status.go, flow/connectors/utils/monitoring/monitoring.go, nexus/catalog/migrations/V43__cdc_table_aggregate_counts.sql
makes cdc_table_batch table queries more optimized
=> Use aggregate table for counts per table

flow/connectors/snowflake/qrep_avro_sync.go, flow/model/qvalue/kind.go, flow/model/qvalue/qschema.go
Introduced in #595 this feature is untested, caused code duplication,
& does not handle edge cases like mixed case columns well
QRep schema changes were experimental enough they were never ported to any other connector
=> SF qrep: remove schema changes

flow/connectors/mysql/validate.go, flow/e2e/api/api_test.go, flow/e2eshared/e2eshared.go
closes #2772 
also refactor some checks to be available to MariaDB as well
=> [mysql] check RDS/Aurora binlog retention hours

flow/alerting/classifier.go, flow/alerting/classifier_test.go
=> feat(classifier): add bigger decimals

flow/alerting/classifier.go, flow/alerting/classifier_test.go
also moved error check outwards
=> feat(classifier): add wal segment removed as recoverable

flow/activities/maintenance_activity.go
The check for missing workflows needs to be a bit earlier
=> fix(maintenance): move skip-pause on missing wf

flow/activities/flowable.go, flow/connectors/postgres/cdc.go, flow/internal/dynamicconf.go
customer was running into issues with autovacuum, reconnecting resolves, introduce setting to allow reconnecting in these scenarios
=> PEERDB_RECONNECT_AFTER_BATCHES

flow/connectors/mysql/cdc.go
based on https://github.com/go-mysql-org/go-mysql/blob/417b93a01264f5e7b6e2d8700f4064be48394b68/canal/sync.go#L54
=> don't always ignore fake rotation events

flow/connectors/mysql/mysql.go
session variable can sometimes return empty set
=> [mysql] gtid_executed is a global variable

flow/cmd/maintenance.go, flow/main.go, flow/workflows/maintenance_flow.go, nexus/catalog/migrations/V45__maintenance_deploy_version.sql
#2857 
This will now force maintenance to be run on chart upgrades as well
=> feat(maintenance): add skip on deployment version match

flow/alerting/classifier.go
@Amogh-Bharadwaj we would need docs for this mostly
=> feat(classifier): add new class NOTIFY_OOM_SOURCE

.github/workflows/flow.yml, flow/activities/flowable.go, flow/activities/flowable_core.go, flow/activities/maintenance_activity.go, flow/alerting/alerting.go, flow/cmd/api.go, flow/cmd/snapshot_worker.go, flow/cmd/worker.go, flow/connectors/mysql/cdc.go, flow/connectors/postgres/cdc.go, flow/otel_metrics/otel_manager.go
Use Noop MeterProvider instead of Nil Checks everywhere when using otel manager
=> refactor(otel): use noop provider instead of nil checks

flow/connectors/mysql/cdc.go
was relying on code not returning while inTx false, to prevent offset in middle of transaction,
but inTx is not set for transactions modifying tables we ignore, which allows storing offset on row event
even tho we'd ignore this row event, go-mysql library will error because it's missing preceding TableMapEvent
=> mysql: only update filepos on XID/Rotate/Query events

.github/workflows/golang-lint.yml, flow/cmd/handler.go
recent GH action update missed version incompatibility
=> fix golangci-lint

flow/connectors/mysql/qrep.go, flow/connectors/utils/partition/partition.go, flow/e2e/generic/generic_test.go, flow/e2e/test_utils.go, ui/app/mirrors/create/cdc/schemabox.tsx
mysql only has ? parameters, which interacts poorly with qrep templates
instead of using parameters, interpolate partition values into template
=> mysql: qrep partitioning

flow/connectors/postgres/rds_test.go
Test is flaky, KG will look into when he has a chance
=> IAM e2e: skip

flow/workflows/cdc_flow.go
There was a regression introduced by https://github.com/PeerDB-io/peerdb/pull/2764 where we update the flow configuration proto in the flows table in drop flow when we trigger resync.
Unfortunately the mirror configuration passed to this operation as input is an outdated configuration which does not have the latest flow updates - sync interval, batch size or table mappings. So none of those get passed on to the new resynced mirror.
=> Resync fix: update cfg with state before resync calls

flow/connectors/mysql/qvalue_convert.go, flow/connectors/mysql/qvalue_convert_test.go, flow/connectors/utils/avro/avro_writer.go, flow/e2e/clickhouse/mysql_test.go
> TIME values may range from '-838:59:59' to '838:59:59'
https://dev.mysql.com/doc/refman/8.4/en/time.html
=> mysql: support full range of time

flow/alerting/classifier.go
Aurora can lead to this issue and this is expected to be recoverable
=> feat(classifier): aurora zero downtime patch should be recoverable

flow/internal/workflow.go
During maintenance if snapshot flow is dropped, it can sometimes not update the temporal status.
This leads to missing flow entry in catalog once drop succeeds and GetWorkflowStatus falls back to temporal which shows stale status (snapshot).
If instead we get `pgx.ErrNoRows` we can raise the error further and assume there is a bigger issue at hand
- in this case, maintenance would retry the activity and next fetch should not have the mirror in the list at all
=> feat(wf-status): raise error if flow not found in catalog

nexus/analyzer/src/lib.rs, nexus/catalog/src/lib.rs, nexus/parser/src/lib.rs, nexus/peer-ast/src/lib.rs, nexus/peer-bigquery/src/ast.rs, nexus/peer-bigquery/src/lib.rs, nexus/peer-bigquery/src/stream.rs, nexus/peer-cursor/src/util.rs, nexus/peer-mysql/src/ast.rs, nexus/peer-mysql/src/lib.rs, nexus/peer-mysql/src/stream.rs, nexus/peer-postgres/src/ast.rs, nexus/peer-postgres/src/stream.rs, nexus/peer-snowflake/src/ast.rs, nexus/peer-snowflake/src/auth.rs, nexus/peer-snowflake/src/lib.rs, nexus/peer-snowflake/src/stream.rs, nexus/postgres-connection/src/lib.rs, nexus/server/src/main.rs, nexus/server/tests/server_test.rs, nexus/value/src/array.rs, nexus/value/src/lib.rs
not sure why these started raising warnings, but okay
return value is constant so doesn't matter
=> nexus: fix warnings

flow/connectors/bigquery/qrep_avro_sync.go, flow/connectors/utils/avro/avro_writer.go, flow/model/conversion_avro.go, flow/model/qvalue/avro_converter.go
less code, & now we directly pass schema instead of serializing our structs to json to deserialize to hamba schema
=> replace custom avro schema building logic with hamba schema

flow/activities/flowable_core.go, flow/connectors/bigquery/qrep.go, flow/connectors/bigquery/qrep_avro_sync.go, flow/connectors/clickhouse/cdc.go, flow/connectors/clickhouse/qrep.go, flow/connectors/clickhouse/qrep_avro_sync.go, flow/connectors/core.go, flow/connectors/elasticsearch/qrep.go, flow/connectors/kafka/qrep.go, flow/connectors/postgres/qrep.go, flow/connectors/pubsub/qrep.go, flow/connectors/s3/qrep.go, flow/connectors/s3/s3.go, flow/connectors/snowflake/qrep.go, flow/connectors/snowflake/qrep_avro_sync.go, flow/connectors/snowflake/snowflake.go, flow/connectors/utils/avro/avro_writer.go, flow/connectors/utils/monitoring/monitoring.go
most code already moved to int64, but a couple interfaces were casting to int intermittently
split out from #2936
=> convert numrows from int to int64

flow/workflows/cdc_flow.go
we just resync child tables unconditionally if resynced during this stage
=> handle flow-state-change during add tables

flow/shared/postgres.go, flow/shared/shared_test.go
=> ParsePgArrayToStringSlice: map NULL to empty string

flow/workflows/cdc_flow.go
activity can take a long time or enter error loop
=> handle flow-state-change during rename tables

ui/app/mirrors/[mirrorId]/cdcDetails.tsx, ui/app/mirrors/[mirrorId]/columnDisplayModal.tsx, ui/app/mirrors/[mirrorId]/tablePairs.tsx
a modal shows up when we click on the table name
=> feat(ui): pull and show column mapping from source

flow/connectors/mongo/mongo.go
-  ignore irrelevant operation types in changestream
-  for 'delete' operation, it is expected that `fullDocument` field does not exist, so bring back this change.
Tested locally e2e:
- Before this change, drop table upstream would break CDC flow. After this change,  CDC continue to run. 
- Delete operation works again.
=> mongo:  ignore irrelevant operation types in changestream

flow/connectors/mysql/cdc.go, flow/model/cdc_stream.go
avoids pause on inactive mirror resuming with invalid binlog errors
=> mysql: update checkpoint in catalog once an hour while waiting for records

flow/shared/clickhouse/query_retry.go
followup to #3073 reverting some of #3050
=> don't log failed queries

flow/connectors/clickhouse/clickhouse.go, flow/connectors/mysql/mysql.go, flow/connectors/utils/rds.go, flow/connectors/utils/ssh.go, flow/internal/postgres.go, flow/shared/string.go
properly handles IPv6 address as host
=> use net.JoinHostPort

flow/connectors/clickhouse/cdc.go, flow/connectors/clickhouse/normalize.go
1. quote identifiers in rename
2. don't use sql.Null for non-nullable results
=> ch cleanup

flow/cmd/peer_data.go, flow/connectors/mongo/mongo.go
so we don't lose changes that happen during snapshot
deduplication is accepted
=> [mongo] save a resumeToken before starting snapshot

flow/connectors/mongo/mongo.go
Looks like this got overwritten accidentally. Previously approved here: #3076
=> ignore irrelevant updates

flow/connectors/clickhouse/clickhouse.go, flow/e2e/clickhouse/clickhouse.go, flow/e2e/clickhouse/peer_flow_ch_test.go, flow/model/qvalue/avro_converter.go, flow/shared/clickhouse/type_conversion.go, flow/shared/types/kind.go, flow/shared/types/qvalue.go, flow/shared/types/type_converter.go
co-authored-by: @dungeon-master-666
closes #3132
=> Numeric to int256

flow/activities/flowable_core.go, flow/connectors/core.go, flow/connectors/mongo/qrep.go, flow/connectors/mysql/mysql.go, flow/connectors/mysql/qrep.go, flow/connectors/postgres/qrep.go
this avoids full table partitions giving off little information & appearing stuck
=> mysql: report bytes while ingestion still ongoing

ui/app/peers/create/[peerType]/schema.ts
Add missed mongoSchema check on frontend
=> mongo: ui schema validation

flow/cmd/handler.go, flow/internal/dynamicconf.go, protos/route.proto, ui/app/maintenance/page.tsx, ui/components/SidebarComponent.tsx
Tab only available if `PEERDB_UI_MAINTENANCE_TAB_ENABLED` dynamic setting enabled
=> feat(internal): add maintenance ui

flow/connectors/clickhouse/normalize_query.go
trimBoth has run into issues on older clickhouse versions
=> remove trimBoth, don't try parsing raw json in ch normalize

flow/connectors/mysql/qrep.go, flow/connectors/utils/partition.go
current partitioning query was still slow, & I'm not sure why we were doing so much for a simple idea, so splitting up range into go code, only asking mysql for count/min/max. This has been shown to perform much better on real world workloads
=> further simplify mysql partitioning

docker-compose-dev.yml, docker-compose.yml
matches what we use in CI, doesn't require messing with entrypoint
=> use bitnami docker images

ui/components/PeerForms/MySqlForm.tsx, ui/components/PeerForms/PostgresForm.tsx
For fields which are not file input, better to have the input be controlled
=> Fix SSH input component

flow/e2e/mongo/mongo_test.go
Mongo bson docs support up to 100 level of nested depth. Test this gets correctly handled by peerdb.
=> mongo: test nested document at limit

flow/connectors/clickhouse/normalize.go, ui/app/mirrors/create/cdc/customColumnType.tsx, ui/app/mirrors/create/cdc/sortingkey.tsx
split out from #3239
cuts down on having state in component which needs to be consolidated upstream with effects
=> refactor custom order by ui

flow/workflows/cdc_flow.go
=> add tables: adding tables to publication should also be part of selector for loop

flow/e2e/clickhouse/peer_flow_ch_test.go
Add e2e test for JSON types.
The following types are currently not supported by CH JSON:
- number
- string
- boolean
- array
Null is supported, but we parse it to empty string with `JSONExtractString(_peerdb_data, <col>)`, so it's failing to insert in the same way that string type does. `JSONExtractRaw(_peerdb_data, <col>)` works locally. Will look into a fix for the 'null' case as a follow-up.
=> pg: add e2e test for json types

flow/alerting/classifier.go, flow/alerting/classifier_test.go, flow/connectors/postgres/postgres.go, flow/shared/exceptions/application.go
Let's notify users if their replication slot gets deleted
=> Classify replication slot missing

flow/e2e/clickhouse/peer_flow_ch_test.go
1.  use `s.source` to add mysql json test coverage
2. test initial load path as well, not just cdc
Follow up to https://github.com/PeerDB-io/peerdb/pull/3292
=> e2e test for json types should test mysql too

flow/e2e/postgres/qrep_flow_pg_test.go, flow/workflows/cdc_flow.go
=> remove tables: use selector

flow/connectors/mongo/mongo.go
issues with Mongo Atlas, need to investigate further
=> revert preventing any options in Mongo URIs

flow/alerting/classifier.go
got MV error in qrep without FROM
=> classify: still use isClickHouseMvError with QRepSyncError

flow/cmd/validate_mirror.go, flow/cmd/validate_peer.go
we already using long running wfs around provision to catch these
=> refactor(alerting): remove validation telemetry events

flow/connectors/utils/monitoring/monitoring.go, nexus/catalog/migrations/V47__drop_cdc_batch_table.sql
=> DROP TABLE peerdb_stats.cdc_batch_table

flow/workflows/cdc_flow.go
Temporal wraps arbitrary errors as application errors (including activity errors) as of a recent release:
https://github.com/temporalio/sdk-go/releases/tag/v1.31.0
```
Arbitrary errors are translated to ApplicationError as they do in the rest of the Temporal SDK.
```
This PR :
- Removes the `IsApplicationError` check in `cdc_flow.go`
- Removes the long sleeps branch for application errors.
- Reduces the error count reset time to an hour.
=> Sync flow sleeping: change reset time, remove 1hr 20min cap errors

flow/internal/context.go
=> try and add temporal metadata to slog.Logger

.github/workflows/flow.yml, docker-compose-dev.yml, docker-compose.yml
https://github.com/bitnami/charts/issues/35164
=> bitnamilegacy

flow/connectors/mysql/qrep.go
full table partition skips templating, even when estimate is 0 rows we need to query,
go through with normal partitioning logic using single partition
=> mysql: don't fallback to full table partition

flow/connectors/mysql/cdc.go, flow/connectors/mysql/qvalue_convert.go, flow/e2e/clickhouse/mysql_test.go
this has been coming up somehow, usually needing us to suggest resync
embrace mysql culture & try handle shoving square pegs in round holes
=> mysql: try handle strings destined for integers/bools/floats

flow/alerting/classifier.go
error code in alerts is 0 was a giveaway: the error matched the `driver.Error` target but failed because we only checked error code and in the case of poolClearedError, code was not specified:
```
pcErr := poolClearedError{err: p.lastClearErr, address: p.address}
err := driver.Error{
Message: pcErr.Error(),
Labels:  []string{driver.TransientTransactionError},
Wrapped: pcErr,
}
```
=> mongo: use label instead

flow/connectors/postgres/qrep_query_executor_test.go, flow/shared/exceptions/mysql.go
=> Fix linter issues

flow/activities/flowable.go, flow/cmd/handler.go, flow/e2e/api/api_test.go, flow/otel_metrics/observables.go
this can happen when dropping mirror which completed or failed over 30 days ago
=> shutdownFlow: ignore cancel failing due to workflow missing

flow/connectors/utils/avro_writer.go
no need to double buffer io, hamba writes to provided writer after one of either:
1. more bytes buffered than block size
2. more records buffered than block length
by default hamba's buffering is 100 length, with unbounded size,
tune these to more closely resemble our 64MB bufio setup
=> avro: skip bufio, configure hamba avro buffer

flow/model/qvalue/avro_converter.go
cleanup while investigating null array handling
=> refactor avro converter

flow/connectors/postgres/qrep_query_executor.go, flow/connectors/postgres/sink_q.go, flow/connectors/snowflake/snowflake.go, flow/e2e/snowflake_test.go, flow/model/conversion_avro.go
following along from #3504, that PR likely unnecessary since I think hamba infers as much
=> pg qrep: don't assume all columns nullable

flow/activities/flowable.go, flow/workflows/drop_flow.go
this tends to happen when destination database no longer exists
=> drop flow: ignore dns host lookup not found

flow/e2e/api_test.go
=> e2e: test resync doesn't clear custom configurations

flow/activities/flowable.go
- Add check to only process slot information for Postgres sources
- Use specific GetPostgresConnectorByName instead of generic GetByNameAs
=> fix: improve error handling for scheduled slot and log retention tasks
